import{gunzipSync}from'node:zlib';import{sha256,normalize,byteCompare,presentationMatch,preparePresentation}from'./lib.mjs';
const mutationPresentationFields=['mutated_target','edit_original','edit_mutated','atom'];
export function assertMutationNovelty(mutations,registry){const corpus=registry?.presentation_corpus,decode=x=>{try{if(typeof x!=='string'||Buffer.from(x,'base64').toString('base64')!==x)return null;const v=JSON.parse(gunzipSync(Buffer.from(x,'base64')).toString('utf8'));return Array.isArray(v)&&v.every(y=>typeof y==='string')?v:null}catch{return null}},manipulation=decode(corpus?.normalized_manipulation_presentations_gzip_base64),all=decode(corpus?.all_normalized_presentations_gzip_base64),prior=[...(manipulation??[]),...(all??[])].map(preparePresentation);if(!Array.isArray(manipulation)||!Array.isArray(all))throw Error('MUTATION_EXPOSURE_REGISTRY_CORPUS_MISSING');for(const m of mutations?.items??[])for(const field of mutationPresentationFields){const value=m?.[field];if(typeof value!=='string'||!normalize(value))throw Error(`${m?.neutral_id??'unknown'}: invalid mutation presentation ${field}`);const candidate=preparePresentation(value);if(prior.some(exposed=>presentationMatch(candidate,exposed)))throw Error(`${m.neutral_id}: EXPOSED_MUTATION_PRESENTATION:${field}`)}}
const seed='gemini-context-counterexample-reviewer-v1/assignment/v1',required={CONTEXT_MUTANT:24,SURFACE_MUTANT:16,CLEAN_CONTROL:24},half={CONTEXT_MUTANT:12,SURFACE_MUTANT:8,CLEAN_CONTROL:12};
function uniqueMap(items,key,label){const m=new Map();for(const x of items??[]){if(m.has(x[key]))throw Error(`${label}: duplicate ${x[key]}`);m.set(x[key],x)}return m}
export function computeAssignment({clean,mutations,checks,bindings,targets,packets,registry},searchBudget=500000){
  assertMutationNovelty(mutations,registry);
  if(clean.items?.length!==64||mutations.items?.length!==40||checks.items?.length!==40)throw Error('assignment input shortfall');
  const bm=uniqueMap(bindings.items,'neutral_id','bindings'),tm=uniqueMap(targets.items,'neutral_id','targets'),pm=uniqueMap(packets.items,'neutral_id','packets'),mm=uniqueMap(mutations.items,'neutral_id','mutations'),cm=uniqueMap(checks.items,'neutral_id','checks');
  const rows=clean.items.map(x=>{const b=bm.get(x.neutral_id),t=tm.get(x.neutral_id),p=pm.get(x.neutral_id),m=mm.get(x.neutral_id),check=cm.get(x.neutral_id);if(x.verdict!=='CLEAN_NO_MATERIAL_DEFECT'||x.direct_source_verified!==true||!b?.historical_task_id||!t||!p)throw Error(`${x.neutral_id}: clean/source/task binding`);if(x.source_artifact_sha256!==b.source_artifact_sha256||x.context_sha256!==b.context_sha256)throw Error(`${x.neutral_id}: audit lineage`);let role='CLEAN_CONTROL',target=t.target;if(m){role=m.kind==='CONTEXT_REQUIRED'?'CONTEXT_MUTANT':m.kind==='SURFACE_VISIBLE'?'SURFACE_MUTANT':null;if(!role||m.clean_target_sha256!==t.target_sha256||!check?.pass||check.neutral_id!==m.neutral_id||check.one_atom!==true||check.minimal_unique_edit!==true||(m.kind==='CONTEXT_REQUIRED'&&(check.surface_only!=='UNDERDETERMINED'||check.with_context!=='UNIQUELY_REFUTED'))||(m.kind==='SURFACE_VISIBLE'&&(check.surface_only!=='OBJECTIVELY_DETECTABLE'||check.with_context!=='NOT_APPLICABLE')))throw Error(`${x.neutral_id}: mutation/check binding`);const at=t.target.indexOf(m.edit_original);if(at<0||at!==t.target.lastIndexOf(m.edit_original)||`${t.target.slice(0,at)}${m.edit_mutated}${t.target.slice(at+m.edit_original.length)}`!==m.mutated_target)throw Error(`${x.neutral_id}: mutation target binding`);target=m.mutated_target}return{base_id:x.neutral_id,role,b,source:t.source,target,source_context:p.source_context}});
  for(const[k,n]of Object.entries(required))if(rows.filter(x=>x.role===k).length!==n)throw Error(`${k}: quota`);if(new Set(rows.map(x=>normalize(x.source))).size!==64||new Set(rows.map(x=>sha256(normalize(x.source_context)))).size!==64)throw Error('input disjointness');
  const order=(cohort,x)=>sha256(`${seed}\0${x.base_id}\0${cohort}`);rows.sort((a,b)=>byteCompare(order('discovery',a),order('discovery',b))||byteCompare(a.base_id,b.base_id));const byFile=new Map();for(const x of rows){const g=byFile.get(x.b.relative_path)??[];g.push(x);byFile.set(x.b.relative_path,g)}if([...byFile.values()].some(g=>g.length>2))throw Error('source-file cap');const groups=[...byFile.entries()].map(([file,g])=>({file,g:g.sort((a,b)=>byteCompare(a.base_id,b.base_id))})).sort((a,b)=>byteCompare(order('discovery',a.g[0]),order('discovery',b.g[0]))||byteCompare(a.file,b.file));
  let solution=null,nodes=0;function tally(xs,key){return xs.reduce((n,x)=>n+(x.role===key),0)}function valid(xs){return Object.keys(half).every(k=>tally(xs,k)<=half[k])&&[...new Set(xs.map(x=>x.b.historical_task_id))].every(t=>xs.filter(x=>x.b.historical_task_id===t).length<=4)}function search(i,d){if(solution)return;if(++nodes>searchBudget)throw Error(`ASSIGNMENT_SEARCH_BUDGET_EXCEEDED:${searchBudget}`);if(i===groups.length){const ds=new Set(d.map(x=>x.base_id)),c=rows.filter(x=>!ds.has(x.base_id));if(Object.keys(half).every(k=>tally(d,k)===half[k]&&tally(c,k)===half[k])&&valid(c))solution=d;return}const remain=groups.slice(i).flatMap(x=>x.g);for(const k of Object.keys(half))if(tally(d,k)>half[k]||tally(d,k)+tally(remain,k)<half[k])return;const g=groups[i].g;if(valid([...d,...g]))search(i+1,[...d,...g]);search(i+1,d)}search(0,[]);if(!solution)throw Error('INSUFFICIENT_ASSIGNMENT');const ds=new Set(solution.map(x=>x.base_id)),confirmation=rows.filter(x=>!ds.has(x.base_id));
  function sample(xs,phase){return{schema_version:'gemini-context-sample-v2',phase,assignment_seed:seed,items:[...xs].sort((a,b)=>byteCompare(sha256(`${seed}\0${phase}\0${a.base_id}`),sha256(`${seed}\0${phase}\0${b.base_id}`))||byteCompare(a.base_id,b.base_id)).map((x,i)=>({global_item_id:`${phase==='discovery'?'D':'C'}-I${String(i+1).padStart(3,'0')}`,base_id:x.base_id,role:x.role,source:x.source,target:x.target,source_context:x.source_context}))}}return{discovery:sample(solution,'discovery'),confirmation:sample(confirmation,'confirmation'),search_nodes:nodes,search_budget:searchBudget};
}
