#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{sha256,normalize,jsonBytes,safeRelative,byteCompare}from'./lib.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),canonicalPath=path.join(here,'FROZEN-CANONICAL-FRAME.json'),registryPath=path.join(here,'EXPOSURE-REGISTRY.json');
const canonical=JSON.parse(fs.readFileSync(canonicalPath)),reg=JSON.parse(fs.readFileSync(registryPath));if(canonical.item_count!==127||canonical.items?.length!==127)throw Error('frozen canonical frame count');if(reg.canonical_frame_sha256!==sha256(fs.readFileSync(canonicalPath)))throw Error('exposure registry/canonical binding');
const sets=Object.fromEntries(Object.entries(reg.keys).map(([k,v])=>[k,new Set(v)])),presentationHits=new Map();for(const h of reg.candidate_presentation_hits??[]){const x=presentationHits.get(h.neutral_id)??new Set();x.add(h.field);presentationHits.set(h.neutral_id,x)}
const counts={frozen_candidate_frame:canonical.items.length,semantic_path_rejected:0,source_or_revision_exposure_rejected:0,normalized_context_exposure_rejected:0,target_or_manipulation_exposure_rejected:0,eligible_before_file_cap:0,file_cap_rejected:0,duplicate_normalized_source_or_context_rejected:0,available_after_file_cap:0},ledger=[],eligible=[];
for(const x of canonical.items){const reasons=[],rel=x.relative_path,hits=presentationHits.get(x.neutral_id)??new Set();if(!['dialogue','narrative'].includes(x.profile)||!safeRelative(rel)||!/^game\/modules\/tome\/data\/(?:chats|lore)\/[^/]+\.lua$/u.test(rel))reasons.push('SEMANTIC_PATH');if(sets.normalized_sources.has(x.normalized_source_sha256)||sets.all_normalized_presentations.has(x.normalized_source_sha256)||sets.revision_values.has(sha256(x.revision_id))||hits.has('source')||hits.has('revision_id'))reasons.push('SOURCE_OR_REVISION_EXPOSURE');if(sets.normalized_contexts.has(x.normalized_context_sha256)||sets.all_normalized_presentations.has(x.normalized_context_sha256)||hits.has('context'))reasons.push('CONTEXT_EXPOSURE');if(sets.normalized_target_presentations.has(x.normalized_target_sha256)||sets.normalized_manipulation_presentations.has(x.normalized_target_sha256)||sets.all_normalized_presentations.has(x.normalized_target_sha256)||hits.has('target'))reasons.push('TARGET_OR_MANIPULATION_EXPOSURE');const primary=reasons[0]??null;if(primary==='SEMANTIC_PATH')counts.semantic_path_rejected++;else if(primary==='SOURCE_OR_REVISION_EXPOSURE')counts.source_or_revision_exposure_rejected++;else if(primary==='CONTEXT_EXPOSURE')counts.normalized_context_exposure_rejected++;else if(primary==='TARGET_OR_MANIPULATION_EXPOSURE')counts.target_or_manipulation_exposure_rejected++;if(!reasons.length)eligible.push(x);ledger.push({neutral_id:x.neutral_id,reasons,decision:reasons.length?'REJECT':'PENDING_CAPS'})}
counts.eligible_before_file_cap=eligible.length;eligible.sort((a,b)=>byteCompare(sha256(`gemini-context-v1\0${a.neutral_id}`),sha256(`gemini-context-v1\0${b.neutral_id}`))||byteCompare(a.neutral_id,b.neutral_id));const selected=[],fc=new Map(),seenSource=new Set(),seenContext=new Set();for(const x of eligible){let reason=null;if((fc.get(x.relative_path)??0)>=2)reason='FILE_CAP';else if(seenSource.has(x.normalized_source_sha256)||seenContext.has(x.normalized_context_sha256))reason='DUPLICATE_NORMALIZED_SOURCE_OR_CONTEXT';if(reason){counts[reason==='FILE_CAP'?'file_cap_rejected':'duplicate_normalized_source_or_context_rejected']++;const q=ledger.find(y=>y.neutral_id===x.neutral_id);q.reasons.push(reason);q.decision='REJECT';continue}selected.push(x);fc.set(x.relative_path,(fc.get(x.relative_path)??0)+1);seenSource.add(x.normalized_source_sha256);seenContext.add(x.normalized_context_sha256);ledger.find(y=>y.neutral_id===x.neutral_id).decision='ELIGIBLE'}counts.available_after_file_cap=selected.length;
const provenance={canonical_frame_sha256:sha256(fs.readFileSync(canonicalPath)),source_snapshot_sha256:canonical.source_snapshot.sha256,exposure_registry_sha256:sha256(fs.readFileSync(registryPath)),builder_sha256:sha256(fs.readFileSync(fileURLToPath(import.meta.url)))};
const frame={schema_version:'gemini-context-source-frame-v3',status:'ZERO_INFERENCE_REFILTERED',provenance,semantic_scope:{allowed_paths:['game/modules/tome/data/chats/*.lua','game/modules/tome/data/lore/*.lua'],profile_labels:['dialogue','narrative']},counts,items:selected.map(x=>({neutral_id:x.neutral_id,profile:x.profile,source:x.source,source_sha256:x.source_sha256}))},local={schema_version:'gemini-context-local-bindings-v3',model_facing:false,provenance,items:selected.map(x=>({neutral_id:x.neutral_id,revision_id:x.revision_id,historical_task_id:null,relative_path:x.relative_path,source_artifact_sha256:x.source_artifact_sha256,source_sha256:x.source_sha256,normalized_source_sha256:x.normalized_source_sha256,context_sha256:x.context_sha256,normalized_context_sha256:x.normalized_context_sha256}))},targets={schema_version:'gemini-context-target-bindings-v3',items:selected.map(x=>({neutral_id:x.neutral_id,source:x.source,source_sha256:x.source_sha256,target:x.target,target_sha256:x.target_sha256,context_sha256:x.context_sha256}))},packets={schema_version:'gemini-context-source-packets-v3',items:selected.map(x=>({neutral_id:x.neutral_id,source_sha256:x.source_sha256,source_context:x.source_context,context_sha256:x.context_sha256,normalized_context_sha256:x.normalized_context_sha256}))};
const surface={schema_version:'gemini-context-surface-audit-queue-v2',status:'FROZEN_NOT_RELEASED',release_prerequisite:'HISTORICAL_TASK_BINDING',items:targets.items},context={schema_version:'gemini-context-context-audit-queue-v2',status:'BLOCKED_UNTIL_MATCHING_SURFACE_PASS',items:selected.map(x=>({neutral_id:x.neutral_id,source_sha256:x.source_sha256,target_sha256:x.target_sha256,source_artifact_sha256:x.source_artifact_sha256,context_sha256:x.context_sha256,source_context:x.source_context}))};
const shortfall=Math.max(0,64-selected.length),blocking=[...(shortfall?['BASE_POOL_SHORTFALL']:[]),'HISTORICAL_TASK_BINDING','FULL_INVENTORY_AVAILABILITY_NOT_ESTABLISHED'],availability={schema_version:'gemini-context-availability-v4',status:shortfall?'INSUFFICIENT_FROZEN_FRAME':'FROZEN_FRAME_POOL_AVAILABLE_AUDIT_PENDING',required_bases:64,eligible_bases:selected.length,shortfall_bases:shortfall,derivation_exact_for_frozen_127_row_frame:true,full_inventory_availability:'NOT_ESTABLISHED',provenance,exact_rejection_counts:counts,constraints_checked:{semantic_and_path_scope:true,all_candidate_presentations_across_all_prior_values:true,max_two_per_source_file:true,max_four_per_historical_task:'UNRESOLVED_HARD_GATE'},blocking_gates:blocking,inference_allowed:false};
const rejection={schema_version:'gemini-context-rejection-ledger-v1',provenance,ordering:'preserved neutral_id order from frozen canonical frame',counts,items:ledger};
for(const[n,v]of Object.entries({'SOURCE-FRAME.json':frame,'SOURCE-PACKETS.json':packets,'LOCAL-BINDINGS.json':local,'TARGET-BINDINGS.json':targets,'SURFACE-AUDIT-QUEUE.json':surface,'CONTEXT-AUDIT-QUEUE.json':context,'AVAILABILITY.json':availability,'REFILTER-REJECTION-LEDGER.json':rejection}))fs.writeFileSync(path.join(here,n),jsonBytes(v));console.log(JSON.stringify(availability,null,2));
