#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {BASELINE,ROUTES,SHARDS,assert,frozenBindings,makeBundle,makeRuntime,removeTemp,runOfflineProbe,scanOutbound,outboundFiles,sha256File,writeNew} from "./runner-lib.mjs";
const here=path.dirname(fileURLToPath(import.meta.url)); const write=process.argv.includes("--write");
const errors=[]; const versions={},availability={}; const frozen=frozenBindings(here);
for(const n of SHARDS) errors.push(...scanOutbound(outboundFiles(here,n)));
for(const [key,route] of Object.entries(ROUTES)){let bundle,runtime;try{bundle=makeBundle(here,1);runtime=makeRuntime(route);const ver=runOfflineProbe(route,["--version"],runtime,bundle);versions[key]=ver.stdout.trim();if(ver.status!==0||versions[key]!==route.version)errors.push(`${key}: version mismatch (${versions[key]||ver.stderr.trim()})`);if(route.kind==="codex"){const x=runOfflineProbe(route,["debug","models","--bundled"],runtime,bundle);availability[key]=x.status===0&&/"slug":"gpt-5\.6-sol"/u.test(x.stdout);}else if(route.kind==="pi"){const x=runOfflineProbe(route,["--list-models",route.model],runtime,bundle);availability[key]=x.status===0&&/zai-standard-cn\s+glm-5\.3-flash/u.test(x.stdout);}else if(route.kind==="agy"){const x=runOfflineProbe(route,["models"],runtime,bundle);availability[key]=x.status===0&&/^gemini-3\.7-flash-high\s/mu.test(x.stdout);}else availability[key]="RUNTIME_STREAM_ONLY";if(availability[key]===false)errors.push(`${key}: requested model unavailable`);}catch(e){errors.push(`${key}: ${e.message}`);availability[key]=false;}finally{if(bundle&&fs.existsSync(bundle))removeTemp(bundle,"rfr-bundle-");if(runtime&&fs.existsSync(runtime))removeTemp(runtime,"rfr-runtime-");}}
const head=(await import("node:child_process")).spawnSync("git",["rev-parse","HEAD"],{cwd:path.resolve(here,"../../../.."),encoding:"utf8"}).stdout.trim();if(head!==BASELINE)errors.push(`baseline mismatch ${head}`);
const record={schema_version:"route-familiarity-reference-preflight-v1",status:errors.length?"NO_GO":"GO",inference_performed:false,baseline_commit:head,predecessor_artifacts:frozen.files,route_versions:versions,model_availability:availability,claude_model_availability_note:"Exact model is verified only from actual runtime stream; no offline list is treated as trustworthy.",outbound_file_set:["PROMPT.md","OUTBOUND-SHARD-NN.json","RESPONSE-SCHEMA-SHARD-NN.json"],errors};
if(write)writeNew(path.join(here,"PREFLIGHT.json"),`${JSON.stringify(record,null,2)}\n`);process.stdout.write(`${JSON.stringify(record,null,2)}\n`);if(errors.length)process.exitCode=2;
