import fs from 'node:fs';import path from 'node:path';import {readCanonical,readJsonSafe,shaFile,sha256,jsonBytes,byteCompare} from './lib.mjs';import {verifyCandidateAtRoot} from './control-plane.mjs';import {mutationGate} from './mutation-gate.mjs';import {validateFrozenArtifactsOnDisk} from './freezer.mjs';import {validateQualification} from './qualification.mjs';
export const TASK='.ai/task/research-gemini-context-counterexample-reviewer-v5-execution-v1';
export const gatePaths={identity:`${TASK}/CANDIDATE-IDENTITY.json`,review:`${TASK}/IMPLEMENTATION-DUAL-REVIEW-GATE.json`,mutation:`${TASK}/MUTATION-VALIDATION-GATE.json`,freeze:`${TASK}/FREEZE-GATE.json`,qualification:`${TASK}/QUALIFICATION-GATE.json`,authorization:`${TASK}/EXECUTION-AUTHORIZATION.json`,discoveryReceipt:`${TASK}/DISCOVERY-COMPLETION-RECEIPT.json`,confirmation:`${TASK}/CONFIRMATION-AUTHORIZATION.json`};
const packageRel='evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v1',taskId='research-gemini-context-counterexample-reviewer-v5-execution-v1',order=['review','mutation','freeze','qualification','authorization'],statuses={review:'SATISFIED_EXACT_DUAL_PASS',mutation:'SATISFIED_40_OF_40',freeze:'SATISFIED_EXACT_REQUEST_FREEZE',qualification:'SATISFIED_NON_SCORED_ROUTE_QUALIFICATION',authorization:'AUTHORIZED_EXACT_REQUESTS_AND_ROUTE'},schemas=Object.fromEntries(order.map(p=>[p,`gemini-context-v5-${p}-gate-v2`]));
const exact=(x,k)=>x&&JSON.stringify(Object.keys(x).sort(byteCompare))===JSON.stringify([...k].sort(byteCompare)),hex=x=>/^[0-9a-f]{64}$/u.test(x??'');
const identityKeys=['candidate_ref','file_count','hash_dag_path','hash_dag_sha256','manifest_path','manifest_sha256','schema_version','task_id'];
export function readCandidateIdentity(repo,manifest,errors=[]){const p=path.join(repo,gatePaths.identity);if(!fs.existsSync(p)){errors.push('identity:ABSENT');return null}let x;try{x=readCanonical(p)}catch(e){errors.push(`identity:${e.message}`);return null}const mp=path.join(repo,x.manifest_path??''),dp=path.join(repo,x.hash_dag_path??'');if(!exact(x,identityKeys)||x.schema_version!=='gemini-context-v5-candidate-identity-v1'||x.task_id!==taskId||x.candidate_ref!==manifest.candidate_ref||x.file_count!==manifest.file_count||x.manifest_path!==`${packageRel}/CANDIDATE-MANIFEST.json`||x.hash_dag_path!==`${packageRel}/HASH-DAG.json`||!hex(x.manifest_sha256)||!hex(x.hash_dag_sha256)||!fs.existsSync(mp)||!fs.existsSync(dp)||shaFile(mp)!==x.manifest_sha256||shaFile(dp)!==x.hash_dag_sha256)errors.push('identity:SCHEMA_BYTES');return x}
function bind(repo,b,want,errors,label){if(!exact(b,['path','sha256'])||b.path!==want||!hex(b.sha256)){errors.push(`${label}:BINDING`);return null}const p=path.join(repo,want);if(!fs.existsSync(p)||shaFile(p)!==b.sha256){errors.push(`${label}:HASH`);return null}return readCanonical(p)}
const reviewKeys=['agent_id','candidate_ref','dispatch_id','findings','hash_dag_sha256','manifest_sha256','purpose','read_only','reviewed_file_count','reviewed_files','reviewed_root_sha256','role','runtime_model','schema_version','selected_model','task_id','verdict'];
function review(repo,b,want,role,identity,manifest,errors,label){const r=bind(repo,b,want,errors,label);if(!r)return null;const files=manifest.files.map(x=>x.path);if(!exact(r,reviewKeys)||r.schema_version!=='gemini-context-v5-strict-review-v1'||r.task_id!==taskId||r.candidate_ref!==identity.candidate_ref||r.manifest_sha256!==identity.manifest_sha256||r.hash_dag_sha256!==identity.hash_dag_sha256||r.role!==role||r.purpose!==(role==='REVIEWER'?'normal_review':'cross_review')||r.selected_model!==(role==='REVIEWER'?'openai-codex/gpt-5.6-sol':'claude-fable-5-1[1m]')||r.runtime_model!==(role==='REVIEWER'?'openai-codex/gpt-5.6-sol':'claude-fable-5-1')||r.read_only!==true||!['PASS','CHANGES_REQUIRED'].includes(r.verdict)||r.reviewed_file_count!==files.length||JSON.stringify(r.reviewed_files)!==JSON.stringify(files)||r.reviewed_root_sha256!==identity.candidate_ref||!Array.isArray(r.findings))errors.push(`${label}:STRICT_SCHEMA`);
 const state=readJsonSafe(path.join(repo,TASK,'STATE.json')),ds=state.child_dispatches?.filter(x=>x.dispatch_id===r.dispatch_id&&x.agent_id===r.agent_id&&x.role===role&&x.purpose===r.purpose&&x.lineage_verified===true&&x.lifecycle==='archived'&&x.archive_confirmed===true)??[];if(ds.length!==1)errors.push(`${label}:STATE_LINEAGE_ARCHIVE_UNIQUE`);return r}
const common=['candidate_ref','hash_dag_sha256','manifest_sha256','phase','schema_version','status','task_id'];
const phaseKeys={review:[...common,'normal_review','senior_review'],mutation:[...common,'author_receipt','predecessor_gate','proposal_evidence','validation_evidence','validator_receipt'],freeze:[...common,'predecessor_gate','request_manifest'],qualification:[...common,'predecessor_gate','qualification_evidence'],authorization:[...common,'predecessor_gate','qualification_evidence_sha256','request_manifest_sha256','request_sha256','route_contract_sha256']};
function predecessor(repo,g,phase,identity,errors){const i=order.indexOf(phase),prev=order[i-1],want=gatePaths[prev],b=g.predecessor_gate;if(!exact(b,['candidate_ref','hash_dag_sha256','manifest_sha256','path','phase','schema_version','sha256'])||b.schema_version!=='gemini-context-v5-phase-gate-binding-v2'||b.phase!==prev||b.candidate_ref!==identity.candidate_ref||b.manifest_sha256!==identity.manifest_sha256||b.hash_dag_sha256!==identity.hash_dag_sha256||b.path!==want||!hex(b.sha256))errors.push(`${phase}:PREDECESSOR_SCHEMA_FIELDS`);else if(!fs.existsSync(path.join(repo,want))||shaFile(path.join(repo,want))!==b.sha256)errors.push(`${phase}:PREDECESSOR_HASH`)}
function completion(repo,b,want,purpose,outputs,identity,errors,label,predecessorPath){const r=bind(repo,b,want,errors,label);if(!r)return;const ks=['agent_id','archive_confirmed','candidate_ref','direct_predecessor','dispatch_id','hash_dag_sha256','lifecycle','lineage_verified','manifest_sha256','output_hashes','purpose','role','schema_version','status','task_id'];if(!exact(r,ks)||r.schema_version!=='gemini-context-v5-lifecycle-completion-receipt-v2'||r.task_id!==taskId||r.role!=='EXECUTOR'||r.purpose!==purpose||r.status!=='AUTHORIZED_COMPLETED'||r.lineage_verified!==true||r.lifecycle!=='archived'||r.archive_confirmed!==true||r.candidate_ref!==identity.candidate_ref||r.manifest_sha256!==identity.manifest_sha256||r.hash_dag_sha256!==identity.hash_dag_sha256||JSON.stringify(r.output_hashes)!==JSON.stringify(outputs)||!exact(r.direct_predecessor,['path','sha256'])||r.direct_predecessor.path!==predecessorPath||!fs.existsSync(path.join(repo,predecessorPath))||r.direct_predecessor.sha256!==shaFile(path.join(repo,predecessorPath)))errors.push(`${label}:FIELDS_OUTPUTS`);const state=readJsonSafe(path.join(repo,TASK,'STATE.json')),d=state.child_dispatches?.find(x=>x.dispatch_id===r.dispatch_id&&x.agent_id===r.agent_id&&x.role==='EXECUTOR'&&x.purpose===purpose&&x.lineage_verified===true&&x.lifecycle==='archived'&&x.archive_confirmed===true);if(!d)errors.push(`${label}:STATE_LINEAGE_ARCHIVE`)}
export function validatePhaseGates(repo,manifestIgnored,through='authorization'){
 const errors=[],complete={},root=path.join(repo,packageRel);let verified;try{verified=verifyCandidateAtRoot(root);errors.push(...verified.errors.map(x=>`candidate:${x}`))}catch(e){errors.push(`candidate:${e.message}`);return{valid:false,errors,complete,identity:null}}const manifest=verified.manifest,identity=readCandidateIdentity(repo,manifest,errors);if(!identity)return{valid:false,errors,complete,identity:null};
 for(const phase of order){const needed=order.indexOf(phase)<=order.indexOf(through),p=path.join(repo,gatePaths[phase]);if(!fs.existsSync(p)){complete[phase]=false;if(needed)errors.push(`${phase}:ABSENT`);continue}let g;try{g=readCanonical(p)}catch(e){errors.push(`${phase}:${e.message}`);complete[phase]=false;continue}const before=errors.length;if(!exact(g,phaseKeys[phase])||g.schema_version!==schemas[phase]||g.task_id!==taskId||g.phase!==phase||g.status!==statuses[phase]||g.candidate_ref!==identity.candidate_ref||g.manifest_sha256!==identity.manifest_sha256||g.hash_dag_sha256!==identity.hash_dag_sha256)errors.push(`${phase}:SCHEMA_FIELDS`);
  if(phase==='review'){const a=review(repo,g.normal_review,`${TASK}/NORMAL-REREVIEW.json`,'REVIEWER',identity,manifest,errors,'review:normal'),b=review(repo,g.senior_review,`${TASK}/SENIOR-REREVIEW.json`,'SENIOR_REVIEWER',identity,manifest,errors,'review:senior');if(a?.verdict!=='PASS'||b?.verdict!=='PASS'||a?.agent_id===b?.agent_id||a?.dispatch_id===b?.dispatch_id)errors.push('review:DUAL_PASS_DISTINCT')}else predecessor(repo,g,phase,identity,errors);
  if(phase==='mutation'){const pp=`${packageRel}/sealed/MUTATION-PROPOSALS.json`,vp=`${packageRel}/sealed/MUTATION-VALIDATIONS.json`;bind(repo,g.proposal_evidence,pp,errors,'mutation:proposals');bind(repo,g.validation_evidence,vp,errors,'mutation:validations');const outA={proposal_sha256:g.proposal_evidence?.sha256},outV={proposal_sha256:g.proposal_evidence?.sha256,validation_sha256:g.validation_evidence?.sha256};completion(repo,g.author_receipt,`${TASK}/MUTATION-AUTHOR-LIFECYCLE-RECEIPT.json`,'mutation_author',outA,identity,errors,'mutation:author',gatePaths.review);completion(repo,g.validator_receipt,`${TASK}/MUTATION-VALIDATOR-LIFECYCLE-RECEIPT.json`,'independent_mutation_validator',outV,identity,errors,'mutation:validator',`${TASK}/MUTATION-AUTHOR-LIFECYCLE-RECEIPT.json`)}
  if(phase==='mutation'){const mg=mutationGate(root,{repoRoot:repo,statePath:path.join(repo,TASK,'STATE.json')});if(mg.status!=='PASS'||mg.proposals!==40||mg.validations!==40)errors.push(`mutation:SEMANTICS:${mg.errors?.join(',')}`)}
  if(phase==='freeze'){bind(repo,g.request_manifest,`${packageRel}/frozen/REQUEST-MANIFEST.json`,errors,'freeze:manifest');errors.push(...validateFrozenArtifactsOnDisk(root).map(x=>`freeze:${x}`))}if(phase==='qualification'){bind(repo,g.qualification_evidence,`${packageRel}/qualification/EVIDENCE.json`,errors,'qualification:evidence');const q=validateQualification(root,{repoRoot:repo,statePath:path.join(repo,TASK,'STATE.json'),skipPhaseGate:true});if(!q.valid)errors.push(`qualification:SEMANTICS:${q.errors.join(',')}`)}if(phase==='authorization'){const rm=path.join(repo,packageRel,'frozen/REQUEST-MANIFEST.json'),qp=path.join(repo,packageRel,'qualification/EVIDENCE.json'),rp=path.join(repo,packageRel,'ROUTE-CONTRACT.json');if(!fs.existsSync(rm)||!fs.existsSync(qp)||!fs.existsSync(rp))errors.push('authorization:BOUND_ARTIFACT_ABSENT');else{const m=readCanonical(rm),requestHash=sha256(jsonBytes(m.requests.map(x=>({path:x.path,sha256:x.sha256}))));if(g.request_manifest_sha256!==shaFile(rm)||g.qualification_evidence_sha256!==shaFile(qp)||g.route_contract_sha256!==shaFile(rp)||g.request_sha256!==requestHash)errors.push('authorization:EXACT_BINDING')}}complete[phase]=errors.length===before}
 return{valid:errors.length===0,errors,complete,identity};
}
export function validateConfirmationAuthorization(repo,manifest,winner,discoveryHash){const e=[],phase=validatePhaseGates(repo,manifest,'authorization');e.push(...phase.errors);if(!phase.identity)return{valid:false,errors:e};const rp=path.join(repo,gatePaths.discoveryReceipt),ap=path.join(repo,gatePaths.confirmation);let r,a;try{r=readCanonical(rp);a=readCanonical(ap)}catch(x){return{valid:false,errors:[...e,x.message]}}const rk=['candidate_ref','discovery_output_sha256','hash_dag_sha256','manifest_sha256','schema_version','task_id','winner'],ak=['candidate_ref','direct_predecessor','discovery_output_sha256','hash_dag_sha256','manifest_sha256','schema_version','status','task_id','winner'];if(!exact(r,rk)||r.schema_version!=='gemini-context-v5-discovery-completion-receipt-v1'||r.winner!==winner||r.discovery_output_sha256!==discoveryHash||r.candidate_ref!==phase.identity.candidate_ref||r.manifest_sha256!==phase.identity.manifest_sha256||r.hash_dag_sha256!==phase.identity.hash_dag_sha256)e.push('DISCOVERY_RECEIPT');if(!exact(a,ak)||a.schema_version!=='gemini-context-v5-confirmation-authorization-v1'||a.status!=='AUTHORIZED_A_PLUS_WINNER'||a.winner!==winner||a.discovery_output_sha256!==discoveryHash||a.candidate_ref!==phase.identity.candidate_ref||a.manifest_sha256!==phase.identity.manifest_sha256||a.hash_dag_sha256!==phase.identity.hash_dag_sha256||!exact(a.direct_predecessor,['path','sha256'])||a.direct_predecessor.path!==gatePaths.discoveryReceipt||a.direct_predecessor.sha256!==shaFile(rp))e.push('CONFIRMATION_AUTH');return{valid:e.length===0,errors:e}}
