import {sha256,jsonBytes} from './lib.mjs';
const roles=new Set(['CONTEXT_MUTANT','SURFACE_MUTANT','CLEAN_CONTROL']),claims=new Set(['SUBJECT','REFERENT','EVENT','CONDITION','SCOPE','DIRECTION','POLARITY','OWNERSHIP','ACTION','STATE','TIMING','OMISSION','ADDITION','FORMAT','OTHER']);
const keys=(x,ks)=>x&&JSON.stringify(Object.keys(x).sort())===JSON.stringify([...ks].sort());
export function validateReference(ref,sampleDoc,expectedHash){
  const e=[];if(expectedHash&&sha256(jsonBytes(ref))!==expectedHash)e.push('REFERENCE_HASH');
  if(!keys(ref,['items','sample_sha256','schema_version'])||ref?.schema_version!=='gemini-context-v5-sealed-reference-v4'||!Array.isArray(ref.items)||ref.items.length!==64)return[...e,'REFERENCE_SCHEMA_COUNT'];
  if(!sampleDoc||ref.sample_sha256!==sha256(jsonBytes(sampleDoc)))e.push('REFERENCE_SAMPLE_HASH');
  const baseItems=sampleDoc?.items??[],ids=baseItems.map(x=>x.item_id);
  ref.items.forEach((x,i)=>{if(!keys(x,['atoms','cohort','item_id','profile','role','row_sha256'])||x.item_id!==ids[i]||x.cohort!==baseItems[i]?.cohort||x.profile!==baseItems[i]?.profile||!roles.has(x.role)||!Array.isArray(x.atoms))e.push(`REFERENCE_ITEM:${i}`);const row={...x};delete row.row_sha256;if(x.row_sha256!==sha256(jsonBytes(row)))e.push(`REFERENCE_ROW_HASH:${i}`);if(x.role==='CLEAN_CONTROL'&&x.atoms.length)e.push(`CLEAN_ATOMS:${i}`);if(x.role!=='CLEAN_CONTROL'&&x.atoms.length!==1)e.push(`MUTANT_ATOMS:${i}`);for(const[j,a]of x.atoms.entries())if(!keys(a,['atom_id','claim_types','target_spans'])||typeof a.atom_id!=='string'||!Array.isArray(a.claim_types)||!a.claim_types.every(c=>claims.has(c))||!Array.isArray(a.target_spans)||!a.target_spans.every(s=>typeof s==='string'&&s))e.push(`ATOM:${i}:${j}`)});
  for(const c of ['discovery','confirmation'])for(const p of ['dialogue','narrative'])for(const[r,n]of Object.entries({CONTEXT_MUTANT:6,SURFACE_MUTANT:4,CLEAN_CONTROL:6}))if(ref.items.filter(x=>x.cohort===c&&x.profile===p&&x.role===r).length!==n)e.push(`ROLE_QUOTA:${c}:${p}:${r}`);return e;
}
export function score(candidate,ref){if(candidate?.valid!==true||candidate.identity_tier!=='QUALIFIED_ROUTE_BOUND')throw Error('INVALID_CELL_NOT_SCORABLE');const byId=new Map(ref.items.map(x=>[x.item_id,x])),seenItems=new Set(),hitAtoms=new Set(),findingItems=new Set();let uniqueFindings=0;for(const out of candidate.response.items){if(seenItems.has(out.item_id))throw Error(`DUPLICATE_ITEM:${out.item_id}`);seenItems.add(out.item_id);const r=byId.get(out.item_id);if(!r)throw Error(`UNKNOWN_ITEM:${out.item_id}`);const seenCandidates=new Set();for(const c of out.candidates){if(c.verdict!=='FINDING')continue;const ck=JSON.stringify([c.claim_type,c.target_span,c.correction,c.evidence]);if(seenCandidates.has(ck))continue;seenCandidates.add(ck);uniqueFindings++;findingItems.add(out.item_id);for(const a of r.atoms)if(a.claim_types.includes(c.claim_type)&&a.target_spans.some(s=>c.target_span.includes(s)))hitAtoms.add(`${out.item_id}\0${a.atom_id}`)}}const contextIds=new Set(ref.items.filter(x=>x.role==='CONTEXT_MUTANT').map(x=>x.item_id)),surfaceIds=new Set(ref.items.filter(x=>x.role==='SURFACE_MUTANT').map(x=>x.item_id)),cleanIds=new Set(ref.items.filter(x=>x.role==='CLEAN_CONTROL').map(x=>x.item_id));const hits=set=>[...hitAtoms].filter(k=>set.has(k.split('\0')[0])).length;return{items:seenItems.size,unique_findings:uniqueFindings,context:{atoms_total:contextIds.size,atom_hits:hits(contextIds),item_hits:[...contextIds].filter(id=>[...hitAtoms].some(k=>k.startsWith(`${id}\0`))).length},surface:{atoms_total:surfaceIds.size,atom_hits:hits(surfaceIds),item_hits:[...surfaceIds].filter(id=>[...hitAtoms].some(k=>k.startsWith(`${id}\0`))).length},clean:{items_total:cleanIds.size,items_with_finding:[...cleanIds].filter(id=>findingItems.has(id)).length}}}
export function selectWinner(runs){if(!Array.isArray(runs)||runs.length!==2)return null;for(const r of runs)for(const p of ['A','B','C','D'])if(!r[p]?.valid)throw Error(`INVALID_DISCOVERY_CELL:${p}`);const pass=p=>runs.every(r=>r[p].context_atom_hits-r.A.context_atom_hits>=3&&r[p].surface_atom_hits>=r.A.surface_atom_hits&&r[p].clean_findings<=r.A.clean_findings),fixed={D:0,C:1,B:2},ps=['B','C','D'].filter(pass);ps.sort((a,b)=>runs.reduce((n,r)=>n+(r[b].context_atom_hits-r.A.context_atom_hits)-(r[a].context_atom_hits-r.A.context_atom_hits),0)||runs.reduce((n,r)=>n+r[a].clean_findings-r[b].clean_findings,0)||fixed[a]-fixed[b]);return ps[0]??null}
export function assertDiscoveryComplete(cells){for(const run of[1,2])for(const protocol of['A','B','C','D'])for(const shard of[1,2]){const x=cells.find(c=>c.run===run&&c.protocol===protocol&&c.shard===shard&&c.cohort==='discovery');if(!x?.valid)throw Error(`INVALID_DISCOVERY_CELL:${protocol}:${run}:${shard}`)}return true}
