#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""并行批量 Pi 审核驱动：并发执行 tools/pi-review，失败自动重试，进度汇报。

用法：
  python3 -B tools/pi-review-batch.py --index <review-index.json> [--workers 4] [--limit N] [--skip M] [--retries 2]

- 并发 worker 数量由 --workers 控制（默认 4；provider 限速时降低）。
- 每个 bundle 单独调用 tools/pi-review（--timeout 1200 保持不变）。
- 非零退出或空响应自动重试 --retries 次（间隔递增）。
- 非 --force 时由 tools/pi-review 的精确缓存身份校验决定是否复用结果。
"""
from __future__ import annotations

import argparse
import json
import queue
import signal
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from i18nlib import TOOL_VERSION  # noqa: E402
from i18nlib.review import _review_index_id, review_descriptor_sort_key  # noqa: E402
from i18nlib.report import json_bytes  # noqa: E402
from i18nlib.translation_review import (  # noqa: E402
    translation_provider_message,
    translation_selection_sha256,
)

PI_REVIEW = ROOT / "tools" / "pi-review"
BATCH_TIMEOUT_SECONDS = 3600 * 4
REVIEW_INDEX_SCHEMA_VERSION = 2
REVIEW_INDEX_CONTRACT = "tome4-review-index-v2"


def load_index(path: Path) -> dict[str, object]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read review index {path}: {error}") from error
    if not isinstance(value, dict) or not isinstance(value.get("bundles"), list):
        raise ValueError("review index must be an object containing a bundles array")
    contract = value.get("review_contract")
    if contract not in (None, "tome4-review-v1", REVIEW_INDEX_CONTRACT):
        raise ValueError(f"unsupported review index contract: {contract!r}")
    for index, descriptor in enumerate(value["bundles"]):
        if not isinstance(descriptor, dict):
            raise ValueError(f"review index bundle {index} must be an object")
        if not all(
            isinstance(descriptor.get(field), str) and descriptor[field]
            for field in ("bundle_id", "path")
        ):
            raise ValueError(
                f"review index bundle {index} must contain bundle_id and path strings"
            )
    if contract == REVIEW_INDEX_CONTRACT:
        if type(value.get("schema_version")) is not int or value["schema_version"] != REVIEW_INDEX_SCHEMA_VERSION:
            raise ValueError("unsupported review index schema")
        for field in ("tool_version", "version", "manifest_sha256"):
            if not isinstance(value.get(field), str) or not value[field]:
                raise ValueError(f"review index has no valid {field}")
        if value["tool_version"] != TOOL_VERSION:
            raise ValueError("review index was generated by a different tool version")
        if (
            len(value["manifest_sha256"]) != 64
            or any(character not in "0123456789abcdef" for character in value["manifest_sha256"])
        ):
            raise ValueError("review index has no valid manifest_sha256")
        scope = value.get("scope")
        if (
            not isinstance(scope, dict)
            or set(scope) != {"translations", "code", "protected_sources"}
            or any(type(scope[field]) is not bool for field in scope)
            or scope["protected_sources"]
            or not (scope["translations"] or scope["code"])
        ):
            raise ValueError("review index has an invalid scope")
        redactions = value.get("redacted_absolute_path_count")
        if type(redactions) is not int or redactions < 0:
            raise ValueError("review index has an invalid redacted path count")
        baseline = value.get("baseline")
        baseline_tree = value.get("baseline_tree")
        if (baseline is None) != (baseline_tree is None) or (
            baseline is not None
            and (
                not isinstance(baseline, str)
                or not baseline
                or not isinstance(baseline_tree, str)
                or not baseline_tree
            )
        ):
            raise ValueError("review index baseline identity is incomplete")
        partitions: dict[tuple[str, str], list[dict[str, object]]] = {}
        seen_bundle_ids: set[str] = set()
        for index, descriptor in enumerate(value["bundles"]):
            required = {
                "bundle_id", "schema_version", "review_contract", "channel",
                "kind", "offset", "count", "total", "artifact_bytes",
                "payload_bytes", "path",
            }
            if descriptor.get("kind") == "translations":
                required.add("component")
                required.update(
                    {
                        "item_character_count",
                        "item_character_budget",
                        "oversized_single_item",
                        "selection_sha256",
                    }
                )
            missing = sorted(required - set(descriptor))
            if missing:
                raise ValueError(
                    f"review index bundle {index} is missing fields: {', '.join(missing)}"
                )
            if not all(isinstance(descriptor[field], str) and descriptor[field] for field in ("bundle_id", "review_contract", "channel", "kind", "path")):
                raise ValueError(f"review index bundle {index} has invalid identity fields")
            if descriptor["bundle_id"] in seen_bundle_ids:
                raise ValueError("review index repeats a bundle_id")
            seen_bundle_ids.add(descriptor["bundle_id"])
            if type(descriptor["schema_version"]) is not int:
                raise ValueError(f"review index bundle {index} has an invalid schema")
            for field in ("artifact_bytes", "payload_bytes"):
                if type(descriptor[field]) is not int or descriptor[field] < 1:
                    raise ValueError(
                        f"review index bundle {index} has invalid {field}"
                    )
            if any(
                type(descriptor[field]) is not int or descriptor[field] < 0
                for field in ("offset", "count", "total")
            ) or (
                descriptor["count"] < 1
                or descriptor["total"] < descriptor["count"]
                or descriptor["offset"] + descriptor["count"] > descriptor["total"]
            ):
                raise ValueError(f"review index bundle {index} has invalid selection counts")
            bundle_path = Path(descriptor["path"])
            try:
                bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
            except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
                raise ValueError(
                    f"cannot read review index bundle {index}: {bundle_path}: {error}"
                ) from error
            if not isinstance(bundle, dict) or any(
                bundle.get(field) != descriptor.get(field)
                for field in ("bundle_id", "schema_version", "review_contract", "kind")
            ):
                raise ValueError(
                    f"review index bundle {index} descriptor does not match its artifact"
                )
            if any(
                bundle.get(field) != value.get(field)
                for field in ("tool_version", "version", "manifest_sha256")
            ):
                raise ValueError(
                    f"review index bundle {index} provenance does not match its index"
                )
            selection = bundle.get("selection")
            if not isinstance(selection, dict) or any(
                selection.get(field) != descriptor[field]
                for field in ("offset", "count", "total")
            ):
                raise ValueError(
                    f"review index bundle {index} selection does not match its artifact"
                )
            expected_channel = (
                "semantic-observation"
                if descriptor["kind"] == "translations"
                and descriptor["review_contract"] == "tome4-translation-review-bundle-v2"
                else "code-findings"
                if descriptor["kind"] == "code"
                and descriptor["review_contract"] == "tome4-review-v1"
                else None
            )
            if descriptor["channel"] != expected_channel:
                raise ValueError(
                    f"review index bundle {index} has an unsupported contract/channel pair"
                )
            if not scope[descriptor["kind"]]:
                raise ValueError(
                    f"review index bundle {index} is outside the declared scope"
                )
            if bundle_path.stat().st_size != descriptor["artifact_bytes"]:
                raise ValueError(
                    f"review index bundle {index} artifact size does not match"
                )
            try:
                provider_payload_bytes = (
                    len(translation_provider_message(bundle))
                    if descriptor["kind"] == "translations"
                    else len(json_bytes(bundle))
                )
            except (KeyError, TypeError, ValueError) as error:
                raise ValueError(
                    f"review index bundle {index} cannot form a provider payload"
                ) from error
            if provider_payload_bytes != descriptor["payload_bytes"]:
                raise ValueError(
                    f"review index bundle {index} provider payload size does not match"
                )
            if descriptor["kind"] == "translations":
                if (
                    bundle.get("channel") != descriptor["channel"]
                    or bundle.get("component") != descriptor["component"]
                    or bundle.get("selection_sha256")
                    != descriptor["selection_sha256"]
                ):
                    raise ValueError(
                        f"review index bundle {index} translation identity does not "
                        "match its artifact"
                    )
                for field in (
                    "item_character_count",
                    "item_character_budget",
                ):
                    if type(descriptor[field]) is not int or descriptor[field] < 1:
                        raise ValueError(
                            f"review index bundle {index} has invalid {field}"
                        )
                if type(descriptor["oversized_single_item"]) is not bool:
                    raise ValueError(
                        f"review index bundle {index} has invalid oversized marker"
                    )
                if any(
                    selection.get(field) != descriptor[field]
                    for field in (
                        "item_character_count",
                        "item_character_budget",
                        "oversized_single_item",
                    )
                ):
                    raise ValueError(
                        f"review index bundle {index} translation selection does not "
                        "match its artifact"
                    )
            component = descriptor.get("component", "")
            if not isinstance(component, str):
                raise ValueError(f"review index bundle {index} has an invalid component")
            partitions.setdefault(
                (str(descriptor["kind"]), component), []
            ).append(descriptor)
        for (kind, component), descriptors in partitions.items():
            ordered = sorted(descriptors, key=lambda item: int(item["offset"]))
            expected_offset = 0
            expected_total = ordered[0]["total"]
            selected_items: list[dict[str, object]] = []
            selection_sha256 = ordered[0].get("selection_sha256")
            for descriptor in ordered:
                if (
                    descriptor["total"] != expected_total
                    or descriptor["offset"] != expected_offset
                ):
                    label = f"{kind}/{component}" if component else kind
                    raise ValueError(
                        f"review index partition {label} has a gap, overlap, or total mismatch"
                    )
                expected_offset += int(descriptor["count"])
                if kind == "translations":
                    if descriptor.get("selection_sha256") != selection_sha256:
                        raise ValueError(
                            f"review index partition {kind}/{component} has mixed selection identities"
                        )
                    bundle_path = Path(str(descriptor["path"]))
                    try:
                        bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
                        items = bundle["items"]
                    except (
                        OSError,
                        UnicodeDecodeError,
                        json.JSONDecodeError,
                        KeyError,
                        TypeError,
                    ) as error:
                        raise ValueError(
                            f"cannot read translation partition artifact {bundle_path}: {error}"
                        ) from error
                    if not isinstance(items, list) or len(items) != descriptor["count"]:
                        raise ValueError(
                            f"review index partition {kind}/{component} item count is invalid"
                        )
                    selected_items.extend(items)
            if expected_offset != expected_total:
                label = f"{kind}/{component}" if component else kind
                raise ValueError(f"review index partition {label} is incomplete")
            if kind == "translations":
                previous_ordinal = -1
                revision_ids: set[str] = set()
                for item in selected_items:
                    if not isinstance(item, dict):
                        raise ValueError(
                            f"review index partition {kind}/{component} has an invalid item"
                        )
                    ordinal = item.get("ordinal")
                    revision_id = item.get("revision_id")
                    if (
                        type(ordinal) is not int
                        or ordinal <= previous_ordinal
                        or not isinstance(revision_id, str)
                        or not revision_id
                        or revision_id in revision_ids
                    ):
                        raise ValueError(
                            f"review index partition {kind}/{component} repeats or reorders a canonical revision"
                        )
                    previous_ordinal = ordinal
                    revision_ids.add(revision_id)
                try:
                    expected_selection = translation_selection_sha256(selected_items)
                except (TypeError, ValueError) as error:
                    raise ValueError(
                        f"review index partition {kind}/{component} selection is invalid"
                    ) from error
                if expected_selection != selection_sha256:
                    raise ValueError(
                        f"review index partition {kind}/{component} selection digest does not match"
                    )
        review_id = value.get("review_id")
        if (
            not isinstance(review_id, str)
            or len(review_id) != 64
            or any(character not in "0123456789abcdef" for character in review_id)
        ):
            raise ValueError("review index has no valid review_id")
        identity = dict(value)
        identity.pop("review_id")
        if review_id != _review_index_id(identity):
            raise ValueError("review index identity is stale or invalid")
    return value


class Progress:
    def __init__(self, total: int) -> None:
        self.total = total
        self.done = 0
        self.ok = 0
        self.failed = 0
        self._lock = queue.SimpleQueue()

    def tick(self, ok: bool) -> None:
        self._lock.put(ok)

    def pump(self) -> None:
        while not self._lock.empty():
            ok = self._lock.get()
            self.done += 1
            if ok:
                self.ok += 1
            else:
                self.failed += 1


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be at least 1")
    return parsed


def non_negative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be non-negative")
    return parsed


def run_one(
    bundle_id: str,
    bundle_path: str,
    retries: int,
    progress: Progress,
    force: bool = False,
) -> tuple[str, bool]:
    delay = 10
    cmd = [
        str(PI_REVIEW),
        "--bundle",
        bundle_path,
        "--expected-bundle-id",
        bundle_id,
    ]
    if force:
        cmd.append("--force")
    for attempt in range(retries + 1):
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=1250,
            )
            stdout = result.stdout or ""
            if result.returncode == 0 and stdout.strip():
                progress.tick(True)
                return bundle_id, True
            empty_response = result.returncode == 0
            if empty_response:
                stderr = (result.stderr or "").strip()
                err = "empty response"
                if stderr:
                    err = f"{err}; stderr: {stderr}"
            else:
                err = (result.stderr or stdout).strip()
            if attempt < retries:
                print(
                    f"  retry {bundle_id[:12]} "
                    f"(attempt {attempt + 1}): {err[:80]}"
                )
                time.sleep(delay)
                delay *= 2
            elif empty_response:
                print(
                    f"  failed {bundle_id[:12]} "
                    f"(attempt {attempt + 1}): {err[:80]}"
                )
        except subprocess.TimeoutExpired:
            print(f"  timeout {bundle_id[:12]} (attempt {attempt + 1})")
            if attempt < retries:
                time.sleep(delay)
                delay *= 2
        except OSError as exc:
            print(f"  error {bundle_id[:12]}: {exc}")
            break
    progress.tick(False)
    return bundle_id, False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--index", required=True, type=Path)
    parser.add_argument("--workers", type=positive_int, default=4)
    parser.add_argument("--limit", type=non_negative_int, default=None)
    parser.add_argument("--skip", type=non_negative_int, default=0)
    parser.add_argument("--retries", type=non_negative_int, default=2)
    parser.add_argument(
        "--force",
        action="store_true",
        help="bypass cache and force fresh Pi review for every bundle",
    )
    signal.alarm(BATCH_TIMEOUT_SECONDS)
    try:
        try:
            return run_batch(parser.parse_args(argv))
        except (OSError, ValueError) as error:
            print(f"error: {error}", file=sys.stderr)
            return 2
    finally:
        signal.alarm(0)


def run_batch(args: argparse.Namespace) -> int:
    index = load_index(args.index)
    bundles = [b for b in index["bundles"] if b.get("path")]
    if index.get("review_contract") == REVIEW_INDEX_CONTRACT:
        bundles.sort(key=review_descriptor_sort_key)
    bundles = bundles[args.skip:]
    if args.limit is not None:
        bundles = bundles[: args.limit]
    total = len(bundles)
    if total == 0:
        print("no bundles to review")
        return 0

    contracts: dict[str, int] = {}
    for bundle in bundles:
        contract = str(bundle.get("review_contract", "legacy-unspecified"))
        contracts[contract] = contracts.get(contract, 0) + 1
    print(
        f"batch: {total} bundles, workers={args.workers}, retries={args.retries}, "
        f"contracts={json.dumps(contracts, ensure_ascii=False, sort_keys=True)}"
    )
    progress = Progress(total)
    results: list[tuple[str, bool]] = []
    started = time.time()
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {
            pool.submit(
                run_one,
                b["bundle_id"],
                b["path"],
                args.retries,
                progress,
                args.force,
            ): b["bundle_id"]
            for b in bundles
        }
        for future in as_completed(futures):
            bundle_id, ok = future.result()
            results.append((bundle_id, ok))
            progress.pump()
            elapsed = time.time() - started
            rate = progress.done / elapsed if elapsed > 0 else 0
            print(
                f"[{progress.done}/{total}] ok={progress.ok} fail={progress.failed} "
                f"rate={rate:.2f}/s ({bundle_id[:12]} {'OK' if ok else 'FAIL'})"
            )

    failed = [bid for bid, ok in results if not ok]
    print(f"\n完成: {progress.done}/{total}，成功 {progress.ok}，失败 {len(failed)}")
    for bid in failed:
        print(f"  FAILED: {bid}")
    summary = {
        "index": str(args.index),
        "total": total,
        "ok": progress.ok,
        "failed": failed,
        "contracts": contracts,
    }
    out = ROOT / ".artifacts" / "i18n" / "pi-batch-summary.json"
    out.write_text(json.dumps(summary, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"summary: {out}")
    return 0 if not failed else 1


if __name__ == "__main__":
    raise SystemExit(main())
