#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseNoDuplicate,readCanonical,jsonBytes,sha256,shaFile,walk,treeBinding,predecessorExecutionV4,agyBinary,verifyAgyExecutable} from '../lib.mjs';
import {checkManifest,buildManifest,manifestSha256,sourcePaths,GENERATED_PREFIXES,TASK_ID,EXPERIMENT_ID} from '../build-manifest.mjs';
import {verifyPredecessorBindings,replay} from '../build-frozen-base.mjs';
import {checkFreeze,freeze,buildFromRoot,freezeState} from '../freezer.mjs';
import {jsonIntegrity,leakageScan,preflight} from '../preflight.mjs';
import {extractAgy} from '../parser.mjs';
import {validateReference,scoreCell} from '../scorer.mjs';
import {deriveState,appendRow,startRow,finishRow,readRows,executionEmpty,nextAttempt,LEDGER_PATH,MAX_ATTEMPTS,QUALIFICATION_CELLS,PILOT_AGY_PROCESS_CEILING} from '../ledger.mjs';
import {TASK_DIR,gatePaths,validateGates,GATE_ORDER} from '../gates.mjs';
import * as qualificationModule from '../qualification.mjs';
import {captureQualification,finalizeQualification,validateQualification,CAPTURE_RECEIPT_PATH,files as qfiles,syntheticItems,parseModels,argvModel,ROUTE_MODEL} from '../qualification.mjs';
import {runCell,requestInput,plan,requestEntry} from '../runner.mjs';
import {parseArgv,resultExitCode,FAILURE_EXIT_CODE} from '../run.mjs';
import {postRun} from '../post-run.mjs';

const here=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),realRepo=path.resolve(here,'../../../..');
const pkgRel='evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v5';
const predecessorRoots=['evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5','evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v1','evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v2','evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v3','evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v4'];
const terminalGate='.ai/task/research-gemini-context-counterexample-reviewer-v5/ROUND-0003-TERMINALIZATION-REVIEW-GATE-001.json';
const authorized=['discovery-A-run-1-shard-1','discovery-C-run-1-shard-1'];
const dynamic=['execution','qualification','PILOT.md','PILOT-RESULT.json','SCORES.json','GATES.json','ROUTE-RELOCATION-CONTRACT.json'];
const forbiddenNames=['REUSE-CONTRACT.json','SYNTHETIC-REUSE-CONTRACT.json','ROUTE-RELOCATION-CONTRACT.json'];
const roots=[];const tmp=()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'v5x5-'));roots.push(d);return d};
function cleanupRoots(){for(const d of roots.splice(0))fs.rmSync(d,{recursive:true,force:true})}
process.once('exit',cleanupRoots);
for(const [signal,code] of [['SIGINT',2],['SIGTERM',15]])process.once(signal,()=>{cleanupRoots();process.exit(128+code)});
const write=(p,x)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,Buffer.isBuffer(x)?x:jsonBytes(x))};
const fixture=readCanonical(path.join(here,'tests/fixtures/valid-envelope.json'));
const gateSchema=g=>`gemini-context-v5-execution-v5-gate-${g.toLowerCase()}-v1`;
const checklist=Array.from({length:10},(_,i)=>`W${String(i+1).padStart(2,'0')}`);
function baseRepo(){const repo=tmp(),root=path.join(repo,pkgRel);for(const rel of sourcePaths(here).filter(x=>!x.startsWith('frozen/'))){const s=path.join(here,rel),d=path.join(root,rel);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(s,d)}for(const rel of predecessorRoots)fs.cpSync(path.join(realRepo,rel),path.join(repo,rel),{recursive:true});fs.cpSync(path.join(realRepo,terminalGate),path.join(repo,terminalGate));const r=replay(repo);write(path.join(root,'frozen/BASES.json'),r.base);write(path.join(root,'frozen/PREDECESSOR-BINDINGS.json'),r.bindings);write(path.join(root,'MANIFEST.json'),buildManifest(root));return{repo,root}}
function agyStdout(items,response='single'){const structured_output={items};return jsonBytes({...fixture,structured_output,response:response==='single'?null:JSON.stringify({items,metadata:'ok'})})}
function qualificationInvoke(counter,{syntheticExit=0}={}){return({argv})=>{counter.n++;counter.argvs.push(argv);if(argv[0]==='models')return{exit_code:0,stdout:Buffer.from('gemini-3.7-flash-high\tGemini Flash High\nother\tOther\n'),stderr:Buffer.alloc(0)};return{exit_code:syntheticExit,stdout:agyStdout(syntheticItems().map(x=>({item_id:x.item_id,candidates:[]})),'dual'),stderr:Buffer.alloc(0)}}}
function cellInvoke(counter){return p=>{counter.n++;const items=requestInput(p.request).items.map(x=>({item_id:x.item_id,candidates:[]}));return{exit_code:0,stdout:agyStdout(items),stderr:Buffer.alloc(0)}}}
function reviewed(){const f=baseRepo();freeze(f.root);const m=manifestSha256(f.root);write(path.join(f.repo,gatePaths.PACKAGE_REVIEW),{schema_version:gateSchema('PACKAGE_REVIEW'),task_id:TASK_ID,gate:'PACKAGE_REVIEW',status:'SATISFIED_CHECKLIST_W01_W10_PASS',manifest_sha256:m,checklist_items_passed:checklist});return{...f,manifest_sha256:m}}
function qualify(){const f=reviewed(),counter={n:0,argvs:[]};captureQualification(f.root,{repoRoot:f.repo,invoke:qualificationInvoke(counter)});write(path.join(f.repo,CAPTURE_RECEIPT_PATH),{schema_version:'gemini-context-v5-execution-v5-qualification-capture-receipt-v1',task_id:TASK_ID,purpose:'route_qualification_capture',dispatch_id:'d',agent_id:'a',archive_confirmed:true,manifest_sha256:f.manifest_sha256,draft_sha256:shaFile(path.join(f.root,qfiles.draft))});finalizeQualification(f.root,{repoRoot:f.repo});return{...f,counter}}
function authorize(f,{budget=4,inferences=3}={}){write(path.join(f.repo,gatePaths.QUALIFICATION),{schema_version:gateSchema('QUALIFICATION'),task_id:TASK_ID,gate:'QUALIFICATION',status:'SATISFIED_NON_SCORED_ROUTE_QUALIFICATION',manifest_sha256:f.manifest_sha256,predecessor_gate:{path:gatePaths.PACKAGE_REVIEW,sha256:shaFile(path.join(f.repo,gatePaths.PACKAGE_REVIEW))},qualification_evidence:{path:`${pkgRel}/${qfiles.evidence}`,sha256:shaFile(path.join(f.root,qfiles.evidence))},reported_model:null});write(path.join(f.repo,gatePaths.EXECUTION_AUTHORIZATION),{schema_version:gateSchema('EXECUTION_AUTHORIZATION'),task_id:TASK_ID,gate:'EXECUTION_AUTHORIZATION',status:'AUTHORIZED_EXACT_CELLS_AND_ROUTE',manifest_sha256:f.manifest_sha256,predecessor_gate:{path:gatePaths.QUALIFICATION,sha256:shaFile(path.join(f.repo,gatePaths.QUALIFICATION))},authorized_cells:authorized,agy_process_budget:budget,inference_call_budget:inferences,request_manifest_sha256:shaFile(path.join(f.root,'frozen/REQUEST-MANIFEST.json')),route_contract_sha256:shaFile(path.join(f.root,'ROUTE-CONTRACT.json'))})}
let n=0;async function test(name,fn){try{await fn();console.log(`ok ${++n} - ${name}`)}catch(e){console.error(`not ok ${n+1} - ${name}\n${e.stack}`);process.exitCode=1}finally{cleanupRoots()}}

await test('W01 v4 canonical tree and all bound predecessors are immutable',()=>{assert.deepEqual(treeBinding(realRepo,predecessorExecutionV4.root),predecessorExecutionV4);assert.deepEqual(verifyPredecessorBindings(here,realRepo),[]);assert.equal(predecessorExecutionV4.tree_sha256,'40240912722cebed3f1a3319c73ec5a6ba48d9c9a9508262042e64da3865f323')});
await test('W02 candidate has no dynamic, result, gate, reuse, or relocation artifacts',()=>{for(const rel of dynamic)assert.equal(fs.existsSync(path.join(here,rel)),false,rel);for(const rel of walk(here))for(const name of forbiddenNames)assert.notEqual(path.basename(rel),name);for(const rel of sourcePaths(here).filter(x=>x.endsWith('.mjs')&&!x.startsWith('tests/')))assert.doesNotMatch(fs.readFileSync(path.join(here,rel),'utf8'),/reuse|relocat/iu,rel)});
await test('W03 ids are v5 and manifest rebuilds byte-identically',()=>{assert.equal(TASK_ID,'research-gemini-context-counterexample-reviewer-v5-execution-v5');assert.equal(EXPERIMENT_ID,'gemini-context-counterexample-reviewer-v5-execution-v5');assert.deepEqual(checkManifest(here),[]);assert.ok(jsonBytes(buildManifest(here)).equals(fs.readFileSync(path.join(here,'MANIFEST.json'))));assert.equal(walk(here).filter(x=>x.includes('execution-v4')).length,0)});
await test('W04 pinned regular executable is hash-bound and updater path is absent',()=>{const r=readCanonical(path.join(here,'ROUTE-CONTRACT.json'));assert.deepEqual(verifyAgyExecutable(r),agyBinary);assert.equal(r.cli_contract.executable,agyBinary.path);assert.notEqual(r.cli_contract.executable,'/home/yun/.local/bin/agy');for(const rel of ['qualification.mjs','runner.mjs','run.mjs'])assert.ok(!fs.readFileSync(path.join(here,rel)).includes('/home/yun/.local/bin/agy'),rel)});
await test('W04 hash check occurs before qualification ledger START',()=>{const f=reviewed(),saved=agyBinary.sha256,c={n:0,argvs:[]};try{agyBinary.sha256='0'.repeat(64);assert.throws(()=>captureQualification(f.root,{repoRoot:f.repo,invoke:qualificationInvoke(c)}),/STOP_ROUTE_EXECUTABLE/);assert.equal(c.n,0);assert.equal(readRows(f.root).rows.length,0)}finally{agyBinary.sha256=saved}});
await test('W04 runner hash check also occurs before ledger START and invoke',()=>{const f=qualify();authorize(f);const saved=agyBinary.sha256,c={n:0};try{agyBinary.sha256='0'.repeat(64);const before=readRows(f.root).rows.length;assert.throws(()=>runCell(authorized[0],{root:f.root,repoRoot:f.repo,invoke:cellInvoke(c)}),/STOP_ROUTE_EXECUTABLE/);assert.equal(c.n,0);assert.equal(readRows(f.root).rows.length,before)}finally{agyBinary.sha256=saved}});
await test('W05 strict TSV accepts only exact two-field target once',()=>{assert.equal(parseModels(Buffer.from(' gemini-3.7-flash-high \t Name \r\nother\tOther\n'),'gemini-3.7-flash-high').model_count,2);for(const x of ['', 'gemini-3.7-flash-high\n','gemini-3.7-flash-high\t\n','gemini-3.7-flash-high\tX\tY\n'])assert.throws(()=>parseModels(Buffer.from(x),'gemini-3.7-flash-high'),/MODEL_LIST_TSV/);for(const x of ['other\tX\n','gemini-3.7-flash-high\tX\ngemini-3.7-flash-high\tY\n','xgemini-3.7-flash-high\tX\n'])assert.throws(()=>parseModels(Buffer.from(x),'gemini-3.7-flash-high'),/MODEL_LIST_EXACT_ROUTE/)});
await test('W05 dual channel equality is required while either single channel works',()=>{const items=fixture.structured_output.items;assert.equal(extractAgy(jsonBytes({...fixture,structured_output:{items},response:JSON.stringify({items})})).output.items.length,16);assert.equal(extractAgy(jsonBytes({...fixture,structured_output:null,response:JSON.stringify({items})})).output.items.length,16);assert.throws(()=>extractAgy(jsonBytes({...fixture,structured_output:'bad',response:null})),/AGY_STRUCTURED_TYPE/);assert.throws(()=>extractAgy(jsonBytes({...fixture,structured_output:{},response:null})),/AGY_STRUCTURED_ITEMS/);assert.throws(()=>extractAgy(jsonBytes({...fixture,structured_output:null,response:null})),/AGY_CHANNEL_CARDINALITY/);assert.throws(()=>extractAgy(jsonBytes({...fixture,structured_output:{items},response:'bad'})),/AGY_RESPONSE/);assert.throws(()=>extractAgy(jsonBytes({...fixture,structured_output:{items},response:JSON.stringify({items:items.slice(1)})})),/AGY_CHANNEL_ITEMS_MISMATCH/)});
await test('W06 one attempt, four processes and three inferences are hard ceilings',()=>{assert.equal(MAX_ATTEMPTS,1);assert.equal(PILOT_AGY_PROCESS_CEILING,4);const d=tmp(),s=startRow(authorized[0],1,'2026-01-01T00:00:00.000Z');appendRow(d,s);appendRow(d,finishRow(s,{exit:1,stdout_sha256:'0'.repeat(64),stderr_sha256:'1'.repeat(64),finished_at:'2026-01-01T00:00:01.000Z'}));assert.equal(nextAttempt(deriveState(d),authorized[0]).attempt,null)});
await test('W06 exact authorization budget is 4 processes / 3 inferences',()=>{const f=qualify();authorize(f,{budget:3,inferences:2});assert.ok(validateGates(f.root,{repoRoot:f.repo}).errors.includes('EXECUTION_AUTHORIZATION:BUDGET'))});
await test('W06 production CLI failure is nonzero and C is blocked before A',()=>{assert.equal(FAILURE_EXIT_CODE,4);assert.equal(resultExitCode({success:false,parse_valid:true}),4);assert.equal(resultExitCode({success:true,parse_valid:false}),4);assert.deepEqual(parseArgv(['--cell',authorized[0]]),{ok:true,cell:authorized[0]});const f=qualify();authorize(f);const c={n:0};assert.throws(()=>runCell(authorized[1],{root:f.root,repoRoot:f.repo,invoke:cellInvoke(c)}),/A_BEFORE_C_REQUIRED/);assert.equal(c.n,0)});
await test('W07 freezer has 32 requests, 35 targets, 7 appends and no leakage',()=>{const r=checkFreeze(here);assert.deepEqual(r.errors,[]);assert.equal(r.built.requests.length,32);assert.equal(r.freeze_state.targets,35);assert.ok([0,35].includes(r.freeze_state.present));assert.equal(r.built.manifest.exact_source_appended_count,7);assert.deepEqual(leakageScan(r.built),[]);assert.equal(new Set(r.built.requests.map(x=>x.cell)).size,32)});
await test('W07 scorer semantics retain one-way span containment',()=>{const d=readCanonical(path.join(here,'tests/fixtures/scorer-case.json'));assert.deepEqual(validateReference(d.reference),[]);assert.deepEqual(scoreCell(d.raw_items,d.reference.items),d.expected)});
await test('W08 exactly three ordered task-owned gates exist in code',()=>{assert.deepEqual(GATE_ORDER,['PACKAGE_REVIEW','QUALIFICATION','EXECUTION_AUTHORIZATION']);assert.equal(Object.keys(gatePaths).length,3);for(const p of Object.values(gatePaths))assert.ok(p.startsWith(`${TASK_DIR}/`))});
await test('W08 qualification runs fresh exactly once per cell and uses exact models argv',()=>{const f=reviewed(),c={n:0,argvs:[]};const out=captureQualification(f.root,{repoRoot:f.repo,invoke:qualificationInvoke(c)});assert.equal(c.n,2);assert.deepEqual(c.argvs[0],['models']);assert.equal(out.agy_processes_spawned,2);assert.equal(out.inference_calls_made,1);assert.deepEqual(readRows(f.root).rows.map(x=>x.cell),[QUALIFICATION_CELLS[0],QUALIFICATION_CELLS[0],QUALIFICATION_CELLS[1],QUALIFICATION_CELLS[1]]);assert.throws(()=>captureQualification(f.root,{repoRoot:f.repo,invoke:qualificationInvoke(c)}),/QUALIFICATION_NOT_FRESH/);assert.equal(c.n,2)});
await test('W08 archived receipt is mandatory and finalization is pure',()=>{const f=reviewed(),c={n:0,argvs:[]};captureQualification(f.root,{repoRoot:f.repo,invoke:qualificationInvoke(c)});assert.throws(()=>finalizeQualification(f.root,{repoRoot:f.repo}),/CAPTURE_RECEIPT_ABSENT/);const before=c.n;write(path.join(f.repo,CAPTURE_RECEIPT_PATH),{schema_version:'gemini-context-v5-execution-v5-qualification-capture-receipt-v1',task_id:TASK_ID,purpose:'route_qualification_capture',dispatch_id:'d',agent_id:'a',archive_confirmed:true,manifest_sha256:f.manifest_sha256,draft_sha256:shaFile(path.join(f.root,qfiles.draft))});assert.equal(finalizeQualification(f.root,{repoRoot:f.repo}).valid,true);assert.equal(c.n,before)});
await test('W08 package production code has no task write sink',()=>{for(const rel of sourcePaths(here).filter(x=>x.endsWith('.mjs')&&!x.startsWith('tests/'))){const src=fs.readFileSync(path.join(here,rel),'utf8');for(const m of src.matchAll(/(?:writeFileSync|appendFileSync|writeExclusive|writeStable|renameSync|rmSync|cpSync)\(([^;\n]*)/gu))for(const token of ['TASK_DIR','CAPTURE_RECEIPT_PATH','gatePaths','.ai/task'])assert.ok(!m[1].includes(token),`${rel}: ${m[0]}`)}});
await test('W09 preflight is NO_RUN with zero process/inference/network counts',()=>{const r=preflight(here,{repoRoot:realRepo});assert.deepEqual(r.integrity_errors,[]);assert.equal(r.execution_state,'NO_RUN');assert.equal(r.decision,'NO_GO_REQUIRED_GATES');assert.equal(r.agy_processes_spawned,0);assert.equal(r.inference_calls_made,0);assert.equal(r.network_calls_made,0)});
await test('W09 mock pilot ends at exactly 4 processes / 3 inferences with A then C',()=>{const f=qualify();authorize(f);const c={n:0};for(const cell of authorized){const r=runCell(cell,{root:f.root,repoRoot:f.repo,invoke:cellInvoke(c)});assert.equal(r.success,true,r.parse_errors?.join(','))}assert.equal(c.n,2);const s=deriveState(f.root);assert.equal(s.agy_processes_spawned,4);assert.equal(s.inference_calls_made,3);assert.equal(postRun(f.root,{repoRoot:f.repo}).decision,'PILOT_COMPLETE')});
await test('W09 generated prefixes cover all dynamic outputs',()=>{for(const p of ['execution/','qualification/','model-facing/requests/','sealed/REFERENCE.json','PILOT-RESULT.json','PILOT.md','SCORES.json'])assert.ok(GENERATED_PREFIXES.includes(p),p)});
await test('W10 README distinguishes v3/v4 failures, v5 validation and no effectiveness claim',()=>{const t=fs.readFileSync(path.join(here,'README.md'),'utf8');for(const x of ['execution-v3','execution-v4','execution-v5','不是模型效果结果','不能据此声称'])assert.ok(t.includes(x),x)});
await test('all JSON is canonical and no STATE.json exists in package',()=>{assert.deepEqual(jsonIntegrity(here),[]);assert.ok(!walk(here).some(x=>path.basename(x)==='STATE.json'));assert.throws(()=>parseNoDuplicate('{"a":1,"a":2}'),/DUPLICATE_KEY/)});
await test('freeze rebuild is deterministic and complete after a missing target',()=>{const f=baseRepo();assert.equal(checkFreeze(f.root).freeze_state.present,0);freeze(f.root);const a=checkFreeze(f.root);assert.deepEqual(a.errors,[]);const victim=a.built.requests[0].path;fs.rmSync(path.join(f.root,victim));assert.equal(freezeState(f.root,buildFromRoot(f.root)).partial,true);freeze(f.root);assert.deepEqual(checkFreeze(f.root).errors,[])});
await test('route plans preserve env values outside argv',()=>{const r=readCanonical(path.join(here,'ROUTE-CONTRACT.json')),f=baseRepo(),saved=process.env.GEMINI_API_KEY;freeze(f.root);try{process.env.GEMINI_API_KEY='v5x5-secret-sentinel';const p=plan(f.root,requestEntry(f.root,authorized[0]));assert.equal(argvModel(p.argv),ROUTE_MODEL);assert.equal(p.env.GEMINI_API_KEY,'v5x5-secret-sentinel');assert.ok(!p.argv.some(x=>String(x).includes('v5x5-secret-sentinel')));assert.ok(!p.request.includes('v5x5-secret-sentinel'));assert.equal(r.cli_contract.timeout_ms,1620000)}finally{if(saved===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=saved}});

cleanupRoots();
const leftovers=fs.readdirSync(os.tmpdir()).filter(x=>x.startsWith('v5x5-'));if(leftovers.length){console.error(`not ok ${n+1} - W09 temp cleanup: ${leftovers.join(',')}`);process.exitCode=1}else console.log(`ok ${++n} - W09 all /tmp/v5x5-* fixtures cleaned`);
if(process.exitCode)process.exit(process.exitCode);console.log(`1..${n}`);
