#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {evaluateContextInputReviewGate, evaluateContextResultsReviewGate, evaluateSidecarReviewGate, replay} from './replay.mjs';
import {evaluateReleaseImplementationReviewGate, jsonBytes, readReleaseProvenanceReviewGate, sha256, validateReleaseReviewGate} from './round-lineage.mjs';
import {ROUND2_AUTHORIZATION_PATH, ROUND2_CANDIDATE_MANIFEST_PATH, ROUND2_GATE_TRANSITION_PATHS, ROUND2_REPAIR_REVIEW_PATHS, ROUND2_REVIEWED_CANDIDATE, validateRound2CandidateManifest} from './round-0002-surface-input.mjs';
import {ROUND2_SURFACE_CALL, validateRound2SurfaceArtifacts} from './round-0002-surface-results.mjs';
import {evaluateRound2ContextReviewLifecycle, validateRound2ContextCandidate, validateRound2ContextInput} from './round-0002-context-input.mjs';
import {validateRound2ContextArtifacts,validateRound2ReviewedContextCandidate} from './round-0002-context-results.mjs';
import {ROUND2_RELEASE_PATHS, evaluateRound2ReleaseReviewGate, validateRound2CompletedReleaseEvidence, validateRound2PendingRelease} from './round-0002-release.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const RELEASE_AUTHORIZATION_PATH = '.ai/task/research-gemini-context-counterexample-reviewer-v5/ROUND-0001-REPLACEMENT-RELEASE-AUTHORIZATION-001.json';
const RELEASE_AUTHORIZATION_SHA256 = '87fca3852d57241fa9756cc8ac8269fd27bb4598ee780204bf9cbb15b7410d37';
const RELEASE_REVIEW_PATHS = ['.ai/task/research-gemini-context-counterexample-reviewer-v5/ROUND-0001-RELEASE-NORMAL-REVIEW-001.json', '.ai/task/research-gemini-context-counterexample-reviewer-v5/ROUND-0001-RELEASE-SENIOR-REVIEW-001.json', '.ai/task/research-gemini-context-counterexample-reviewer-v5/ROUND-0001-RELEASE-REVIEW-GATE-001.json'];
const ROUND2_REPAIR_REVIEW_SHA256 = Object.freeze({normal:'b82805696cfdeb9a6f2ded1e0fbe726e6a1a476091e8147624628daeaf6bfab3',senior:'8ebbe132a7f5bc27c7b3a2cc0e78a1381d6d35f83cfc56f09210743771593d20'});
const ROUND2_REPAIR_REVIEWERS = Object.freeze({normal:'49850012-7f63-4a83-8db6-985d384ca404',senior:'471fcff8-d683-4509-b77e-f24ad837b67d'});
const ROUND2_RELEASE_TASK_ROOT = '.ai/task/research-gemini-context-counterexample-reviewer-v5';

function validateUnexpectedRound2ReleaseReviews(repo) {
  const taskDir = path.join(repo, ROUND2_RELEASE_TASK_ROOT);
  const canonical = new Set([path.basename(ROUND2_RELEASE_PATHS.normal), path.basename(ROUND2_RELEASE_PATHS.senior), path.basename(ROUND2_RELEASE_PATHS.gate)]);
  const unexpected = fs.readdirSync(taskDir).filter(name =>
    /^(?:ROUND-0002-RELEASE-(?:NORMAL|SENIOR)-REVIEW|ROUND-0002-RELEASE-REVIEW-GATE)(?:-(?:\d+|RAW)|\.json$)/u.test(name) && !canonical.has(name)
  );
  if (unexpected.length) throw Error(`ROUND2_RELEASE_UNEXPECTED_REVIEW_ARTIFACT:${unexpected.join(',')}`);
}

function canonicalRecord(repo, relative, label) {
  const file=path.join(repo,relative),stat=fs.lstatSync(file); if(stat.isSymbolicLink()||!stat.isFile())throw Error(`${label}_FILE_TYPE`);
  const bytes=fs.readFileSync(file); let parsed; try{parsed=JSON.parse(bytes);}catch{throw Error(`${label}_JSON`);} if(!bytes.equals(jsonBytes(parsed)))throw Error(`${label}_NONCANONICAL_BYTES`); return {bytes,parsed};
}

export function validateRound2RepairReviewGate(repo, queue, candidate, {verifyTransitionFiles=true}={}) {
  const reviewKeys=['schema_version','review_id','status','role','reviewer_agent_id','reviewed_candidate_ref','reviewed_candidate_manifest_path','reviewed_candidate_manifest_sha256','reviewed_file_count','surface_queue_sha256','surface_queue_view_sha256','resolved_findings','findings','permitted_next_action','repository_modified_by_review','auditor_call_made'];
  const reviews={};
  for(const kind of ['normal','senior']){
    const record=canonicalRecord(repo,ROUND2_REPAIR_REVIEW_PATHS[kind],`ROUND2_REPAIR_${kind.toUpperCase()}_REVIEW`),role=kind==='normal'?'NORMAL_REVIEWER':'SENIOR_REVIEWER';
    if(sha256(record.bytes)!==ROUND2_REPAIR_REVIEW_SHA256[kind]||JSON.stringify(Object.keys(record.parsed).sort())!==JSON.stringify([...reviewKeys].sort())||record.parsed.schema_version!=='gemini-context-v5-round-0002-surface-input-repair-rereview-v1'||record.parsed.status!=='PASS'||record.parsed.role!==role||record.parsed.reviewer_agent_id!==ROUND2_REPAIR_REVIEWERS[kind]||record.parsed.reviewed_candidate_ref!==ROUND2_REVIEWED_CANDIDATE.candidate_ref||record.parsed.reviewed_candidate_manifest_path!==candidate.path||record.parsed.reviewed_candidate_manifest_sha256!==ROUND2_REVIEWED_CANDIDATE.manifest_sha256||record.parsed.reviewed_file_count!==ROUND2_REVIEWED_CANDIDATE.file_count||record.parsed.surface_queue_sha256!==ROUND2_REVIEWED_CANDIDATE.queue_sha256||record.parsed.surface_queue_view_sha256!==ROUND2_REVIEWED_CANDIDATE.view_sha256||JSON.stringify(record.parsed.resolved_findings)!==JSON.stringify(['R2-A','R2-B'])||record.parsed.findings.length!==0||record.parsed.repository_modified_by_review!==false||record.parsed.auditor_call_made!==false)throw Error(`ROUND2_REPAIR_${kind.toUpperCase()}_REVIEW_BINDING`);
    reviews[kind]={path:ROUND2_REPAIR_REVIEW_PATHS[kind],sha256:sha256(record.bytes),agent_id:record.parsed.reviewer_agent_id,role,status:'PASS'};
  }
  if(reviews.normal.agent_id===reviews.senior.agent_id)throw Error('ROUND2_REPAIR_REVIEWER_INDEPENDENCE');
  const gate=canonicalRecord(repo,ROUND2_REPAIR_REVIEW_PATHS.gate,'ROUND2_REPAIR_REVIEW_GATE'),g=gate.parsed;
  const keys=['schema_version','gate_id','status','candidate_ref','candidate_manifest_path','candidate_manifest_sha256','normal_review','senior_review','transition_files','authorized_input_boundary','auditor_contract','permitted_next_action','forbidden_before_valid_auditor_output','surface_auditor_call_made'];
  const forbidden=['SURFACE_RECORDS_OR_AGGREGATE_MATERIALIZATION','CONTEXT_INPUT_OR_OUTPUT','ROUND_0002_REPLACEMENT_OR_RELEASE','ROUND_0003','FORMAL_GEMINI_INFERENCE','UNRELATED_MODEL_OR_NETWORK_CALL'];
  const contract={authorized_call_number:1,call_count_allowance:1,calls_started:0,calls_remaining:1,payload_path:'rounds/ROUND-0002/SURFACE-QUEUE-VIEW.json',payload_sha256:ROUND2_REVIEWED_CANDIDATE.view_sha256,payload_is_exact_view_bytes_only:true,queue_is_binding_not_payload:true,response_schema_version:'gemini-context-v5-surface-auditor-response-v2',response_item_keys:['neutral_id','verdict','evidence'],allowed_verdicts:['PASS_SURFACE','NOT_CLEAN','OUT_OF_SCOPE_NON_PROSE'],ordered_neutral_ids:queue.items.map(item=>item.neutral_id),evidence_required_nonempty:true,response_persistence_authorized_by_this_gate:false,results_materialization_authorized_by_this_gate:false};
  const boundary={round_id:'ROUND-0002',stage:'SURFACE',item_count:10,surface_queue_sha256:ROUND2_REVIEWED_CANDIDATE.queue_sha256,surface_queue_view_sha256:ROUND2_REVIEWED_CANDIDATE.view_sha256,authorization_record_sha256:queue.authorization_record_sha256};
  if(JSON.stringify(Object.keys(g).sort())!==JSON.stringify([...keys].sort())||g.schema_version!=='gemini-context-v5-round-0002-surface-input-repair-review-gate-v1'||g.gate_id!=='V5-ROUND-0002-SURFACE-INPUT-REPAIR-DUAL-PASS-GATE-001'||g.status!=='SATISFIED_FINAL_DUAL_PASS'||g.candidate_ref!==ROUND2_REVIEWED_CANDIDATE.candidate_ref||g.candidate_manifest_path!==candidate.path||g.candidate_manifest_sha256!==ROUND2_REVIEWED_CANDIDATE.manifest_sha256||JSON.stringify(g.normal_review)!==JSON.stringify(reviews.normal)||JSON.stringify(g.senior_review)!==JSON.stringify(reviews.senior)||JSON.stringify(g.transition_files?.map(item=>item.path))!==JSON.stringify(ROUND2_GATE_TRANSITION_PATHS)||JSON.stringify(g.authorized_input_boundary)!==JSON.stringify(boundary)||JSON.stringify(g.auditor_contract)!==JSON.stringify(contract)||g.permitted_next_action!=='GO_ROUND_0002_SURFACE_AUDITOR_CALL_ONLY'||JSON.stringify(g.forbidden_before_valid_auditor_output)!==JSON.stringify(forbidden)||g.surface_auditor_call_made!==false)throw Error('ROUND2_REPAIR_REVIEW_GATE_BINDING');
  if(verifyTransitionFiles)for(const item of g.transition_files){if(sha256(fs.readFileSync(path.join(repo,item.path)))!==item.sha256)throw Error(`ROUND2_GATE_TRANSITION_FILE:${item.path}`);}
  return {path:ROUND2_REPAIR_REVIEW_PATHS.gate,sha256:sha256(gate.bytes),record:g,auditor_contract:contract};
}

export function validateReleaseImplementationAuthorization(repo) {
  const file = path.join(repo, RELEASE_AUTHORIZATION_PATH), stat = fs.lstatSync(file); if (stat.isSymbolicLink() || !stat.isFile()) throw Error('RELEASE_AUTHORIZATION_FILE_TYPE');
  const bytes = fs.readFileSync(file), record = JSON.parse(bytes); if (!bytes.equals(jsonBytes(record)) || sha256(bytes) !== RELEASE_AUTHORIZATION_SHA256) throw Error('RELEASE_AUTHORIZATION_BYTES');
  const keys = ['schema_version', 'authorization_id', 'status', 'authorized_by', 'round_id', 'executor', 'scout', 'scope', 'required_review_gate', 'permitted_current_decision', 'forbidden_before_review'];
  if (JSON.stringify(Object.keys(record).sort()) !== JSON.stringify(keys.sort()) || record.schema_version !== 'gemini-context-v5-round-release-implementation-authorization-v1' || record.authorization_id !== 'V5-ROUND-0001-REPLACEMENT-RELEASE-IMPLEMENTATION-001' || record.status !== 'AUTHORIZED_IMPLEMENTATION_PENDING_INDEPENDENT_DUAL_REVIEW' || record.authorized_by !== 'user' || record.round_id !== 'ROUND-0001' || record.executor?.role !== 'EXECUTOR' || record.executor?.agent_id !== 'f5cc0aa8-b313-4ca7-8f92-191041de73a8' || record.executor?.route !== 'native Codex fallback' || typeof record.executor?.reason !== 'string' || !record.executor.reason || record.scout?.role !== 'SCOUT' || record.scout?.agent_id !== '2bb54f05-3044-49c3-b06c-d63977d62385' || record.scout?.status !== 'COMPLETED_READ_ONLY_DESIGN_HARVESTED' || record.scout?.write_authorized !== false) throw Error('RELEASE_AUTHORIZATION_IDENTITY');
  const scope = record.scope;
  if (scope?.frozen_round_artifact_count !== 9 || scope?.deterministic_rejected_slot_count !== 10 || scope?.surface_rejected_slot_count !== 9 || scope?.context_rejected_slot_count !== 1 || scope?.temporary_fixture_release_derivation !== true || scope?.release_schema_and_replay_implementation !== true || scope?.lineage_and_reserve_accounting_implementation !== true || scope?.real_release_materialization_before_dual_review !== false || scope?.real_active_lineage_reserve_round_index_mutation_before_dual_review !== false || scope?.round_0002_audit_authorized !== false || scope?.model_calls_authorized !== false || scope?.network_calls_authorized !== false) throw Error('RELEASE_AUTHORIZATION_SCOPE');
  if (record.required_review_gate?.status !== 'REQUIRED' || record.required_review_gate?.normal_review_path !== RELEASE_REVIEW_PATHS[0] || record.required_review_gate?.senior_review_path !== RELEASE_REVIEW_PATHS[1] || record.required_review_gate?.combined_gate_path !== RELEASE_REVIEW_PATHS[2] || record.permitted_current_decision !== 'NO_GO_RELEASE_IMPLEMENTATION_REVIEW_REQUIRED') throw Error('RELEASE_AUTHORIZATION_REVIEW_GATE');
  return {authorization_path: RELEASE_AUTHORIZATION_PATH, authorization_sha256: RELEASE_AUTHORIZATION_SHA256, status: record.status};
}

export function completedExperimentDocument(releaseState) {
  if (releaseState.schema_version === 'gemini-context-v5-release-state-v4') return {schema_version: 'gemini-context-v5-experiment-state-v4', status: 'ROUND_0002_RELEASED_ROUND_0003_AUDIT_NOT_AUTHORIZED', completed_rounds: 2, last_release_sha256: releaseState.last_release_sha256, released_round: releaseState.released_round, audits_released: true, replacements_authorized: true, release_authorized: true, mutations_released: true, round_0003_audit_authorized: false, qualification_authorized: false, inference_authorized: false, formal_gemini_experiment_inference_calls_made: 0, model_calls_started: 0, network_calls_made: 0};
  return {
    schema_version: 'gemini-context-v5-experiment-state-v3',
    status: 'ROUND_0001_RELEASED_ROUND_0002_AUDIT_NOT_AUTHORIZED',
    completed_rounds: 1,
    last_release_sha256: releaseState.last_release_sha256,
    released_round: releaseState.released_round,
    audits_released: true,
    replacements_authorized: true,
    release_authorized: true,
    mutations_released: true,
    round_0002_audit_authorized: false,
    qualification_authorized: false,
    inference_authorized: false,
    authorized_surface_auditor_calls_started: 2,
    invalid_auditor_input_attempts: 1,
    valid_surface_auditor_responses: 1,
    valid_persisted_surface_results: 1,
    authorized_context_auditor_calls_started: 1,
    valid_context_auditor_responses: 1,
    valid_persisted_context_results: 1,
    formal_gemini_experiment_inference_calls_made: 0,
    network_calls_made: 0
  };
}

export function runPreflight(root = here, {allowUnverifiedFixture = false} = {}) {
if (arguments.length > 2) throw Error('ROUND_RELEASE_RUNTIME_PIN_OVERRIDE_FORBIDDEN');
const pendingPath = path.join(root, 'PENDING-RELEASE.json'), pending = fs.existsSync(pendingPath) ? JSON.parse(fs.readFileSync(pendingPath)) : null, repo = path.resolve(root, '..', '..', '..', '..');
if (pending?.schema_version === 'gemini-context-v5-round-0002-pending-release-v1') {
  try {
    validateUnexpectedRound2ReleaseReviews(repo);
    const {candidate} = validateRound2PendingRelease(root, repo);
    if (fs.existsSync(path.join(root, 'rounds/ROUND-0003'))) throw Error('ROUND3_FORBIDDEN');
    const review = evaluateRound2ReleaseReviewGate(repo, {allowUnverifiedFixture});
    const common = {static_integrity: review.invalid ? 'FAIL_CLOSED' : 'PASS', completed_rounds: 1, last_release_sha256: pending.predecessor_release_sha256, candidate_ref: candidate.candidate_ref, candidate_manifest_sha256: candidate.manifest_sha256, candidate_file_count: candidate.file_count, expected_hashes: candidate.expected_hashes, deterministic_rejected_slot_count: 2, active_rows_after_release: 64, lineage_edges_after_release: 12, remaining_reserve_rows_after_release: 299, remaining_dialogue_reserve_rows_after_release: 226, remaining_narrative_reserve_rows_after_release: 73, banned_revision_ids_after_release: 12, consumed_revision_ids_after_release: 12, real_release_created: false, derived_state_mutated: false, round_0003_created: false, formal_gemini_experiment_inference_calls_made: 0, model_calls_started: 0, network_calls_made: 0};
    if (review.invalid) return {decision: 'NO_GO_ROUND_0002_RELEASE_REVIEW_INVALID', ...common, run_status: 'ROUND_0002_RELEASE_REVIEW_INVALID', reason: review.reason};
    if (!review.satisfied) return {decision: 'NO_GO_ROUND_0002_RELEASE_IMPLEMENTATION_REVIEW_REQUIRED', ...common, run_status: 'ROUND_0002_RELEASE_IMPLEMENTATION_PENDING_INDEPENDENT_DUAL_REVIEW', review_gate_reason: review.reason, blockers: ['NORMAL_REVIEW_REQUIRED','SENIOR_REVIEW_REQUIRED','COMBINED_RELEASE_REVIEW_GATE_REQUIRED','ATOMIC_MATERIALIZATION_ONLY_AFTER_DUAL_PASS','ROUND_0003_NOT_AUTHORIZED']};
    return {decision: 'GO_ROUND_0002_RELEASE_MATERIALIZATION_ONLY', ...common, run_status: 'ROUND_0002_RELEASE_IMPLEMENTATION_DUAL_PASS_READY', review_gate: review.provenance, blockers: ['ATOMIC_MATERIALIZATION_ONLY','ROUND_0003_NOT_AUTHORIZED']};
  } catch (error) {
    if (error.message?.startsWith('ROUND2_RELEASE_UNEXPECTED_REVIEW_ARTIFACT:')) return {decision: 'NO_GO_ROUND_0002_RELEASE_REVIEW_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0002_RELEASE_REVIEW_INVALID', reason: error.message, completed_rounds: 1, real_release_created: false, derived_state_mutated: false, round_0003_created: false, model_calls_started: 0, network_calls_made: 0};
    return {decision: 'NO_GO_ROUND_0002_RELEASE_IMPLEMENTATION_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0002_RELEASE_IMPLEMENTATION_INVALID', reason: error.code === 'ENOENT' ? 'ROUND2_RELEASE_IMPLEMENTATION_ARTIFACT_MISSING' : error.message, completed_rounds: 1, last_release_sha256: pending.predecessor_release_sha256, real_release_created: false, round_0003_created: false, formal_gemini_experiment_inference_calls_made: 0, model_calls_started: 0, network_calls_made: 0};
  }
}
if (pending) {
  const reviewGate = evaluateSidecarReviewGate(repo, pending);
  if (!reviewGate.satisfied) return {decision: 'NO_GO_SIDECAR_REVIEW_BINDING_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'SIDECAR_REVIEW_GATE_INVALID', review_gate_reason: reviewGate.reason, completed_rounds: 0, audits_released: false, surface_audit_retry_input_authorized: false, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0};
  const contextReviewGate = evaluateContextInputReviewGate(repo, pending);
  if (!contextReviewGate.satisfied) return {decision: 'NO_GO_CONTEXT_INPUT_REVIEW_BINDING_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'CONTEXT_INPUT_REVIEW_GATE_INVALID', review_gate_reason: contextReviewGate.reason, completed_rounds: 0, audits_released: false, context_auditor_input_authorized: false, context_auditor_calls_started: 0, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0};
  const contextResultsGate = evaluateContextResultsReviewGate(repo, pending);
  if (!contextResultsGate.satisfied) return {decision: 'NO_GO_CONTEXT_RESULTS_REVIEW_BINDING_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'CONTEXT_RESULTS_REVIEW_GATE_INVALID', review_gate_reason: contextResultsGate.reason, completed_rounds: 0, audits_released: false, context_results_materialization_authorized: false, context_auditor_calls_started: 1, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0};
}
let docs;
try { docs = replay(root); }
catch (error) {
  if (!pending && fs.existsSync(path.join(root, 'rounds', 'ROUND-0002'))) {const contextStarted=['CONTEXT-QUEUE.json','CONTEXT-SOURCE-ANCHORS.json','CONTEXT-QUEUE-VIEW.json'].some(name=>fs.existsSync(path.join(root,'rounds','ROUND-0002',name)));return {decision:contextStarted?'NO_GO_ROUND_0002_CONTEXT_INPUT_INVALID':'NO_GO_ROUND_0002_SURFACE_INPUT_INVALID', static_integrity:'FAIL_CLOSED', run_status:contextStarted?'ROUND_0002_CONTEXT_INPUT_INVALID':'ROUND_0002_SURFACE_INPUT_INVALID', reason:error.code==='ENOENT'?'ROUND_0002_INPUT_OR_AUTHORIZATION_MISSING':error.message, completed_rounds:1,audits_released:true,round_0002_surface_input_authorized:true,surface_auditor_call_authorized:false,context_auditor_call_authorized:false,formal_gemini_experiment_inference_calls_made:0,network_calls_made:0};}
  if (!pending && fs.existsSync(path.join(root, 'rounds', 'ROUND-0001', 'RELEASE.json'))) return {decision: 'NO_GO_RELEASE_REVIEW_BINDING_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'COMPLETED_RELEASE_REVIEW_INVALID', reason: error.code === 'ENOENT' ? 'RELEASE_REVIEW_FILE_MISSING' : error.message, completed_rounds: 0, audits_released: false, round_0002_audit_authorized: false, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0};
  throw error;
}
const completedRounds = docs['ROUND-INDEX.json'].completed_rounds;
try {
  for (const [name, doc] of Object.entries(docs)) if (!fs.existsSync(path.join(root, name)) || !fs.readFileSync(path.join(root, name)).equals(jsonBytes(doc))) throw Error(`DETERMINISTIC_REPLAY_DRIFT:${name}`);
} catch (error) {
  return {decision: 'NO_GO_ROUND_0002_RELEASE_REVIEW_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0002_COMPLETED_RELEASE_EVIDENCE_INVALID', reason: error.message, completed_rounds: completedRounds, real_release_created: completedRounds >= 2, round_0003_created: false, model_calls_started: 0, network_calls_made: 0};
}
if (!pending && completedRounds === 2) {
  const requiredCompletedFiles = ['rounds/ROUND-0002/RELEASE.json', 'ACTIVE-FRAME.json', 'LINEAGE.json', 'RESERVE-STATE.json', 'ROUND-INDEX.json', 'RELEASE-STATE.json', 'EXPERIMENT.json'];
  const missingCompletedFile = requiredCompletedFiles.find(name => !fs.existsSync(path.join(root, name)));
  if (missingCompletedFile) return {decision: 'NO_GO_ROUND_0002_RELEASE_REVIEW_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0002_COMPLETED_RELEASE_EVIDENCE_INVALID', reason: `ROUND2_COMPLETED_REQUIRED_FILE_MISSING:${missingCompletedFile}`, completed_rounds: 2, real_release_created: true, round_0003_created: false, model_calls_started: 0, network_calls_made: 0};
}
if (!pending && completedRounds === 2) {
  const releaseState = docs['RELEASE-STATE.json'], experimentBytes = fs.readFileSync(path.join(root, 'EXPERIMENT.json'));
  let completedEvidence;
  try { completedEvidence = validateRound2CompletedReleaseEvidence(repo, {allowUnverifiedFixture}); }
  catch (error) { return {decision: 'NO_GO_ROUND_0002_RELEASE_REVIEW_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0002_COMPLETED_RELEASE_EVIDENCE_INVALID', reason: error.message, completed_rounds: 2, real_release_created: true, round_0003_created: false, model_calls_started: 0, network_calls_made: 0}; }
  if (releaseState.schema_version !== 'gemini-context-v5-release-state-v4' || releaseState.status !== 'ROUND_0002_RELEASED_ROUND_0003_AUDIT_NOT_AUTHORIZED' || releaseState.last_release_sha256 !== docs['ROUND-INDEX.json'].last_release_sha256 || releaseState.released_round?.round_id !== 'ROUND-0002' || releaseState.released_round?.release_sha256 !== releaseState.last_release_sha256 || releaseState.released_round?.predecessor_release_sha256 !== 'bf37e1fc2f1015d6c86e0666154338df591d2f556a489b25ba775ccf7ce66119' || releaseState.released_round?.release_authorization?.executor_agent_id !== 'f77eedbb-5a3b-4ecb-98f6-32d9243a4164' || releaseState.released_round?.release_authorization?.review_routing?.senior !== 'GEMINI_3_7_FLASH' || releaseState.released_round?.release_authorization?.review_routing?.opus_calls_authorized !== false || releaseState.active_rows !== 64 || releaseState.lineage_edges !== 12 || releaseState.remaining_reserve_rows !== 299 || releaseState.remaining_dialogue_reserve_rows !== 226 || releaseState.remaining_narrative_reserve_rows !== 73 || releaseState.banned_revision_ids !== 12 || releaseState.consumed_revision_ids !== 12 || releaseState.round_0003_audit_authorized !== false || releaseState.formal_gemini_experiment_inference_calls_made !== 0 || releaseState.model_calls_started !== 0 || releaseState.network_calls_made !== 0) throw Error('ROUND2_COMPLETED_RELEASE_STATE_BINDING');
  if (!experimentBytes.equals(jsonBytes(completedExperimentDocument(releaseState)))) throw Error('ROUND2_COMPLETED_EXPERIMENT_STATE_BINDING');
  if (fs.existsSync(path.join(root, 'PENDING-RELEASE.json')) || fs.existsSync(path.join(root, 'rounds', 'ROUND-0003'))) throw Error('ROUND2_COMPLETED_FORBIDDEN_ARTIFACT');
  return {decision: 'NO_GO_ROUND_0003_AUDIT_NOT_AUTHORIZED', static_integrity: 'PASS', run_status: releaseState.status, completed_rounds: 2, last_release_sha256: releaseState.last_release_sha256, active_rows: 64, lineage_edges: 12, remaining_reserve_rows: 299, remaining_dialogue_reserve_rows: 226, banned_revision_ids: 12, consumed_revision_ids: 12, round_0003_audit_authorized: false, qualification_authorized: false, inference_authorized: false, formal_gemini_experiment_inference_calls_made: 0, model_calls_started: 0, network_calls_made: 0, completed_release_review_gate: completedEvidence, blockers: ['ROUND_0003_AUDIT_NOT_AUTHORIZED']};
}
if (!pending && completedRounds === 1) {
  const releaseState = docs['RELEASE-STATE.json'];
  const releaseBytes = fs.readFileSync(path.join(root, 'rounds', 'ROUND-0001', 'RELEASE.json')), releaseDocument = JSON.parse(releaseBytes);
  try { validateReleaseReviewGate(repo, {release_authorization: releaseDocument.release_authorization, implementation_review_gate: releaseDocument.implementation_review_gate, release: releaseDocument}); }
  catch (error) { return {decision: 'NO_GO_RELEASE_REVIEW_BINDING_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'COMPLETED_RELEASE_REVIEW_INVALID', reason: error.code === 'ENOENT' ? 'RELEASE_REVIEW_FILE_MISSING' : error.message, completed_rounds: 1, last_release_sha256: sha256(releaseBytes), audits_released: false, round_0002_audit_authorized: false, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0}; }
  const hasRound2SurfaceInput = fs.existsSync(path.join(root, 'rounds', 'ROUND-0002'));
  if (!hasRound2SurfaceInput) {
    const materializationReview = evaluateReleaseImplementationReviewGate(repo, {materializedRelease: releaseDocument});
    if (!materializationReview.satisfied) return {decision: 'NO_GO_RELEASE_REVIEW_BINDING_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'COMPLETED_RELEASE_MATERIALIZATION_REVIEW_INVALID', reason: materializationReview.reason, completed_rounds: 1, last_release_sha256: sha256(releaseBytes), audits_released: false, round_0002_audit_authorized: false, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0};
  }
  if (releaseState.schema_version !== 'gemini-context-v5-release-state-v3' || releaseState.status !== 'ROUND_0001_RELEASED_ROUND_0002_AUDIT_NOT_AUTHORIZED' || releaseState.last_release_sha256 !== docs['ROUND-INDEX.json'].last_release_sha256 || releaseState.released_round?.round_id !== 'ROUND-0001' || releaseState.released_round?.release_sha256 !== releaseState.last_release_sha256 || releaseState.released_round?.predecessor_release_sha256 !== null || releaseState.released_round?.release_authorization?.authorized_by !== 'user' || releaseState.released_round?.release_authorization?.executor_agent_id !== 'f5cc0aa8-b313-4ca7-8f92-191041de73a8' || releaseState.released_round?.implementation_review_gate?.status !== 'SATISFIED_FINAL_DUAL_PASS' || releaseState.released_round?.implementation_review_gate?.verification_mode !== 'REPO_REVIEW_RECORDS' || releaseState.released_round?.implementation_review_gate?.normal?.agent_id === releaseState.released_round?.implementation_review_gate?.senior?.agent_id || releaseState.completed_surface_stage_applied_to_active_state !== true || releaseState.context_input_applied_to_active_state !== true || releaseState.active_frame_mutated !== true || releaseState.lineage_mutated !== true || releaseState.reserve_mutated !== true || releaseState.banned_revision_ids_added !== 10 || releaseState.consumed_revision_ids_added !== 10 || releaseState.replacements_authorized !== true || releaseState.release_authorized !== true || releaseState.audits_released !== true || releaseState.round_0002_audit_authorized !== false || releaseState.qualification_authorized !== false || releaseState.inference_authorized !== false || releaseState.authorized_surface_auditor_calls_started !== 2 || releaseState.invalid_auditor_input_attempts !== 1 || releaseState.valid_surface_auditor_responses !== 1 || releaseState.valid_persisted_surface_results !== 1 || releaseState.authorized_context_auditor_calls_started !== 1 || releaseState.valid_context_auditor_responses !== 1 || releaseState.valid_persisted_context_results !== 1 || releaseState.formal_gemini_experiment_inference_calls_made !== 0 || releaseState.network_calls_made !== 0) throw Error('COMPLETED_RELEASE_STATE_BINDING');
  const experimentBytes = fs.readFileSync(path.join(root, 'EXPERIMENT.json')), expectedExperiment = completedExperimentDocument(releaseState);
  if (!experimentBytes.equals(jsonBytes(expectedExperiment))) throw Error('COMPLETED_EXPERIMENT_STATE_BINDING');
  const round2 = path.join(root, 'rounds', 'ROUND-0002');
  if (fs.existsSync(round2)) {
    const queuePath = path.join(round2, 'SURFACE-QUEUE.json'), viewPath = path.join(round2, 'SURFACE-QUEUE-VIEW.json'), authorizationPath = path.join(repo, ROUND2_AUTHORIZATION_PATH);
    const surfaceCompleted = fs.existsSync(path.join(round2,'SURFACE-RECORDS.json')) || fs.existsSync(path.join(round2,'SURFACE-AGGREGATE.json'));
    if(surfaceCompleted){
      const candidate={path:ROUND2_CANDIDATE_MANIFEST_PATH,sha256:ROUND2_REVIEWED_CANDIDATE.manifest_sha256,candidate_ref:ROUND2_REVIEWED_CANDIDATE.candidate_ref,file_count:ROUND2_REVIEWED_CANDIDATE.file_count,reviewed_gate_transition:true};
      let gate,results;
      try{
        const manifestBytes=fs.readFileSync(path.join(repo,ROUND2_CANDIDATE_MANIFEST_PATH));
        if(sha256(manifestBytes)!==candidate.sha256)throw Error('ROUND2_REVIEWED_CANDIDATE_IDENTITY');
        gate=validateRound2RepairReviewGate(repo,JSON.parse(fs.readFileSync(queuePath)),candidate,{verifyTransitionFiles:false});
        results=validateRound2SurfaceArtifacts({root});
      }catch(error){return {decision:'NO_GO_ROUND_0002_SURFACE_RESULTS_INVALID',static_integrity:'FAIL_CLOSED',run_status:'ROUND_0002_SURFACE_RESULTS_INVALID',reason:error.code==='ENOENT'?'ROUND_0002_SURFACE_RESULT_OR_GATE_MISSING':error.message,completed_rounds:1,last_release_sha256:releaseState.last_release_sha256,round_0002_surface_input_authorized:true,surface_auditor_call_authorized:false,formal_gemini_experiment_inference_calls_made:0,network_calls_made:0};}
      const contextPaths=['CONTEXT-QUEUE.json','CONTEXT-SOURCE-ANCHORS.json','CONTEXT-QUEUE-VIEW.json'],contextStarted=contextPaths.some(name=>fs.existsSync(path.join(round2,name)));
      if(contextStarted){
        const contextResultPaths=['CONTEXT-RECORDS.json','CONTEXT-AGGREGATE.json'],contextResultsStarted=contextResultPaths.some(name=>fs.existsSync(path.join(round2,name)));let context,candidateContext,lifecycle,contextResults;try{if(!contextPaths.every(name=>fs.existsSync(path.join(round2,name))))throw Error('ROUND2_CONTEXT_INPUT_PARTIAL');if(contextResultsStarted&&!contextResultPaths.every(name=>fs.existsSync(path.join(round2,name))))throw Error('ROUND2_CONTEXT_RESULTS_PARTIAL');context=validateRound2ContextInput({root,repo});candidateContext=contextResultsStarted?validateRound2ReviewedContextCandidate(repo):validateRound2ContextCandidate(repo);lifecycle=evaluateRound2ContextReviewLifecycle(repo,candidateContext);if(contextResultsStarted)contextResults=validateRound2ContextArtifacts({root});}catch(error){return {decision:contextResultsStarted?'NO_GO_ROUND_0002_CONTEXT_RESULTS_INVALID':'NO_GO_ROUND_0002_CONTEXT_INPUT_INVALID',static_integrity:'FAIL_CLOSED',run_status:contextResultsStarted?'ROUND_0002_CONTEXT_RESULTS_INVALID':'ROUND_0002_CONTEXT_INPUT_INVALID',reason:error.code==='ENOENT'?'ROUND_0002_CONTEXT_INPUT_RESULT_OR_CANDIDATE_MISSING':error.message,completed_rounds:1,last_release_sha256:releaseState.last_release_sha256,round_0002_surface_input_authorized:true,round_0002_context_input_authorized:true,context_auditor_call_authorized:false,formal_gemini_experiment_inference_calls_made:0,network_calls_made:0};}
        if(contextResultsStarted)return {decision:'NO_GO_ROUND_0002_RELEASE_NOT_AUTHORIZED',static_integrity:'PASS',run_status:'ROUND_0002_AUDIT_RESULTS_FROZEN_RELEASE_NOT_AUTHORIZED',review_lifecycle_status:lifecycle.status,completed_rounds:1,last_release_sha256:releaseState.last_release_sha256,active_frame_sha256:sha256(fs.readFileSync(path.join(root,'ACTIVE-FRAME.json'))),lineage_sha256:sha256(fs.readFileSync(path.join(root,'LINEAGE.json'))),reserve_state_sha256:sha256(fs.readFileSync(path.join(root,'RESERVE-STATE.json'))),round_index_sha256:sha256(fs.readFileSync(path.join(root,'ROUND-INDEX.json'))),context_auditor_agent_id:contextResults.auditor_agent_id,context_auditor_call_authorized:false,context_auditor_call_count_allowance:1,context_auditor_calls_started:1,context_auditor_calls_remaining:0,raw_context_response_sha256:contextResults.raw_response_sha256,context_records_sha256:contextResults.context_records_sha256,context_aggregate_sha256:contextResults.context_aggregate_sha256,context_verdict_counts:contextResults.counts,context_clean_ids:contextResults.clean_ids,context_not_clean_ids:contextResults.not_clean_ids,context_results_frozen:true,round_0002_replacement_authorized:false,round_0002_release_authorized:false,pending_release_created:false,active_frame_mutated:false,lineage_mutated:false,reserve_mutated:false,round_index_mutated:false,round_0003_created:false,formal_gemini_experiment_inference_calls_made:0,model_calls_started:0,network_calls_made:0,blockers:['ROUND_0002_RELEASE_NOT_AUTHORIZED','ROUND_0002_REPLACEMENT_NOT_AUTHORIZED','ROUND_0003_FORBIDDEN']};
        if(lifecycle.authorized)return {decision:'GO_ROUND_0002_CONTEXT_AUDITOR_CALL_ONLY',static_integrity:'PASS',run_status:'ROUND_0002_CONTEXT_INPUT_DUAL_PASS_CONTEXT_AUDITOR_CALL_AUTHORIZED',review_lifecycle_status:lifecycle.status,completed_rounds:1,context_auditor_call_authorized:true,context_auditor_call_count_allowance:1,context_auditor_calls_started:0,context_auditor_calls_remaining:1,context_queue_sha256:context.context_queue_sha256,context_source_anchors_sha256:context.context_source_anchors_sha256,context_queue_view_sha256:context.context_queue_view_sha256,context_candidate_ref:candidateContext.candidate_ref,context_candidate_manifest_sha256:candidateContext.sha256,blockers:[],formal_gemini_experiment_inference_calls_made:0,model_calls_started:0,network_calls_made:0};
        const pendingDecision={PENDING_NORMAL_AND_SENIOR:['NO_GO_ROUND_0002_CONTEXT_INPUT_REVIEW_REQUIRED','ROUND_0002_CONTEXT_INPUT_PENDING_NORMAL_AND_SENIOR'],PENDING_OTHER_REVIEW:['NO_GO_ROUND_0002_CONTEXT_INPUT_REVIEW_REQUIRED','ROUND_0002_CONTEXT_INPUT_PENDING_OTHER_REVIEW'],DUAL_PASS_GATE_REQUIRED:['NO_GO_ROUND_0002_CONTEXT_INPUT_GATE_REQUIRED','ROUND_0002_CONTEXT_INPUT_DUAL_PASS_GATE_REQUIRED'],NO_GO_REPAIR_REQUIRED:['NO_GO_ROUND_0002_CONTEXT_INPUT_REPAIR_REQUIRED','ROUND_0002_CONTEXT_INPUT_REPAIR_REQUIRED']}[lifecycle.status];if(!pendingDecision)throw Error('ROUND2_CONTEXT_REVIEW_LIFECYCLE_UNEXPECTED');
        return {decision:pendingDecision[0],static_integrity:'PASS',run_status:pendingDecision[1],review_lifecycle_status:lifecycle.status,completed_rounds:1,last_release_sha256:releaseState.last_release_sha256,active_frame_sha256:sha256(fs.readFileSync(path.join(root,'ACTIVE-FRAME.json'))),lineage_sha256:sha256(fs.readFileSync(path.join(root,'LINEAGE.json'))),round_0002_surface_input_authorized:true,round_0002_surface_input_frozen:true,surface_queue_sha256:sha256(fs.readFileSync(queuePath)),surface_queue_view_sha256:sha256(fs.readFileSync(viewPath)),surface_records_sha256:results.surface_records_sha256,surface_aggregate_sha256:results.surface_aggregate_sha256,surface_auditor_call_authorized:false,round_0002_surface_auditor_call_count_allowance:1,round_0002_surface_auditor_calls_started:1,round_0002_surface_auditor_calls_remaining:0,round_0002_context_input_authorized:true,round_0002_context_input_frozen:true,context_queue_path:'rounds/ROUND-0002/CONTEXT-QUEUE.json',context_queue_sha256:context.context_queue_sha256,context_source_anchors_path:'rounds/ROUND-0002/CONTEXT-SOURCE-ANCHORS.json',context_source_anchors_sha256:context.context_source_anchors_sha256,context_queue_view_path:'rounds/ROUND-0002/CONTEXT-QUEUE-VIEW.json',context_queue_view_sha256:context.context_queue_view_sha256,context_item_count:context.item_count,context_source_file_count:context.source_file_count,context_eligible_ids:context.context_eligible_ids,context_auditor_call_authorized:false,context_auditor_calls_started:0,context_candidate_ref:candidateContext.candidate_ref,context_candidate_manifest_path:candidateContext.path,context_candidate_manifest_sha256:candidateContext.sha256,context_candidate_file_count:candidateContext.file_count,context_records_created:false,context_aggregate_created:false,active_frame_mutated:false,lineage_mutated:false,reserve_mutated:false,round_index_mutated:false,round_0002_replacements_created:false,round_0002_release_created:false,round_0003_created:false,formal_gemini_experiment_inference_calls_made:0,model_calls_started:0,network_calls_made:0,blockers:lifecycle.blockers};
      }
      return {decision:'NO_GO_ROUND_0002_CONTEXT_INPUT_IMPLEMENTATION_REQUIRED',static_integrity:'PASS',run_status:'ROUND_0002_SURFACE_RESULTS_MATERIALIZED_CONTEXT_INPUT_IMPLEMENTATION_REQUIRED',completed_rounds:1,last_release_sha256:releaseState.last_release_sha256,active_frame_sha256:sha256(fs.readFileSync(path.join(root,'ACTIVE-FRAME.json'))),lineage_sha256:sha256(fs.readFileSync(path.join(root,'LINEAGE.json'))),round_0002_surface_input_authorized:true,round_0002_surface_input_frozen:true,surface_queue_path:path.relative(root,queuePath),surface_queue_sha256:sha256(fs.readFileSync(queuePath)),surface_queue_view_path:path.relative(root,viewPath),surface_queue_view_sha256:sha256(fs.readFileSync(viewPath)),authorization_path:ROUND2_AUTHORIZATION_PATH,authorization_sha256:sha256(fs.readFileSync(authorizationPath)),candidate_ref:candidate.candidate_ref,candidate_manifest_path:candidate.path,candidate_manifest_sha256:candidate.sha256,candidate_file_count:candidate.file_count,review_gate_path:gate.path,review_gate_sha256:gate.sha256,item_count:10,surface_auditor_agent_id:ROUND2_SURFACE_CALL.auditor_agent_id,authorized_surface_auditor_call_number:1,round_0002_surface_auditor_call_count_allowance:1,round_0002_surface_auditor_calls_started:1,round_0002_surface_auditor_calls_remaining:0,surface_auditor_call_authorized:false,raw_surface_response_path:ROUND2_SURFACE_CALL.response_path,raw_surface_response_sha256:results.raw_response_sha256,surface_records_created:true,surface_records_sha256:results.surface_records_sha256,surface_aggregate_created:true,surface_aggregate_sha256:results.surface_aggregate_sha256,verdict_counts:results.counts,context_eligible_ids:results.context_eligible_ids,context_inputs_created:false,active_frame_mutated:false,lineage_mutated:false,reserve_mutated:false,round_index_mutated:false,round_0002_replacements_created:false,round_0002_release_created:false,round_0003_created:false,formal_gemini_experiment_inference_calls_made:0,model_calls_started:0,network_calls_made:0,blockers:['ROUND_0002_CONTEXT_INPUT_IMPLEMENTATION_REQUIRED','CONTEXT_AUDITOR_CALL_NOT_AUTHORIZED','ROUND_0002_REPLACEMENT_RELEASE_NOT_AUTHORIZED','ROUND_0003_FORBIDDEN']};
    }
    let candidate;
    try { candidate = validateRound2CandidateManifest(repo); }
    catch (error) { return {decision: 'NO_GO_ROUND_0002_SURFACE_INPUT_CANDIDATE_INVALID', static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0002_SURFACE_INPUT_CANDIDATE_INVALID', reason: error.code === 'ENOENT' ? 'ROUND_0002_CANDIDATE_MANIFEST_MISSING' : error.message, completed_rounds: 1, last_release_sha256: releaseState.last_release_sha256, audits_released: true, round_0002_surface_input_authorized: true, surface_auditor_call_authorized: false, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0}; }
    const common={static_integrity:'PASS',completed_rounds:1,last_release_sha256:releaseState.last_release_sha256,active_frame_sha256:sha256(fs.readFileSync(path.join(root,'ACTIVE-FRAME.json'))),lineage_sha256:sha256(fs.readFileSync(path.join(root,'LINEAGE.json'))),round_0002_surface_input_authorized:true,round_0002_surface_input_frozen:true,surface_queue_path:path.relative(root,queuePath),surface_queue_sha256:sha256(fs.readFileSync(queuePath)),surface_queue_view_path:path.relative(root,viewPath),surface_queue_view_sha256:sha256(fs.readFileSync(viewPath)),authorization_path:ROUND2_AUTHORIZATION_PATH,authorization_sha256:sha256(fs.readFileSync(authorizationPath)),item_count:10,candidate_ref:candidate.candidate_ref,candidate_manifest_path:candidate.path,candidate_manifest_sha256:candidate.sha256,candidate_file_count:candidate.file_count,active_frame_mutated:false,lineage_mutated:false,reserve_mutated:false,round_index_mutated:false,surface_records_created:false,surface_aggregate_created:false,context_inputs_created:false,round_0002_replacements_created:false,round_0002_release_created:false,round_0003_created:false,formal_gemini_experiment_inference_calls_made:0,model_calls_started:0,network_calls_made:0};
    if(candidate.reviewed_gate_transition){
      let gate; try{gate=validateRound2RepairReviewGate(repo,JSON.parse(fs.readFileSync(queuePath)),candidate);}catch(error){return {decision:'NO_GO_ROUND_0002_SURFACE_INPUT_REVIEW_INVALID',...common,static_integrity:'FAIL_CLOSED',run_status:'ROUND_0002_SURFACE_INPUT_REVIEW_INVALID',surface_auditor_call_authorized:false,reason:error.message};}
      return {decision:'GO_ROUND_0002_SURFACE_AUDITOR_CALL_ONLY',...common,run_status:'ROUND_0002_SURFACE_INPUT_DUAL_PASS_AUDITOR_CALL_ONLY',surface_auditor_call_authorized:true,round_0002_surface_auditor_call_count_allowance:1,round_0002_surface_auditor_calls_started:0,round_0002_surface_auditor_calls_remaining:1,authorized_surface_auditor_call_number:1,review_gate_path:gate.path,review_gate_sha256:gate.sha256,auditor_contract:gate.auditor_contract,blockers:['SURFACE_RESPONSE_PERSISTENCE_NOT_AUTHORIZED_BY_THIS_GATE','SURFACE_RESULTS_MATERIALIZATION_NOT_AUTHORIZED','CONTEXT_NOT_AUTHORIZED','ROUND_0002_REPLACEMENT_RELEASE_NOT_AUTHORIZED','ROUND_0003_FORBIDDEN']};
    }
    return {decision:'NO_GO_ROUND_0002_SURFACE_INPUT_REVIEW_REQUIRED',...common,run_status:'ROUND_0002_SURFACE_INPUT_FROZEN_PENDING_INDEPENDENT_DUAL_REVIEW',surface_auditor_call_authorized:false,blockers:['NORMAL_REVIEW_REQUIRED','SENIOR_REVIEW_REQUIRED','COMBINED_SURFACE_INPUT_REVIEW_GATE_REQUIRED','SURFACE_AUDITOR_CALL_NOT_AUTHORIZED_BEFORE_GATE','ROUND_0002_RECORDS_AGGREGATE_CONTEXT_REPLACEMENT_RELEASE_FORBIDDEN','ROUND_0003_FORBIDDEN']};
  }
  return {decision: 'NO_GO_ROUND_0002_AUDIT_NOT_AUTHORIZED', static_integrity: 'PASS', run_status: releaseState.status, completed_rounds: 1, last_release_sha256: releaseState.last_release_sha256, audits_released: true, round_0002_audit_authorized: false, qualification_authorized: false, inference_authorized: false, authorized_surface_auditor_calls_started: 2, invalid_auditor_input_attempts: 1, valid_surface_auditor_responses: 1, valid_persisted_surface_results: 1, authorized_context_auditor_calls_started: 1, valid_context_auditor_responses: 1, valid_persisted_context_results: 1, formal_gemini_experiment_inference_calls_made: 0, network_calls_made: 0, blockers: ['ROUND_0002_AUDIT_NOT_AUTHORIZED']};
}
if (!pending) throw Error(`PENDING_RELEASE_REQUIRED_FOR_INCOMPLETE_STATE:${completedRounds}`);
const expectedPendingCompletedRounds = pending.round_id === 'ROUND-0002' ? 1 : 0;
if (completedRounds !== expectedPendingCompletedRounds) throw Error(`PENDING_RELEASE_COMPLETED_ROUND_MISMATCH:${completedRounds}`);
const experiment = JSON.parse(fs.readFileSync(path.join(root, 'EXPERIMENT.json'))), release = JSON.parse(fs.readFileSync(path.join(root, 'RELEASE-STATE.json')));
const expectedContextGate = {status: 'SATISFIED_FINAL_DUAL_PASS', record_path: pending.context_input_state.implementation_review_gate.record_path, record_sha256: pending.context_input_state.implementation_review_gate.record_sha256, reviewed_candidate_ref: 'f4cba464e366809479257be606e3acd3e058b488bcfc80fc8d1b2e16c5f3b408', reviewed_candidate_manifest_sha256: '8dd7579a704eeaa3c07e4f587aa47b32279274eacad22e1491280d61e3663137', normal_reviewer_agent_id: '94403f94-bcdd-45cd-926b-90a7233eb741', senior_reviewer_agent_id: '9480ec23-de89-4ed3-918a-dfa3958e55d6'};
const materialized = pending.context_results_state.records_materialized === true && pending.context_results_state.aggregate_materialized === true;
const expectedStatus = materialized ? 'CONTEXT_RESULTS_MATERIALIZED_PENDING_REPLACEMENT_RELEASE_AUTHORIZATION' : 'CONTEXT_RESULTS_DUAL_PASS_PENDING_MATERIALIZATION';
const expectedReviewStatus = 'SATISFIED_FINAL_DUAL_PASS';
const expectedResultsGate = {status: 'SATISFIED_FINAL_DUAL_PASS', record_path: pending.context_results_state.implementation_review_gate.record_path, record_sha256: pending.context_results_state.implementation_review_gate.record_sha256, reviewed_candidate_ref: '0185b8fc41e58e5a4ac1428a9d9b6ee946918c475f10162acf21bf53a50d1256', reviewed_candidate_manifest_sha256: 'b91626a3e1a2d6fac820a26615341598f5746d61fbf4c67343e73990ea28c0fc', normal_reviewer_agent_id: '94403f94-bcdd-45cd-926b-90a7233eb741', senior_reviewer_agent_id: '9480ec23-de89-4ed3-918a-dfa3958e55d6'};
if (experiment.status !== expectedStatus || JSON.stringify(experiment.context_input_review_gate) !== JSON.stringify(expectedContextGate) || JSON.stringify(experiment.context_results_review_gate) !== JSON.stringify(expectedResultsGate) || experiment.authorized_surface_auditor_calls_started !== 2 || experiment.authorized_context_auditor_calls_started !== 1 || experiment.invalid_auditor_input_attempts !== 1 || experiment.valid_surface_auditor_responses !== 1 || experiment.valid_persisted_surface_results !== 1 || experiment.valid_context_auditor_responses !== 1 || experiment.valid_persisted_context_results !== (materialized ? 1 : 0) || experiment.formal_gemini_experiment_inference_calls_made !== 0 || experiment.network_calls_made !== 0 || experiment.audits_released !== false || experiment.context_results_implementation_review_status !== expectedReviewStatus || experiment.context_records_materialized !== materialized || experiment.context_aggregate_materialized !== materialized || experiment.replacements_authorized !== false || experiment.release_authorized !== false || experiment.qualification_authorized !== false || experiment.inference_authorized !== false) throw Error('CONTEXT_RESULTS_EXPERIMENT_STATE');
if (release.schema_version !== 'gemini-context-v5-release-state-v2' || release.status !== expectedStatus || release.context_input_state?.implementation_review_gate?.status !== 'SATISFIED_FINAL_DUAL_PASS' || release.context_results_state?.implementation_review_gate?.status !== 'SATISFIED_FINAL_DUAL_PASS' || release.authorized_surface_auditor_calls_started !== 2 || release.authorized_context_auditor_calls_started !== 1 || release.invalid_auditor_input_attempts !== 1 || release.valid_surface_auditor_responses !== 1 || release.valid_persisted_surface_results !== 1 || release.valid_context_auditor_responses !== 1 || release.valid_persisted_context_results !== (materialized ? 1 : 0) || release.formal_gemini_experiment_inference_calls_made !== 0 || release.network_calls_made !== 0 || release.audits_released !== false || release.context_audit_authorized !== true || release.context_auditor_call_started !== true || release.context_records_materialized !== materialized || release.context_aggregate_materialized !== materialized || release.replacements_authorized !== false || release.release_authorized !== false || release.qualification_authorized !== false || release.inference_authorized !== false || release.sidecar_review_gate?.status !== 'SATISFIED_FINAL_DUAL_PASS' || release.completed_rounds !== 0 || release.last_release_sha256 !== null || release.completed_surface_stage_applied_to_active_state !== false || release.context_input_applied_to_active_state !== false || release.active_frame_mutated !== false || release.lineage_mutated !== false || release.reserve_mutated !== false || release.banned_revision_ids_added !== 0 || release.consumed_revision_ids_added !== 0) throw Error('PENDING_CONTEXT_RESULTS_RELEASE_STATE');
const response = experiment.validated_surface_response;
if (response?.artifact_path !== pending.validated_surface_response.artifact_path || response?.artifact_sha256 !== pending.validated_surface_response.artifact_sha256 || response?.artifact_schema_version !== pending.validated_surface_response.records_schema_version || response?.artifact_role !== pending.validated_surface_response.artifact_role || response?.non_regenerable !== true || response?.auditor_agent_id !== pending.validated_surface_response.auditor_agent_id || response?.authorized_call_number !== pending.validated_surface_response.authorized_call_number || response?.surface_queue_sha256 !== pending.surface_queue_sha256 || response?.surface_queue_view_sha256 !== pending.surface_queue_view_sha256 || response?.expected_surface_records_sha256 !== pending.validated_surface_response.expected_surface_records_sha256 || response?.expected_surface_aggregate_sha256 !== pending.validated_surface_response.expected_surface_aggregate_sha256) throw Error('EXPERIMENT_SURFACE_AUDITOR_RESPONSE_BINDING');
const contextResponse = experiment.validated_context_response;
if (contextResponse?.artifact_path !== pending.validated_context_response.artifact_path || contextResponse?.artifact_sha256 !== pending.validated_context_response.artifact_sha256 || contextResponse?.artifact_schema_version !== pending.validated_context_response.records_schema_version || contextResponse?.artifact_role !== pending.validated_context_response.artifact_role || contextResponse?.non_regenerable !== true || contextResponse?.auditor_agent_id !== pending.validated_context_response.auditor_agent_id || contextResponse?.authorized_call_number !== pending.validated_context_response.authorized_call_number || contextResponse?.context_queue_sha256 !== pending.validated_context_response.context_queue_sha256 || contextResponse?.context_source_anchors_sha256 !== pending.validated_context_response.context_source_anchors_sha256 || contextResponse?.context_queue_view_sha256 !== pending.validated_context_response.context_queue_view_sha256 || contextResponse?.expected_context_records_sha256 !== pending.validated_context_response.expected_context_records_sha256 || contextResponse?.expected_context_aggregate_sha256 !== pending.validated_context_response.expected_context_aggregate_sha256 || contextResponse?.item_count !== 55 || contextResponse?.clean_count !== 54 || contextResponse?.not_clean_count !== 1 || JSON.stringify(release.validated_context_response) !== JSON.stringify(pending.validated_context_response)) throw Error('EXPERIMENT_CONTEXT_AUDITOR_RESPONSE_BINDING');
if (JSON.stringify(experiment.implementation_candidate_binding) !== JSON.stringify(pending.implementation_candidate_binding) || JSON.stringify(release.implementation_candidate_binding) !== JSON.stringify(pending.implementation_candidate_binding) || JSON.stringify(release.validated_surface_response) !== JSON.stringify(pending.validated_surface_response)) throw Error('RELEASE_SURFACE_INTERMEDIATE_BINDING');
const queuePath = path.join(root, 'rounds', pending.round_id, 'CONTEXT-QUEUE.json'), anchorsPath=path.join(root,'rounds',pending.round_id,'CONTEXT-SOURCE-ANCHORS.json'), viewPath = path.join(root, 'rounds', pending.round_id, 'CONTEXT-QUEUE-VIEW.json');
const authorizationPath = path.join(repo, pending.authorization_record_path), authorizationBytes = fs.readFileSync(authorizationPath), authorization = JSON.parse(authorizationBytes);
if (sha256(authorizationBytes) !== pending.authorization_record_sha256 || authorization.authorization_id !== pending.authorization_id || authorization.status !== 'AUTHORIZED_QUEUE_FREEZE_PENDING_AUDITOR_OUTPUT' || authorization.authorized_candidate_ref !== pending.authorized_candidate_ref || authorization.required_final_pass_reviews?.normal?.agent_id !== pending.final_pass_reviewer_agent_ids.normal || authorization.required_final_pass_reviews?.normal?.status !== 'PASS' || authorization.required_final_pass_reviews?.senior?.agent_id !== pending.final_pass_reviewer_agent_ids.senior || authorization.required_final_pass_reviews?.senior?.status !== 'PASS' || authorization.transition_executor?.agent_id !== '87c413cc-b555-4659-b4b5-7eadb69636e2' || authorization.reviewed_implementation_attribution?.candidate_author_agent_id !== '193050c1-cfe9-436d-9027-1dd1228f6ebb' || authorization.reviewed_implementation_attribution?.unchanged !== true) throw Error('AUDIT_AUTHORIZATION_BINDING');
if (!fs.existsSync(queuePath) || !fs.existsSync(anchorsPath) || !fs.existsSync(viewPath)) throw Error('AUTHORIZED_CONTEXT_INPUT_MISSING');
const forbidden = fs.readdirSync(root).filter(name => /^(?:RAW-|REQUEST-|QUALIFICATION-|MUTATIONS|SEALED-REFERENCE-|AUDIT-AUTHORIZATION)/u.test(name));
if (forbidden.length) throw Error(`FORBIDDEN_DOWNSTREAM_ARTIFACTS:${forbidden.join(',')}`);
const common = {static_integrity: 'PASS', round_id: pending.round_id, stage: 'CONTEXT', queue_path: path.relative(root, queuePath), queue_sha256: pending.context_input_state.context_queue_sha256, source_anchors_path:path.relative(root,anchorsPath),source_anchors_sha256:pending.context_input_state.context_source_anchors_sha256,queue_view_path: path.relative(root, viewPath), queue_view_sha256: pending.context_input_state.context_queue_view_sha256, item_count: pending.context_input_state.item_count, surface_queue_sha256: pending.surface_queue_sha256, surface_queue_view_sha256: pending.surface_queue_view_sha256, surface_records_sha256: pending.validated_surface_response.expected_surface_records_sha256, surface_aggregate_sha256: pending.validated_surface_response.expected_surface_aggregate_sha256, completed_rounds: completedRounds, audits_released: false, active_frame_mutated: false, lineage_mutated: false, reserve_mutated: false, context_auditor_calls_started: experiment.context_auditor_calls_started, formal_gemini_experiment_inference_calls_made: experiment.formal_gemini_experiment_inference_calls_made, network_calls_made: experiment.network_calls_made};
if (!materialized) return {decision: 'GO_CONTEXT_RESULTS_MATERIALIZATION_ONLY', ...common, run_status: expectedStatus, context_results_materialization_authorized: true, durable_response_path: pending.validated_context_response.artifact_path, durable_response_sha256: pending.validated_context_response.artifact_sha256, verdict_counts: pending.validated_context_response.verdict_counts, expected_context_records_sha256: pending.validated_context_response.expected_context_records_sha256, expected_context_aggregate_sha256: pending.validated_context_response.expected_context_aggregate_sha256, context_records_materialized: false, context_aggregate_materialized: false, banned_revision_ids_added: 0, consumed_revision_ids_added: 0, blockers: ['MATERIALIZATION_ONLY', 'REPLACEMENTS_NOT_AUTHORIZED', 'RELEASE_NOT_AUTHORIZED', 'LATER_ROUNDS_NOT_AUTHORIZED']};
let releaseAuthorization; try { releaseAuthorization = validateReleaseImplementationAuthorization(repo); } catch (error) { return {decision: 'NO_GO_RELEASE_AUTHORIZATION_BINDING_INVALID', ...common, static_integrity: 'FAIL_CLOSED', run_status: 'RELEASE_AUTHORIZATION_INVALID', reason: error.code === 'ENOENT' ? 'RELEASE_AUTHORIZATION_MISSING' : error.message, context_records_materialized: true, context_aggregate_materialized: true, banned_revision_ids_added: 0, consumed_revision_ids_added: 0}; }
const implementationReview = evaluateReleaseImplementationReviewGate(repo);
const releaseBoundary = {...common, ...releaseAuthorization, context_results_materialization_authorized: false, replacement_release_implementation_authorized: true, verdict_counts: pending.validated_context_response.verdict_counts, context_records_sha256: pending.validated_context_response.expected_context_records_sha256, context_aggregate_sha256: pending.validated_context_response.expected_context_aggregate_sha256, context_records_materialized: true, context_aggregate_materialized: true, deterministic_rejected_slot_count: 10, banned_revision_ids_added: 0, consumed_revision_ids_added: 0};
if (implementationReview.invalid) return {decision: 'NO_GO_RELEASE_IMPLEMENTATION_REVIEW_INVALID', ...releaseBoundary, static_integrity: 'FAIL_CLOSED', run_status: 'ROUND_0001_RELEASE_IMPLEMENTATION_REVIEW_INVALID', real_release_materialization_authorized: false, reason: implementationReview.reason, blockers: ['IMPLEMENTATION_REVIEW_RECORD_INVALID', 'ROUND_0002_NOT_AUTHORIZED']};
if (!implementationReview.satisfied) return {decision: 'NO_GO_RELEASE_IMPLEMENTATION_REVIEW_REQUIRED', ...releaseBoundary, run_status: 'ROUND_0001_RELEASE_IMPLEMENTATION_REVIEW_REQUIRED', real_release_materialization_authorized: false, review_gate_reason: implementationReview.reason, candidate_ref: implementationReview.candidate_ref, candidate_manifest_sha256: implementationReview.candidate_manifest_sha256, blockers: ['NORMAL_REVIEW_REQUIRED', 'SENIOR_REVIEW_REQUIRED', 'COMBINED_RELEASE_REVIEW_GATE_REQUIRED', 'ROUND_0002_NOT_AUTHORIZED']};
return {decision: 'GO_ROUND_0001_RELEASE_MATERIALIZATION_ONLY', ...releaseBoundary, run_status: 'ROUND_0001_RELEASE_IMPLEMENTATION_DUAL_PASS', real_release_materialization_authorized: true, implementation_review_gate: readReleaseProvenanceReviewGate(repo), materialization_review_gate: implementationReview.provenance, blockers: ['MATERIALIZATION_ONLY', 'ROUND_0002_NOT_AUTHORIZED']};
}
if (import.meta.url === `file://${process.argv[1]}`) { const result = runPreflight(); console.log(JSON.stringify(result, null, 2)); process.exitCode = ['GO_CONTEXT_RESULTS_MATERIALIZATION_ONLY', 'GO_ROUND_0001_RELEASE_MATERIALIZATION_ONLY', 'GO_ROUND_0002_SURFACE_AUDITOR_CALL_ONLY'].includes(result.decision) ? 0 : 3; }
