import fs from'node:fs';import os from'node:os';import path from'node:path';import{spawnSync}from'node:child_process';import{readCanonical,shaFile,sha256,jsonBytes,writeExclusive}from'./lib.mjs';import{CELL_ORDER,factors,splitRequest}from'./freezer.mjs';import{validateGates}from'./gate-reader.mjs';import{derive,start,finish,append,prestartTerminal,pathsFor,rawValue,MAX_ATTEMPTS,PROCESS_BUDGET,CALL_BUDGET}from'./ledger.mjs';import{parseCapture}from'./parser.mjs';import{mechanicalMetrics}from'./metrics.mjs';import{runtimeChecks}from'./runtime-integrity.mjs';
const EXPECTED='/home/yun/.local/lib/agy-pinned/f3575050ae826d1944913f595b32f827a4674ec42e59ff0476450e2bac5fa39e/agy',HASH='f3575050ae826d1944913f595b32f827a4674ec42e59ff0476450e2bac5fa39e';
export function makePlan(root,cell,tempRoot){const entry=readCanonical(path.join(root,'frozen/REQUEST-MANIFEST.json')).requests.find(x=>x.cell===cell);if(!entry)throw Error('UNKNOWN_CELL');const requestBytes=fs.readFileSync(path.join(root,entry.path)),schemaBytes=fs.readFileSync(path.join(root,`model-facing/schemas/${entry.schema}.json`));if(sha256(requestBytes)!==entry.sha256||sha256(schemaBytes)!==entry.schema_sha256)throw Error('REQUEST_SCHEMA_DRIFT');const cwd=path.join(tempRoot,'cwd'),tmp=path.join(tempRoot,'tmp');fs.mkdirSync(cwd,{mode:0o700});fs.mkdirSync(tmp,{mode:0o700});fs.writeFileSync(path.join(cwd,'request.txt'),requestBytes,{mode:0o600,flag:'wx'});fs.writeFileSync(path.join(cwd,'schema.json'),schemaBytes,{mode:0o600,flag:'wx'});const route=readCanonical(path.join(root,'ROUTE-CONTRACT.json')),argv=route.cli_contract.argv_template.map(x=>x==='[REQUEST_BYTES]'?requestBytes.toString('utf8'):x==='[BUNDLE_SCHEMA]'?schemaBytes.toString('utf8'):x),env=Object.fromEntries(route.environment_allowlist.filter(k=>process.env[k]!==undefined).map(k=>[k,process.env[k]]));env.TMPDIR=tmp;return{entry,requestBytes,command:route.cli_contract.executable,argv,env,cwd,timeout_ms:route.cli_contract.timeout_ms};}
export function verifyRoute(root,p){const r=readCanonical(path.join(root,'ROUTE-CONTRACT.json')).cli_contract;if(r.executable!==EXPECTED||r.executable_sha256!==HASH||r.model!=='gemini-3.7-flash-high'||r.effort!=='high'||r.mode!=='plan'||p.command!==EXPECTED)throw Error('STOP_ROUTE_CONFIG');if(!fs.statSync(r.executable).isFile()||shaFile(r.executable)!==HASH)throw Error('STOP_ROUTE_EXECUTABLE');for(const[k,v]of[['--model',r.model],['--effort','high'],['--mode','plan'],['--output-format','json']]){const i=p.argv.indexOf(k);if(i<0||p.argv[i+1]!==v||p.argv.filter(x=>x===k).length!==1)throw Error(`STOP_ROUTE_ARGV:${k}`);}if(!p.argv.includes('--json-schema')||!p.argv.includes('--sandbox')||!p.argv.includes('--disable-slash-commands'))throw Error('STOP_ROUTE_REQUIRED_FLAGS');}
const invoke=p=>{const r=spawnSync(p.command,p.argv,{env:p.env,cwd:p.cwd,encoding:null,timeout:p.timeout_ms,maxBuffer:16*1024*1024});return{exit_code:Number.isInteger(r.status)?r.status:-1,stdout:Buffer.from(r.stdout??''),stderr:Buffer.from(r.stderr??''),timed_out:r.error?.code==='ETIMEDOUT',spawn_error:r.error?.message??null};};
export function runCell(root,repo,cell,systemInvoke=invoke){
 const integrity=runtimeChecks(root);if(integrity.length)throw Error(`STATIC:${integrity.join(',')}`);const gates=validateGates(root,repo);if(!gates.valid)throw Error(`GATES:${gates.errors.join(',')}`);const state=derive(root);if(state.errors.length)throw Error(`LEDGER:${state.errors.join(',')}`);if(MAX_ATTEMPTS!==1||state.agy_processes_spawned>=PROCESS_BUDGET||state.inference_calls_made>=CALL_BUDGET)throw Error('STOP_BUDGET');if(state.unfinished||state.terminal_failure)throw Error('STOP_PREVIOUS');if(cell!==CELL_ORDER[state.agy_processes_spawned]||state.cells[cell])throw Error('CELL_ORDER_ATTEMPT');const cp=pathsFor(cell);if(Object.values(cp).some(x=>fs.existsSync(path.join(root,x))))throw Error('DYNAMIC_COLLISION');
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),`gemini-holdout-${cell}-`));let began=false,s,plan,result={exit_code:-1,stdout:Buffer.alloc(0),stderr:Buffer.alloc(0),timed_out:false,spawn_error:null},parsed={valid:false,errors:['NOT_RUN'],normalized:null},postError=null,raw=null,metrics=null;
 try{
  try{plan=makePlan(root,cell,temp);verifyRoute(root,plan);}catch(e){prestartTerminal(root,cell,`ROUTE_OR_PLAN:${e.message}`);throw e;}
  s=start(cell,state);append(root,s);began=true;
  try{result=systemInvoke(plan)??result;}catch(e){postError=e;}result={exit_code:Number.isInteger(result.exit_code)?result.exit_code:-1,stdout:Buffer.from(result.stdout??''),stderr:Buffer.from(result.stderr??''),timed_out:!!result.timed_out,spawn_error:result.spawn_error??null};
  for(const[k,b]of[['stdout',result.stdout],['stderr',result.stderr]])try{writeExclusive(path.join(root,cp[k]),b);}catch(e){postError??=e;}
  const processOK=!postError&&!result.spawn_error&&result.exit_code===0&&!result.timed_out;if(processOK){parsed=parseCapture(result.stdout,splitRequest(plan.requestBytes).input,plan.entry.condition);if(parsed.valid)try{raw=rawValue(cell,plan.entry,parsed.normalized,parsed.envelope_metadata);writeExclusive(path.join(root,cp.raw),jsonBytes(raw));metrics=mechanicalMetrics(parsed.normalized,splitRequest(plan.requestBytes).input);}catch(e){postError??=e;parsed={valid:false,errors:[`RAW:${e.message}`],normalized:null};}}else parsed={valid:false,errors:[postError?`SPAWN:${postError.message}`:result.spawn_error?'SPAWN_ERROR':'PROCESS_FAILED'],normalized:null};
  const finalOK=!postError&&!result.spawn_error&&result.exit_code===0&&!result.timed_out;append(root,finish(s,{exit_code:result.exit_code,stdout_sha256:sha256(result.stdout),stderr_sha256:sha256(result.stderr),process_success:finalOK,payload_strict_valid:finalOK&&parsed.valid,raw_path:finalOK&&parsed.valid?cp.raw:null}));
 }finally{fs.rmSync(temp,{recursive:true,force:true});}
 if(!began)throw Error('START_NOT_REACHED');return{cell,attempt:1,process_success:!postError&&!result.spawn_error&&result.exit_code===0&&!result.timed_out,payload_strict_valid:parsed.valid,errors:parsed.errors,metrics,continue_authorized:!postError&&!result.spawn_error&&result.exit_code===0&&!result.timed_out&&parsed.valid};
}
