#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{readCanonical,jsonBytes,sha256,shaFile,writeExclusive}from'./lib.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
export const CELL='combined-p1-s2-a-network-retry-1';export const CELL_ORDER=[CELL];
export const REQUEST='model-facing/requests/combined-p1-s2-a-network-retry-1.txt';export const SCHEMA='model-facing/schemas/S2.json';
export const REQUEST_SHA256='46a6358dab506eca4f0a69b8af0232227da813bebed722173c9972a2d95eda99';export const REQUEST_BYTES=6958;export const SCHEMA_SHA256='1dce33b98f259190a73df85dca957feb7f73e93f62501f22c02e512ef3cfc138';
export function splitRequest(bytes){const text=Buffer.from(bytes).toString('utf8'),a=text.indexOf('\n\nINPUT JSON:\n'),b=text.indexOf('\n\nOUTPUT SCHEMA:\n');if(a<0||b<a)throw Error('REQUEST_FORMAT');return{prompt:text.slice(0,a),input:JSON.parse(text.slice(a+14,b)),schema:JSON.parse(text.slice(b+17))}}
export function build(root=here){const request=fs.readFileSync(path.join(root,REQUEST)),schema=fs.readFileSync(path.join(root,SCHEMA));if(request.length!==REQUEST_BYTES||sha256(request)!==REQUEST_SHA256)throw Error('COPIED_REQUEST_DRIFT');if(sha256(schema)!==SCHEMA_SHA256)throw Error('COPIED_SCHEMA_DRIFT');const q=splitRequest(request),schemaValue=readCanonical(path.join(root,SCHEMA));if(JSON.stringify(q.schema)!==JSON.stringify(schemaValue))throw Error('EMBEDDED_SCHEMA_DRIFT');if(!Array.isArray(q.input?.items)||q.input.items.length!==16||q.input.items.some((x,i)=>x.item_id!==`EC-I${String(i+1).padStart(3,'0')}`))throw Error('REQUEST_ITEMS');const manifest={schema_version:'evidence-contract-recovery-request-manifest-v1',fixed_order:CELL_ORDER,request:{cell:CELL,path:REQUEST,sha256:REQUEST_SHA256,utf8_bytes:REQUEST_BYTES,schema:SCHEMA,schema_sha256:SCHEMA_SHA256,item_ids:q.input.items.map(x=>x.item_id)}};return{request,schema,manifest}}
export function checkFreeze(root=here){const errors=[];let built;try{built=build(root)}catch(e){return{errors:[e.message],built:null}}const p=path.join(root,'frozen/REQUEST-MANIFEST.json'),expected=jsonBytes(built.manifest);if(!fs.existsSync(p))errors.push('MISSING:frozen/REQUEST-MANIFEST.json');else if(!fs.readFileSync(p).equals(expected))errors.push('DRIFT:frozen/REQUEST-MANIFEST.json');return{errors,built}}
export function freeze(root=here){const b=build(root),p=path.join(root,'frozen/REQUEST-MANIFEST.json'),bytes=jsonBytes(b.manifest);if(fs.existsSync(p)){if(!fs.readFileSync(p).equals(bytes))throw Error('FROZEN_DRIFT:frozen/REQUEST-MANIFEST.json')}else writeExclusive(p,bytes);return{items:b.manifest.request.item_ids.length,requests:1,request_bytes:REQUEST_BYTES,request_sha256:REQUEST_SHA256,schema_sha256:SCHEMA_SHA256}}
if(import.meta.url===`file://${process.argv[1]}`){try{if(process.argv[2]==='--check'){const x=checkFreeze();console.log(JSON.stringify({mode:'CHECK',errors:x.errors},null,2));process.exitCode=x.errors.length?3:0}else if(process.argv.length===2)console.log(JSON.stringify(freeze(),null,2));else{console.error('usage: node freezer.mjs [--check]');process.exitCode=2}}catch(e){console.error(e.message);process.exitCode=3}}
