#!/usr/bin/env node
import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';import{checkFreeze,build,CELL,REQUEST_SHA256,REQUEST_BYTES,SCHEMA_SHA256,splitRequest}from'../freezer.mjs';import{checkManifest}from'../build-manifest.mjs';import{preflight}from'../preflight.mjs';import{treeBinding,shaFile,jsonBytes,sha256}from'../lib.mjs';import{parseOutput,parseCapture}from'../parser.mjs';import{metrics}from'../metrics.mjs';import{derive,START_KEYS,FINISH_KEYS,MAX_ATTEMPTS}from'../ledger.mjs';import{runCell}from'../runner.mjs';import{postRun}from'../post-run.mjs';import{GATE_PATHS,TASK}from'../gates.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),repo=path.resolve(root,'../../../..'),pred='evidence/quality/model-probes/gemini-evaluator-evidence-contract-conformance-v1';
let tests=0;const test=(name,fn)=>{fn();tests++;console.log(`ok ${tests} - ${name}`)};
const before=treeBinding(repo,pred);
test('frozen copy and static manifest rebuild byte-identically',()=>{assert.deepEqual(checkFreeze(root).errors,[]);assert.deepEqual(checkManifest(root),[])});
test('request and schema are exact predecessor bytes with independent fixed hashes',()=>{const b=build(root),pr=fs.readFileSync(path.join(repo,pred,'model-facing/requests/combined-p1-s2-a.txt')),ps=fs.readFileSync(path.join(repo,pred,'model-facing/schemas/S2.json'));assert.ok(b.request.equals(pr));assert.ok(b.schema.equals(ps));assert.equal(b.request.length,REQUEST_BYTES);assert.equal(sha256(b.request),REQUEST_SHA256);assert.equal(sha256(b.schema),SCHEMA_SHA256)});
test('predecessor tree and result remain immutable',()=>{assert.equal(before.file_count,45);assert.equal(before.tree_sha256,'df8798c8c42315f1ded923c632084140738a5e1e52059e86f4abdc5d329a2dad');assert.equal(shaFile(path.join(repo,pred,'RESULT.json')),'cf06bc31ecafe9291806ebf7c08e6935c34386bac57af414753c861e749d653e')});
test('zero-state preflight is NO_RUN 0/0 and blocked only on read-only gates',()=>{const x=preflight(root,repo);assert.equal(x.decision,'NO_GO_REQUIRED_GATES');assert.equal(x.execution_state,'NO_RUN');assert.equal(x.static_integrity,'PASS');assert.equal(x.agy_processes_spawned,0);assert.equal(x.inference_calls_made,0);assert.equal(x.network_calls_made,0);assert.deepEqual(x.blocked_gates,['PACKAGE_REVIEW','EXECUTION_AUTHORIZATION'])});
const input=splitRequest(build(root).request).input,empty={items:input.items.map(x=>({item_id:x.item_id,candidates:[]}))};
test('parser accepts repaired evidence aliases and metrics retain membership and registered-name distinctions',()=>{const mk=(field,value)=>({items:input.items.map((x,i)=>({item_id:x.item_id,candidates:i?[]:[{verdict:'FINDING',claim_type:'OTHER',target_span:x.target.slice(0,1),correction:'修', [field]:value}]}))});const quote=mk('evidence_quote',input.items[0].source.slice(0,1)),alias=mk('evidence','not-a-member');const a=parseOutput(quote,input,'S2'),b=parseOutput(alias,input,'S2');assert.equal(a.valid,true);assert.equal(b.valid,true);const am=metrics(a.normalized,input),bm=metrics(b.normalized,input);assert.equal(am.evidence_membership_count,1);assert.equal(am.registered_field_name_count,1);assert.equal(bm.evidence_membership_count,0);assert.equal(bm.registered_field_name_count,0);assert.equal(bm.status,'DESCRIPTIVE')});
test('parser validates agy response alias and rejects duplicate keys',()=>{const good=Buffer.from(JSON.stringify({status:'SUCCESS',response:JSON.stringify(empty)}));assert.equal(parseCapture(good,input,'S2').valid,true);assert.equal(parseCapture(Buffer.from('{"status":"SUCCESS","status":"SUCCESS","structured_output":{"items":[]}}'),input,'S2').valid,false)});
test('ledger contract has exact keys, one attempt, and FINISH requirement',()=>{assert.equal(MAX_ATTEMPTS,1);assert.deepEqual(START_KEYS,['event','cell','attempt','started_at']);assert.deepEqual(FINISH_KEYS,['event','cell','attempt','started_at','finished_at','exit_code','stdout_sha256','stderr_sha256','process_success','envelope_schema_valid','raw_path'])});
function fixture(){const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-recovery-test-')),pkg=path.join(tmp,'evidence/quality/model-probes/gemini-evaluator-evidence-contract-conformance-v1-network-recovery-v1'),predCopy=path.join(tmp,pred);fs.mkdirSync(path.dirname(pkg),{recursive:true});fs.cpSync(root,pkg,{recursive:true});fs.cpSync(path.join(repo,pred),predCopy,{recursive:true});fs.rmSync(path.join(pkg,'execution'),{recursive:true,force:true});fs.rmSync(path.join(pkg,'RESULT.json'),{force:true});const gateDir=path.join(tmp,'.ai/task',TASK);fs.mkdirSync(gateDir,{recursive:true});const manifest=shaFile(path.join(pkg,'MANIFEST.json')),review={schema_version:'evidence-contract-package-review-v1',task_id:TASK,decision:'PASS',manifest_sha256:manifest,authorized_cells:[CELL]};fs.writeFileSync(path.join(tmp,GATE_PATHS.PACKAGE_REVIEW),jsonBytes(review));const authorization={schema_version:'evidence-contract-execution-authorization-v1',task_id:TASK,decision:'AUTHORIZED',manifest_sha256:manifest,package_review_sha256:shaFile(path.join(tmp,GATE_PATHS.PACKAGE_REVIEW)),authorized_cells:[CELL],agy_process_budget:1,inference_call_budget:1,max_attempts:1,retries:0,context_cell_authorized:false};fs.writeFileSync(path.join(tmp,GATE_PATHS.EXECUTION_AUTHORIZATION),jsonBytes(authorization));return{tmp,pkg,gateHashes:[shaFile(path.join(tmp,GATE_PATHS.PACKAGE_REVIEW)),shaFile(path.join(tmp,GATE_PATHS.EXECUTION_AUTHORIZATION))]}}
test('mocked valid execution has one-spawn ceiling, exact FINISH ledger, read-only gates, and cleanup',()=>{const f=fixture();let calls=0;try{const stdout=Buffer.from(JSON.stringify({status:'SUCCESS',structured_output:empty}));const r=runCell(f.pkg,f.tmp,CELL,()=>{calls++;return{exit_code:0,stdout,stderr:Buffer.alloc(0),timed_out:false}});assert.equal(r.envelope_schema_valid,true);assert.equal(calls,1);assert.throws(()=>runCell(f.pkg,f.tmp,CELL,()=>{calls++;throw Error('must not spawn')}),/STOP_BUDGET/);assert.equal(calls,1);const d=derive(f.pkg);assert.equal(d.rows.length,2);assert.deepEqual(Object.keys(d.rows[0]).sort(),[...START_KEYS].sort());assert.deepEqual(Object.keys(d.rows[1]).sort(),[...FINISH_KEYS].sort());assert.equal(d.rows[1].event,'FINISH');const result=postRun(f.pkg,f.tmp),again=postRun(f.pkg,f.tmp);assert.deepEqual(result,again);assert.equal(result.decision,'DESCRIPTIVE_RECOVERY_COMPLETE');assert.equal(result.effectiveness_evidence,false);assert.deepEqual(f.gateHashes,[shaFile(path.join(f.tmp,GATE_PATHS.PACKAGE_REVIEW)),shaFile(path.join(f.tmp,GATE_PATHS.EXECUTION_AUTHORIZATION))])}finally{fs.rmSync(f.tmp,{recursive:true,force:true})}assert.equal(fs.existsSync(f.tmp),false)});
test('malformed response consumes sole attempt with no retry or RAW',()=>{const f=fixture();let calls=0;try{const r=runCell(f.pkg,f.tmp,CELL,()=>{calls++;return{exit_code:0,stdout:Buffer.from('{}'),stderr:Buffer.alloc(0),timed_out:false}});assert.equal(r.envelope_schema_valid,false);assert.equal(calls,1);assert.equal(fs.existsSync(path.join(f.pkg,'execution/RAW',`${CELL}.json`)),false);assert.throws(()=>runCell(f.pkg,f.tmp,CELL,()=>{calls++;return{}}),/STOP_BUDGET/);assert.equal(calls,1);assert.equal(derive(f.pkg).rows.at(-1).event,'FINISH')}finally{fs.rmSync(f.tmp,{recursive:true,force:true})}assert.equal(fs.existsSync(f.tmp),false)});
test('tests do not change predecessor',()=>{assert.deepEqual(treeBinding(repo,pred),before)});
console.log(`1..${tests}`);
