import{sha256,normalize,byteCompare}from'./lib.mjs';
const seed='gemini-context-counterexample-reviewer-v4/assignment/v4',half={CONTEXT_MUTANT:12,SURFACE_MUTANT:8,CLEAN_CONTROL:12};
function uniqueMap(items,key,label){const m=new Map();for(const x of items??[]){if(m.has(x[key]))throw Error(`${label}: duplicate ${x[key]}`);m.set(x[key],x)}return m}
export function computeAssignment({clean,mutations,checks,bindings,targets,packets}){
  if(clean.items?.length!==64||mutations.items?.length!==40||checks.items?.length!==40)throw Error('assignment input shortfall');
  const bm=uniqueMap(bindings.items,'neutral_id','bindings'),tm=uniqueMap(targets.items,'neutral_id','targets'),pm=uniqueMap(packets.items,'neutral_id','packets'),mm=uniqueMap(mutations.items,'neutral_id','mutations'),cm=uniqueMap(checks.items,'neutral_id','checks');
  const rows=clean.items.map(x=>{const b=bm.get(x.neutral_id),t=tm.get(x.neutral_id),p=pm.get(x.neutral_id),m=mm.get(x.neutral_id),check=cm.get(x.neutral_id);if(x.verdict!=='CLEAN_NO_MATERIAL_DEFECT'||x.direct_source_verified!==true||!b||!t||!p)throw Error(`${x.neutral_id}: clean/source/task binding`);if(!['discovery','confirmation'].includes(b.cohort)||!['dialogue','narrative'].includes(b.profile))throw Error(`${x.neutral_id}: frozen cohort/profile`);if((b.cohort==='discovery'&&!/^V4-D-/u.test(x.neutral_id))||(b.cohort==='confirmation'&&!/^V4-C-/u.test(x.neutral_id)))throw Error(`${x.neutral_id}: cohort identity drift`);if(x.source_artifact_sha256!==b.source_artifact_sha256||x.context_sha256!==b.context_sha256)throw Error(`${x.neutral_id}: audit lineage`);let role='CLEAN_CONTROL',target=t.target;if(m){role=m.kind==='CONTEXT_REQUIRED'?'CONTEXT_MUTANT':m.kind==='SURFACE_VISIBLE'?'SURFACE_MUTANT':null;if(!role||m.clean_target_sha256!==t.target_sha256||!check?.pass||check.neutral_id!==m.neutral_id||check.one_atom!==true||check.minimal_unique_edit!==true||(m.kind==='CONTEXT_REQUIRED'&&(check.surface_only!=='UNDERDETERMINED'||check.with_context!=='UNIQUELY_REFUTED'))||(m.kind==='SURFACE_VISIBLE'&&(check.surface_only!=='OBJECTIVELY_DETECTABLE'||check.with_context!=='NOT_APPLICABLE')))throw Error(`${x.neutral_id}: mutation/check binding`);const at=t.target.indexOf(m.edit_original);if(at<0||at!==t.target.lastIndexOf(m.edit_original)||`${t.target.slice(0,at)}${m.edit_mutated}${t.target.slice(at+m.edit_original.length)}`!==m.mutated_target)throw Error(`${x.neutral_id}: mutation target binding`);target=m.mutated_target}return{base_id:x.neutral_id,role,b,source:t.source,target,source_context:p.source_context}});
  if(new Set(rows.map(x=>x.b.revision_id)).size!==64||new Set(rows.map(x=>x.b.revision_uid)).size!==64||new Set(rows.map(x=>normalize(x.source))).size!==64||new Set(rows.map(x=>sha256(normalize(x.source_context)))).size!==64)throw Error('input row uniqueness');
  function sample(cohort){const xs=rows.filter(x=>x.b.cohort===cohort);if(xs.length!==32)throw Error(`${cohort}: frozen cohort count`);for(const profile of['dialogue','narrative'])if(xs.filter(x=>x.b.profile===profile).length!==16)throw Error(`${cohort}: ${profile} profile quota`);for(const[role,n]of Object.entries(half))if(xs.filter(x=>x.role===role).length!==n)throw Error(`${cohort}: ${role} quota`);const phase=cohort;return{schema_version:'gemini-context-sample-v4',phase,assignment_seed:seed,items:[...xs].sort((a,b)=>byteCompare(sha256(`${seed}\0${phase}\0${a.base_id}`),sha256(`${seed}\0${phase}\0${b.base_id}`))||byteCompare(a.base_id,b.base_id)).map((x,i)=>({global_item_id:`${phase==='discovery'?'D':'C'}-I${String(i+1).padStart(3,'0')}`,base_id:x.base_id,role:x.role,source:x.source,target:x.target,source_context:x.source_context}))}}
  return{discovery:sample('discovery'),confirmation:sample('confirmation'),search_nodes:0,search_budget:0};
}
