#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {readJson, shaFile, walkFiles, manifestRoot, dynamicArtifact, downstreamArtifactPath} from './lib.mjs';

const here=path.dirname(fileURLToPath(import.meta.url)), dir=process.env.V4_PREFLIGHT_DIR||here, errors=[];
const get=n=>readJson(path.join(dir,n));
try {
  const a=get('AVAILABILITY.json'), s=get('SOURCE-FRAME.json'), r=get('RANKED-SAME-PROFILE-RESERVE.json'), e=get('EXPERIMENT.json'), l=get('LOCAL-BINDINGS.json'), t=get('TARGET-BINDINGS.json'), p=get('SOURCE-PACKETS.json'), ledger=get('REPLACEMENT-LEDGER.json'), initial=get('FROZEN-RANKED-64-FRAME.json');
  if(a.eligible_dialogue_rows!==927||a.eligible_narrative_rows!==309||a.capped_dialogue_rows!==265||a.capped_narrative_rows!==110)errors.push('ELIGIBLE_OR_CAPPED_COUNT');
  if(a.selected_bases!==64||s.items?.length!==64||l.items?.length!==64||t.items?.length!==64||p.items?.length!==64)errors.push('SELECTION_COUNT');
  const selectedProfiles=Object.fromEntries(['dialogue','narrative'].map(x=>[x,s.items.filter(y=>y.profile===x).length]));
  const reserveProfiles=Object.fromEntries(['dialogue','narrative'].map(x=>[x,r.items.filter(y=>y.profile===x).length]));
  if(selectedProfiles.dialogue!==32||selectedProfiles.narrative!==32||reserveProfiles.dialogue!==a.reserve_dialogue_rows||reserveProfiles.narrative!==a.reserve_narrative_rows)errors.push('PROFILE_COUNT');
  if(a.reserve_bases!==r.items.length||a.reserve_bases!==a.reserve_dialogue_rows+a.reserve_narrative_rows||a.initial_reserve_bases!==a.reserve_bases+ledger.items.length+a.globally_banned_reserve_rows||ledger.initial_narrative_reserve_rows!==a.initial_narrative_reserve_rows||ledger.globally_banned_narrative_reserve_rows!==a.globally_banned_narrative_reserve_rows||ledger.consumed_narrative_replacements!==a.consumed_narrative_replacements||ledger.remaining_narrative_rejection_tolerance!==a.remaining_narrative_rejection_tolerance)errors.push('RESERVE_LEDGER_COUNT');
  if(a.initial_narrative_reserve_rows< a.narrative_reserve_target)errors.push('INITIAL_NARRATIVE_RESERVE_TARGET');
  const successfulNarrative=ledger.items.filter(x=>x.profile==='narrative').length;
  if(a.initial_consumed_narrative_replacements!==0||a.consumed_narrative_replacements!==successfulNarrative||e.consumed_narrative_replacements!==successfulNarrative)errors.push('NARRATIVE_CONSUMPTION_COUNT');
  const bannedReserve=a.globally_banned_narrative_reserve_rows;
  if(!Number.isInteger(bannedReserve)||bannedReserve<0||bannedReserve>a.globally_banned_reserve_rows||a.remaining_narrative_rejection_tolerance!==a.initial_narrative_reserve_rows-successfulNarrative-bannedReserve||a.remaining_narrative_rejection_tolerance!==a.reserve_narrative_rows||e.remaining_narrative_rejection_tolerance!==a.remaining_narrative_rejection_tolerance)errors.push('NARRATIVE_RESERVE_ACCOUNTING');
  if(e.selected_bases!==a.selected_bases||e.reserve_bases!==a.reserve_bases||e.reserve_narrative_rows!==a.reserve_narrative_rows||e.globally_banned_reserve_rows!==a.globally_banned_reserve_rows||e.initial_narrative_reserve_rows!==a.initial_narrative_reserve_rows||e.consumed_narrative_replacements!==a.consumed_narrative_replacements||e.remaining_narrative_rejection_tolerance!==a.remaining_narrative_rejection_tolerance)errors.push('EXPERIMENT_COUNTERS');
  const frameIds=s.items.map(x=>x.neutral_id), initialIds=initial.items.map(x=>x.neutral_id);
  if(JSON.stringify(frameIds)!==JSON.stringify(initialIds))errors.push('FRAME_SLOT_ORDER');
  const ledgerBy=new Map();for(const x of ledger.items??[]){if(ledgerBy.has(x.neutral_id))errors.push(`LEDGER_DUPLICATE:${x.neutral_id}`);ledgerBy.set(x.neutral_id,x)}
  for(let i=0;i<64;i++){const base=initial.items[i], current=s.items[i], changed=base.revision_id!==current.revision_id;if(changed){const x=ledgerBy.get(base.neutral_id);if(!x||x.rejected_revision_id!==base.revision_id||x.replacement_revision_id!==current.revision_id||x.replacement_file!==current.public_source_file)errors.push(`FRAME_REPLACEMENT_BINDING:${base.neutral_id}`)}else if(ledgerBy.has(base.neutral_id))errors.push(`LEDGER_UNCHANGED_SLOT:${base.neutral_id}`)}
  if(ledgerBy.size!==s.items.filter((x,i)=>x.revision_id!==initial.items[i]?.revision_id).length)errors.push('LEDGER_CHANGED_SLOT_COUNT');
  if(new Set(initial.items.map(x=>x.revision_id)).size!==64)errors.push('INITIAL_FRAME_DRIFT');
  for(const [name,rows] of [['LOCAL-BINDINGS.json',l.items],['TARGET-BINDINGS.json',t.items],['SOURCE-PACKETS.json',p.items]]){if(JSON.stringify(rows.map(x=>x.neutral_id))!==JSON.stringify(frameIds))errors.push(`FRAME_BINDING_ORDER:${name}`);for(let i=0;i<64;i++){if(rows[i]?.revision_id&&rows[i].revision_id!==s.items[i].revision_id)errors.push(`FRAME_BINDING_REVISION:${name}:${frameIds[i]}`);if(name==='TARGET-BINDINGS.json'&&(rows[i]?.source_sha256!==s.items[i]?.source_sha256||rows[i]?.target_sha256!==s.items[i]?.target_sha256))errors.push(`FRAME_BINDING_HASH:${name}:${frameIds[i]}`);if(name==='SOURCE-PACKETS.json'&&(rows[i]?.source_sha256!==s.items[i]?.source_sha256||rows[i]?.context_sha256!==s.items[i]?.context_sha256))errors.push(`FRAME_BINDING_HASH:${name}:${frameIds[i]}`)}}
  for(const [name,rows] of [['SURFACE-AUDIT-QUEUE.json',get('SURFACE-AUDIT-QUEUE.json').items],['CONTEXT-AUDIT-QUEUE.json',get('CONTEXT-AUDIT-QUEUE.json').items]])if(JSON.stringify(rows.map(x=>x.neutral_id))!==JSON.stringify(frameIds))errors.push(`FRAME_BINDING_ORDER:${name}`);
  const slots=[['LOCAL-BINDINGS.json',l.items],['TARGET-BINDINGS.json',t.items],['SOURCE-PACKETS.json',p.items],['SURFACE-AUDIT-QUEUE.json',get('SURFACE-AUDIT-QUEUE.json').items],['CONTEXT-AUDIT-QUEUE.json',get('CONTEXT-AUDIT-QUEUE.json').items]];
  for(const[name,rows]of slots)for(let i=0;i<64;i++){const a=s.items[i],b=rows[i]??{};for(const k of ['neutral_id','cohort','profile','revision_id','revision_uid','public_source_file','source_artifact_sha256','source_sha256','target_sha256','normalized_source_sha256','context_sha256','selection_context_sha256','occurrence'])if(Object.hasOwn(b,k)&&JSON.stringify(b[k])!==JSON.stringify(a[k]))errors.push(`SLOT_BINDING:${name}:${i}:${k}`);if(name==='TARGET-BINDINGS.json'&&(b.source_sha256!==a.source_sha256||b.target_sha256!==a.target_sha256))errors.push(`SLOT_BINDING:${name}:${i}:TEXT`)}
  const cq=get('CONTEXT-AUDIT-QUEUE.json');if(cq.context_queue_sha256&&cq.context_queue_sha256!==shaFile(path.join(dir,'CONTEXT-AUDIT-QUEUE.json')))errors.push('CONTEXT_QUEUE_HASH');
  for(const key of['revision_id','revision_uid','normalized_source_sha256','context_sha256'])if(new Set(s.items.map(x=>x[key])).size!==64)errors.push(`ROW_UNIQUENESS:${key}`);
  for(const profile of['dialogue','narrative']){const rows=s.items.filter(x=>x.profile===profile);for(const file of new Set(rows.map(x=>x.public_source_file))){if(rows.filter(x=>x.public_source_file===file).length>3)errors.push(`FILE_CAP:${profile}:${file}`);for(const cohort of['discovery','confirmation'])if(rows.filter(x=>x.public_source_file===file&&x.cohort===cohort).length>2)errors.push(`COHORT_FILE_CAP:${profile}:${cohort}:${file}`)}}
  for(const cohort of['discovery','confirmation'])for(const profile of['dialogue','narrative'])if(s.items.filter(x=>x.cohort===cohort&&x.profile===profile).length!==16)errors.push(`QUOTA:${cohort}:${profile}`);
  if(p.items.some(x=>x.source_match_count!==1||(x.source_context.match(/\[\[SOURCE_MATCH_1\]\]/gu)||[]).length!==1))errors.push('SOURCE_BINDING');
  if(e.model_calls_made!==0||e.network_calls_made!==0||e.inference_authorized!==false||e.qualification_authorized!==false)errors.push('ZERO_CALL_STATE');
} catch(x){errors.push(`STATIC:${x.message}`)}
try{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'v4-rebuild-')),frozen=['REJECTED-BASES-INPUT.json','EXPERIMENT.json','INVENTORY-PROVENANCE.json','FROZEN-RANKED-64-FRAME.json','RANKED-SAME-PROFILE-RESERVE.json','REPLACEMENT-LEDGER.json','SOURCE-FRAME.json','LOCAL-BINDINGS.json','TARGET-BINDINGS.json','SOURCE-PACKETS.json','AVAILABILITY.json','SURFACE-AUDIT-QUEUE.json','CONTEXT-AUDIT-QUEUE.json'];for(const n of frozen)fs.copyFileSync(path.join(dir,n),path.join(tmp,n));const r=spawnSync(process.execPath,[path.join(here,'select-and-freeze.mjs'),'--check'],{env:{...process.env,V4_OUTPUT_DIR:tmp},encoding:'utf8'});if(r.status!==0)errors.push(`DETERMINISTIC_REBUILD:${(r.stderr||r.stdout||'failed').trim().slice(0,240)}`);for(const n of frozen)if(!fs.readFileSync(path.join(tmp,n)).equals(fs.readFileSync(path.join(dir,n))))errors.push(`DETERMINISTIC_REBUILD:${n}`);fs.rmSync(tmp,{recursive:true,force:true})}catch(x){errors.push(`DETERMINISTIC_REBUILD:${x.message}`)}
try{const d=get('HASH-DAG.json'),names=walkFiles(dir).filter(n=>!dynamicArtifact(n));if(manifestRoot(d.files??{})!==d.candidate_root_sha256||names.some(n=>!Object.hasOwn(d.files??{},n))||Object.keys(d.files??{}).some(n=>!names.includes(n)))errors.push('HASH_DAG_COMPLETENESS');for(const[n,h]of Object.entries(d.files??{}))if(shaFile(path.join(dir,n))!==h)errors.push(`HASH_DRIFT:${n}`)}catch(x){errors.push(`HASH_DAG:${x.message}`)}
for(const n of walkFiles(dir))if(downstreamArtifactPath(n))errors.push(`DOWNSTREAM_ARTIFACT:${n}`);
const blockers=['INDEPENDENT_REVIEWS','SURFACE_AUDIT_RELEASE','CONTEXT_AUDIT_RELEASE','MUTATION_AND_MANIPULATION','SEALED_REFERENCES','COHORT_ROLE_ASSIGNMENT','ROUTE_QUALIFICATION','PHASE_REQUEST_AND_RAW_MANIFESTS','EXECUTION_AUTHORIZATION','POST_RUN_VALIDATION'];
console.log(JSON.stringify({schema_version:'gemini-context-v4-preflight-v2',status:'NO_GO',static_integrity:errors.length?'FAIL':'PASS',errors,blocking_gates:blockers,inference_allowed:false},null,2));
process.exitCode=errors.length?2:3;
