import fs from'node:fs';import os from'node:os';import path from'node:path';import{spawnSync}from'node:child_process';
export const ALLOW_ENV=['PATH','LANG','LC_ALL','LC_CTYPE','TZ','TERM','SSL_CERT_FILE','SSL_CERT_DIR','HTTPS_PROXY','HTTP_PROXY','ALL_PROXY','NO_PROXY'];
export function envPolicy(){const e={};for(const k of ALLOW_ENV)if(typeof process.env[k]==='string')e[k]=process.env[k];return{...e,PATH:`/tmp/route-runtime/bin:${e.PATH??'/usr/local/bin:/usr/bin:/bin'}`,HOME:'/tmp/route-runtime/home',TMPDIR:'/tmp/route-runtime/tmp',XDG_CONFIG_HOME:'/tmp/route-runtime/home/.config',XDG_CACHE_HOME:'/tmp/route-runtime/home/.cache',NO_COLOR:'1'}}
function exe(name){for(const d of(process.env.PATH??'').split(path.delimiter)){const p=path.join(d,name);try{if(fs.statSync(p).isFile())return fs.realpathSync(p)}catch{}}throw Error(`${name} unavailable`)}
export function makeRuntime(){const r=fs.mkdtempSync(path.join(os.tmpdir(),'gccr-runtime-'));for(const d of['home','tmp','bin'])fs.mkdirSync(path.join(r,d),{mode:0o700});const src=path.join(os.homedir(),'.gemini','antigravity-cli','antigravity-oauth-token'),dst=path.join(r,'home','.gemini','antigravity-cli','antigravity-oauth-token'),st=fs.lstatSync(src);if(!st.isFile()||st.isSymbolicLink())throw Error('unsafe/missing route authorization');fs.mkdirSync(path.dirname(dst),{recursive:true,mode:0o700});fs.copyFileSync(src,dst,fs.constants.COPYFILE_EXCL);fs.chmodSync(dst,0o600);fs.writeFileSync(path.join(r,'bin','agy'),'');return r}
export function bwrapPlan(bundle,runtime,args){return{command:'bwrap',args:['--die-with-parent','--new-session','--cap-drop','ALL','--ro-bind','/','/','--dev','/dev','--proc','/proc','--tmpfs',os.homedir(),'--ro-bind',bundle,'/mnt','--tmpfs','/tmp','--dir','/tmp/route-runtime','--bind',runtime,'/tmp/route-runtime','--ro-bind',exe('agy'),'/tmp/route-runtime/bin/agy','--chdir','/mnt','--','agy',...args]}}
export function invoke(bundle,runtime,args,timeout=30*60*1000){const p=bwrapPlan(bundle,runtime,args);return spawnSync(p.command,p.args,{cwd:'/tmp',env:envPolicy(),encoding:'utf8',maxBuffer:128*1024*1024,timeout})}
export function invokeBytes(bundle,runtime,args,timeout=120000){const p=bwrapPlan(bundle,runtime,args);return spawnSync(p.command,p.args,{cwd:'/tmp',env:envPolicy(),maxBuffer:128*1024*1024,timeout})}
export function cleanup(p,prefix){if(path.dirname(p)!==os.tmpdir()||!path.basename(p).startsWith(prefix))throw Error('unsafe cleanup');fs.rmSync(p,{recursive:true})}
export function agyArgs(request){return['-p',request,'--model','gemini-3.7-flash-high','--effort','high','--disable-slash-commands','--output-format','json','--print-timeout','25m','--mode','plan','--sandbox','--json-schema','/mnt/REVIEWER-SCHEMA.json']}
