#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readJson,shaFile,walkFiles,manifestRoot,dynamicArtifact} from './lib.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
const errors=[];
try{const a=readJson(path.join(here,'AVAILABILITY.json')),s=readJson(path.join(here,'SOURCE-FRAME.json')),r=readJson(path.join(here,'RANKED-SAME-PROFILE-RESERVE.json')),e=readJson(path.join(here,'EXPERIMENT.json')),l=readJson(path.join(here,'LOCAL-BINDINGS.json')),t=readJson(path.join(here,'TARGET-BINDINGS.json')),p=readJson(path.join(here,'SOURCE-PACKETS.json'));if(a.selected_bases!==64||s.items?.length!==64||l.items?.length!==64||t.items?.length!==64||p.items?.length!==64)errors.push('SELECTION_COUNT');if(r.items?.length!==a.reserve_bases||r.items?.length!==e.reserve_bases||r.items?.length<2)errors.push('RESERVE_COUNT');const q=x=>new Set(x);if(q(s.items.map(x=>x.public_source_file)).size!==64||q(s.items.map(x=>x.revision_id)).size!==64||q(s.items.map(x=>x.revision_uid)).size!==64||q(s.items.map(x=>x.normalized_source_sha256)).size!==64||q(s.items.map(x=>x.context_sha256)).size!==64||s.items.some(x=>x.inventory_occurrence_count!==1))errors.push('SELECTION_DISJOINTNESS');if(r.items.some(x=>q(s.items.map(y=>y.public_source_file)).has(x.public_source_file)))errors.push('RESERVE_OVERLAP');for(const cohort of['discovery','confirmation'])for(const profile of['dialogue','narrative'])if(s.items.filter(x=>x.cohort===cohort&&x.profile===profile).length!==16)errors.push(`QUOTA:${cohort}:${profile}`);if(p.items.some(x=>x.source_match_count!==1||!x.occurrence?.public_source_file||!Number.isInteger(x.occurrence?.line)||!x.occurrence?.construct||(x.source_context.match(/\[\[SOURCE_MATCH_1\]\]/gu)||[]).length!==1))errors.push('SOURCE_MATCH');}catch(e){errors.push(`STATIC:${e.message}`)}
try{const dag=readJson(path.join(here,'HASH-DAG.json')),immutable=walkFiles(here).filter(n=>!dynamicArtifact(n));if(manifestRoot(dag.files??{})!==dag.candidate_root_sha256||immutable.some(n=>!Object.hasOwn(dag.files??{},n))||Object.keys(dag.files??{}).some(n=>!immutable.includes(n)))errors.push('HASH_DAG_COMPLETENESS');for(const[n,h]of Object.entries(dag.files??{}))if(shaFile(path.join(here,n))!==h)errors.push(`HASH_DRIFT:${n}`)}catch(e){errors.push(`HASH_DAG:${e.message}`)}
for(const rel of walkFiles(here).filter(x=>/^REQUEST-.*\.txt$/u.test(x))){const text=fs.readFileSync(path.join(here,rel),'utf8');if(/(?:\/home\/|\/Users\/|sealed.reference|defect.id|api[_-]?key|BEGIN .*PRIVATE KEY)/iu.test(text))errors.push(`REQUEST_SANITATION:${rel}`)}
const blockers=['SURFACE_AUDIT_INCOMPLETE','CONTEXT_AUDIT_INCOMPLETE','MUTATIONS_INCOMPLETE','REFERENCES_INCOMPLETE','ASSIGNMENT_INCOMPLETE','INDEPENDENT_REVIEWS_INCOMPLETE','ROUTE_QUALIFICATION_INCOMPLETE','EXECUTION_AUTHORIZATION_MISSING'];
console.log(JSON.stringify({schema_version:'gemini-context-v2-preflight-v1',status:'NO_GO',static_integrity:errors.length?'FAIL':'PASS',errors,blocking_gates:blockers,inference_allowed:false},null,2));
process.exitCode=errors.length?2:3;
