"""Deterministic full-locale and addon-delta builders."""

from __future__ import annotations

import hashlib
from collections import defaultdict
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

from .config import ComponentSpec, Manifest
from .errors import ValidationError
from .git_source import GitRepository
from .locale_model import LocaleDocument, LocaleLoader, runtime_map
from .report import atomic_write_bytes, create_run_directory, write_json
from .semantics import runtime_semantic_signature


def _lua_string(value: str) -> str:
    if "\n" in value and not value.startswith("\n"):
        equals = ""
        while f"]{equals}]" in value:
            equals += "="
        return f"[{equals}[{value}]{equals}]"
    escaped: list[str] = ['"']
    escapes = {
        "\\": "\\\\",
        '"': '\\"',
        "\a": "\\a",
        "\b": "\\b",
        "\f": "\\f",
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
        "\v": "\\v",
    }
    for character in value:
        if character in escapes:
            escaped.append(escapes[character])
        elif ord(character) < 32 or ord(character) == 127:
            escaped.append(f"\\{ord(character):03d}")
        else:
            escaped.append(character)
    escaped.append('"')
    return "".join(escaped)


def _lua_value(value: Any) -> str:
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not value.is_integer():
            return repr(value)
        return str(int(value))
    if isinstance(value, str):
        return _lua_string(value)
    if isinstance(value, list):
        return "{" + ", ".join(_lua_value(item) for item in value) + "}"
    if isinstance(value, dict):
        fields: list[str] = []
        for key in sorted(value):
            if not isinstance(key, str):
                raise ValidationError("cannot render a Lua table with a non-string key")
            fields.append(f"[{_lua_string(key)}] = {_lua_value(value[key])}")
        return "{" + ", ".join(fields) + "}"
    raise ValidationError(f"cannot render Lua value of type {type(value).__name__}")


def _render_translation(entry: dict[str, Any]) -> str:
    values: list[Any] = [entry["source"], entry["target"]]
    source_tag = entry.get("source_tag")
    args_order = entry.get("args_order")
    special = entry.get("special")
    if source_tag is not None or args_order is not None or special is not None:
        values.append(source_tag)
    if args_order is not None or special is not None:
        values.append(args_order)
    if special is not None:
        values.append(special)
    return "t(" + ", ".join(_lua_value(value) for value in values) + ")"


def _semantic_value(entry: dict[str, Any]) -> str:
    return runtime_semantic_signature(entry)


def _translation_runtime_key(entry: dict[str, Any]) -> tuple[str, str | None]:
    source = entry.get("source")
    source_tag = entry.get("source_tag")
    if not isinstance(source, str) or (source_tag is not None and not isinstance(source_tag, str)):
        raise ValidationError("translation has an invalid runtime key")
    return source, source_tag


def _final_entries(*documents: LocaleDocument) -> list[dict[str, Any]]:
    entries = [
        entry
        for document in documents
        for entry in document.translations
    ]
    last_index: dict[tuple[str, str | None], int] = {}
    for index, entry in enumerate(entries):
        last_index[_translation_runtime_key(entry)] = index
    return [
        entry
        for index, entry in enumerate(entries)
        if last_index[_translation_runtime_key(entry)] == index
    ]


def _render_addon_locale(
    manifest: Manifest,
    entries: Iterable[dict[str, Any]],
    *,
    skipped: Iterable[dict[str, str]],
) -> bytes:
    skipped_items = list(skipped)
    lines = [
        f"locale {_lua_string(manifest.locale)}",
        "-- Generated by tools/i18n; do not edit this file by hand.",
        f"-- Source version: {manifest.version}",
    ]
    if skipped_items:
        lines.append("-- INCOMPLETE ARTIFACT: the following layers were not built:")
        for item in skipped_items:
            lines.append(f"--   {item['component']}: {item['reason']}")
    lines.append("")
    current_section: str | None = None
    for entry in entries:
        section = entry.get("section")
        if not isinstance(section, str):
            section = ""
        if section != current_section:
            if current_section is not None:
                lines.append("")
            lines.append("------------------------------------------------")
            lines.append(f"section {_lua_string(section)}")
            lines.append("")
            current_section = section
        lines.append(_render_translation(entry))
    lines.append("")
    return "\n".join(lines).encode("utf-8")


def _compose_full_locale(
    manifest: Manifest,
    component: ComponentSpec,
) -> bytes:
    pieces = [f"locale {_lua_string(manifest.locale)}\n".encode("utf-8")]
    if component.copy_fragment:
        copy_path = manifest.root / component.copy_fragment
        try:
            copy_bytes = copy_path.read_bytes()
        except OSError as error:
            raise ValidationError(f"cannot read copy fragment: {copy_path}") from error
        pieces.append(copy_bytes)
        if copy_bytes and not copy_bytes.endswith(b"\n"):
            pieces.append(b"\n")
    translation_path = manifest.root / component.translation
    try:
        translation_bytes = translation_path.read_bytes()
    except OSError as error:
        raise ValidationError(f"cannot read translation: {translation_path}") from error
    pieces.append(translation_bytes)
    if translation_bytes and not translation_bytes.endswith(b"\n"):
        pieces.append(b"\n")
    return b"".join(pieces)


def _assert_same_semantics(
    expected_documents: Iterable[LocaleDocument],
    actual: LocaleDocument,
    *,
    label: str,
) -> None:
    expected_map = runtime_map(expected_documents)
    actual_map = runtime_map([actual])
    if set(expected_map) != set(actual_map):
        missing = len(set(expected_map) - set(actual_map))
        unexpected = len(set(actual_map) - set(expected_map))
        raise ValidationError(
            f"{label} runtime keys differ: missing={missing}, unexpected={unexpected}"
        )
    mismatches = [
        key
        for key in expected_map
        if _semantic_value(expected_map[key]) != _semantic_value(actual_map[key])
    ]
    if mismatches:
        raise ValidationError(f"{label} changed {len(mismatches)} translation values")


def _unique_components(
    components: Iterable[ComponentSpec],
) -> list[ComponentSpec]:
    selected: list[ComponentSpec] = []
    seen: set[str] = set()
    for component in components:
        if component.id in seen:
            continue
        seen.add(component.id)
        selected.append(component)
    return selected


def _validate_full_output_layout(components: Iterable[ComponentSpec]) -> None:
    outputs = sorted(
        (
            (PurePosixPath(component.full_output), component)
            for component in components
            if component.full_output is not None
        ),
        key=lambda item: (item[0].parts, item[1].id),
    )
    for index, (first_path, first) in enumerate(outputs):
        for second_path, second in outputs[index + 1 :]:
            if first_path == second_path:
                relationship = "exact duplicate output path"
            elif first_path in second_path.parents or second_path in first_path.parents:
                relationship = "ancestor/descendant output paths"
            else:
                continue
            raise ValidationError(
                f"full_output collision ({relationship}): "
                f"component {first.id!r} maps to {first.full_output!r}; "
                f"component {second.id!r} maps to {second.full_output!r}"
            )


def build_full_locales(
    manifest: Manifest,
    loader: LocaleLoader,
    components: Iterable[ComponentSpec],
) -> dict[str, Any]:
    selected = _unique_components(components)
    if not selected:
        raise ValidationError("no full-locale components selected")
    missing_outputs = [
        component.id for component in selected if component.full_output is None
    ]
    if missing_outputs:
        label = "component" if len(missing_outputs) == 1 else "components"
        verb = "has" if len(missing_outputs) == 1 else "have"
        raise ValidationError(
            f"{label} {', '.join(repr(value) for value in missing_outputs)} "
            f"{verb} no full_output mapping"
        )
    _validate_full_output_layout(selected)
    run_directory = create_run_directory(manifest.root, "build-full")
    reports: list[dict[str, Any]] = []
    for component in selected:
        canonical = loader.load_path(
            manifest.root / component.translation,
            logical_path=component.translation,
        )
        expected_documents: list[LocaleDocument] = []
        if component.copy_fragment:
            expected_documents.append(
                loader.load_path(
                    manifest.root / component.copy_fragment,
                    logical_path=component.copy_fragment,
                )
            )
        expected_documents.append(canonical)
        output_bytes = _compose_full_locale(manifest, component)
        generated = loader.load_bytes(
            output_bytes,
            logical_path=f"generated:full/{component.full_output}",
        )
        _assert_same_semantics(
            expected_documents,
            generated,
            label=f"full build {component.id}",
        )
        output_path = run_directory / "full" / component.full_output
        atomic_write_bytes(output_path, output_bytes)
        reports.append(
            {
                "component": component.id,
                "translation_entries": len(canonical.translations),
                "output": str(output_path),
                "sha256": hashlib.sha256(output_bytes).hexdigest(),
            }
        )
    report = {
        "ok": True,
        "profile": "full",
        "version": manifest.version,
        "components": reports,
        "run_directory": str(run_directory),
    }
    write_json(run_directory / "build.json", report)
    return report


def _verify_overlay(
    official_documents: Iterable[LocaleDocument],
    canonical_documents: Iterable[LocaleDocument],
    patch: LocaleDocument,
) -> dict[str, int]:
    official_map = runtime_map(official_documents)
    canonical_map = runtime_map(canonical_documents)
    patch_map = runtime_map([patch])
    expected = dict(official_map)
    expected.update(canonical_map)
    actual = dict(official_map)
    actual.update(patch_map)
    missing = set(expected) - set(actual)
    unexpected = set(actual) - set(expected)
    mismatched = {
        key
        for key in set(expected) & set(actual)
        if _semantic_value(expected[key]) != _semantic_value(actual[key])
    }
    redundant = {
        key
        for key, entry in patch_map.items()
        if key in official_map
        and _semantic_value(entry) == _semantic_value(official_map[key])
    }
    if missing or unexpected or mismatched or redundant:
        raise ValidationError(
            "addon overlay verification failed: "
            f"missing={len(missing)}, unexpected={len(unexpected)}, "
            f"mismatched={len(mismatched)}, redundant={len(redundant)}"
        )
    return {
        "expected_runtime_keys": len(expected),
        "patch_runtime_keys": len(patch_map),
        "missing": 0,
        "unexpected": 0,
        "mismatched": 0,
        "redundant": 0,
    }


def build_addon_locale(
    manifest: Manifest,
    loader: LocaleLoader,
    components: Iterable[ComponentSpec],
    *,
    include_external_requirements: bool = True,
) -> dict[str, Any]:
    selected = _unique_components(components)
    if not selected:
        raise ValidationError("no addon components selected")
    non_eligible = [
        component.id for component in selected if not component.addon_eligible
    ]
    if non_eligible:
        raise ValidationError(
            "addon build requires addon-eligible components; not eligible: "
            + ", ".join(non_eligible)
        )

    canonical_documents: list[LocaleDocument] = []
    official_documents: list[LocaleDocument] = []
    delta_entries: list[dict[str, Any]] = []
    skipped: list[dict[str, str]] = []
    delta_keys_seen: dict[tuple[str, str | None], str] = {}
    component_reports: list[dict[str, Any]] = []
    inherited_entries = 0
    override_entries = 0
    new_entries = 0

    for component in selected:
        if component.source_repository is None or component.official_locale is None:
            skipped.append(
                {
                    "component": component.id,
                    "reason": "no pinned official locale/source repository",
                }
            )
            continue
        repository_spec = manifest.repositories[component.source_repository]
        repository = GitRepository(manifest.repository_path(component.source_repository))
        official_bytes = repository.read_blob(
            repository_spec.commit, component.official_locale
        )
        official = loader.load_bytes(
            official_bytes,
            logical_path=f"{repository_spec.commit}:{component.official_locale}",
        )
        component_canonical_documents = [
            loader.load_path(
                manifest.root / component.translation,
                logical_path=component.translation,
            )
        ]
        if component.copy_fragment:
            component_canonical_documents.insert(
                0,
                loader.load_path(
                    manifest.root / component.copy_fragment,
                    logical_path=component.copy_fragment,
                ),
            )
        if any(
            record.get("kind") == "casefold"
            for document in component_canonical_documents
            for record in document.records
        ):
            raise ValidationError(
                f"component {component.id!r} uses tc(), which addon rendering does not yet support"
            )
        official_map = runtime_map([official])
        component_delta: list[dict[str, Any]] = []
        final_entries = _final_entries(*component_canonical_documents)
        component_inherited = 0
        component_overrides = 0
        component_new = 0
        for entry in final_entries:
            key = _translation_runtime_key(entry)
            if key in official_map:
                if _semantic_value(entry) == _semantic_value(official_map[key]):
                    inherited_entries += 1
                    component_inherited += 1
                    continue
            semantic = _semantic_value(entry)
            previous = delta_keys_seen.get(key)
            if previous is not None and previous != semantic:
                raise ValidationError(
                    f"addon components disagree on runtime key {key!r}"
                )
            if previous is not None:
                continue
            if key in official_map:
                override_entries += 1
                component_overrides += 1
            else:
                new_entries += 1
                component_new += 1
            delta_keys_seen[key] = semantic
            component_delta.append(entry)
        delta_entries.extend(component_delta)
        canonical_documents.extend(component_canonical_documents)
        official_documents.append(official)
        component_reports.append(
            {
                "component": component.id,
                "canonical_entries": sum(
                    len(document.translations)
                    for document in component_canonical_documents
                ),
                "canonical_runtime_keys": len(final_entries),
                "official_entries": len(official.translations),
                "inherited_entries": component_inherited,
                "override_entries": component_overrides,
                "new_entries": component_new,
                "delta_entries": len(component_delta),
            }
        )

    if include_external_requirements:
        skipped.extend(
            {"component": requirement.id, "reason": requirement.reason}
            for requirement in manifest.addon_external_requirements
        )

    if not canonical_documents:
        raise ValidationError("no addon component has a pinned official baseline")
    output_bytes = _render_addon_locale(manifest, delta_entries, skipped=skipped)
    generated = loader.load_bytes(
        output_bytes,
        logical_path="generated:addon/data/locales/zh_hans.lua",
    )
    verification = _verify_overlay(
        official_documents,
        canonical_documents,
        generated,
    )
    run_directory = create_run_directory(manifest.root, "build-addon")
    output_path = run_directory / "addon" / "data" / "locales" / "zh_hans.lua"
    atomic_write_bytes(output_path, output_bytes)
    report = {
        "ok": True,
        "complete": not skipped,
        "profile": "addon",
        "version": manifest.version,
        "components": component_reports,
        "external_requirements_included": include_external_requirements,
        "inherited_entries": inherited_entries,
        "override_entries": override_entries,
        "new_entries": new_entries,
        "delta_entries": delta_entries,
        "skipped": skipped,
        "verification": verification,
        "output": str(output_path),
        "sha256": hashlib.sha256(output_bytes).hexdigest(),
        "run_directory": str(run_directory),
    }
    write_json(run_directory / "build.json", report)
    return report
