"""Non-destructive three-way merge and candidate generation."""

from __future__ import annotations

import hashlib
import json
from collections import defaultdict
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any

from .build import _lua_string, _render_translation
from .config import ComponentSpec, Manifest
from .errors import ValidationError
from .lint import Issue, lint_documents, load_policy
from .locale_model import LocaleDocument, LocaleLoader
from .report import atomic_write_bytes, create_run_directory, write_json
from .snapshot import DefinitionGroup, Snapshot, read_snapshot


def _semantic_signature(entry: dict[str, Any]) -> str:
    value = [entry.get("target"), entry.get("args_order"), entry.get("special")]
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _editorial_key(entry: dict[str, Any]) -> tuple[str, str, str | None]:
    section = entry.get("section")
    source = entry.get("source")
    source_tag = entry.get("source_tag")
    if not isinstance(section, str) or not isinstance(source, str):
        raise ValidationError("translation has an invalid editorial key")
    if source_tag is not None and not isinstance(source_tag, str):
        raise ValidationError("translation has an invalid source_tag")
    return section, source, source_tag


def _runtime_key(entry: dict[str, Any]) -> tuple[str, str | None]:
    _, source, source_tag = _editorial_key(entry)
    return source, source_tag


def _current_indexes(
    document: LocaleDocument,
) -> tuple[
    dict[tuple[str, str, str | None], dict[str, Any]],
    dict[tuple[str, str | None], dict[str, Any]],
]:
    editorial: dict[tuple[str, str, str | None], dict[str, Any]] = {}
    runtime_groups: dict[tuple[str, str | None], list[dict[str, Any]]] = defaultdict(list)
    for entry in document.translations:
        editorial[_editorial_key(entry)] = entry
        runtime_groups[_runtime_key(entry)].append(entry)
    runtime: dict[tuple[str, str | None], dict[str, Any]] = {}
    for key, entries in runtime_groups.items():
        signatures = {_semantic_signature(entry) for entry in entries}
        if len(signatures) > 1:
            raise ValidationError(
                f"canonical translation contains a runtime collision for {key!r}"
            )
        runtime[key] = entries[-1]
    return editorial, runtime


def _candidate_entry(
    group: DefinitionGroup,
    translation: dict[str, Any],
) -> dict[str, Any]:
    return {
        "kind": "translation",
        "function_name": "t",
        "section": group.definition.section,
        "source": group.definition.source,
        "target": translation.get("target"),
        "source_tag": group.definition.source_tag,
        "args_order": translation.get("args_order"),
        "special": translation.get("special"),
        "line": translation.get("line"),
        "logical_path": translation.get("logical_path"),
    }


def _render_candidate(
    component: str,
    snapshot_sha256: str,
    entries: list[dict[str, Any]],
) -> bytes:
    lines = [
        "-- Generated by tools/i18n merge; review before applying.",
        f"-- Component: {component}",
        f"-- Extraction snapshot: {snapshot_sha256}",
        "",
    ]
    current_section: str | None = None
    for entry in entries:
        section = entry["section"]
        if section != current_section:
            if current_section is not None:
                lines.append("")
            lines.extend(
                [
                    "------------------------------------------------",
                    f"section {_lua_string(section)}",
                    "",
                ]
            )
            current_section = section
        lines.append(_render_translation(entry))
    lines.append("")
    return "\n".join(lines).encode("utf-8")


def _group_detail(group: DefinitionGroup, *, classification: str) -> dict[str, Any]:
    detail = group.to_dict()
    detail["classification"] = classification
    return detail


def _source_change_suggestions(
    *,
    untranslated_groups: list[DefinitionGroup],
    base_snapshot: Snapshot,
    new_snapshot: Snapshot,
    current_runtime: dict[tuple[str, str | None], dict[str, Any]],
    threshold: float = 0.68,
    base_index: Any | None = None,
    new_index: Any | None = None,
) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]], dict[str, Any]]:
    deleted_groups = [
        group
        for group in base_snapshot.groups
        if group.runtime_key not in new_snapshot.runtime_keys
        and group.runtime_key in current_runtime
    ]
    buckets: dict[tuple[str, str | None], list[DefinitionGroup]] = defaultdict(list)
    for group in deleted_groups:
        buckets[(group.definition.section, group.definition.source_tag)].append(group)

    # Contract §5: L1-L5 identity matching, layered on the legacy heuristic.
    # Field compatibility: classification "source-changed" and automatic False
    # are preserved; identity matches add match_level / tu_uid / event.
    identity_matches: dict[str, Any] = {}
    identity_events: list[dict[str, Any]] = []
    if base_index is not None and new_index is not None:
        from .identity import match_migrations

        matches, events = match_migrations(
            base_index=base_index,
            new_index=new_index,
            untranslated_groups=untranslated_groups,
            base_snapshot=base_snapshot,
            threshold=threshold,
        )
        identity_matches = {match.group.entry_id: match for match in matches}
        identity_events = [event.to_dict() for event in events]

    suggestions: list[dict[str, Any]] = []
    by_new_entry_id: dict[str, dict[str, Any]] = {}
    for group in untranslated_groups:
        if group.runtime_key in base_snapshot.runtime_keys:
            continue
        identity_match = identity_matches.get(group.entry_id)
        if identity_match is not None and identity_match.level in ("L1", "L2", "L4"):
            previous_definition = identity_match.previous_definition
            if identity_match.level == "L4":
                # Hint only: never carries curated data (contract §5).
                suggestions.append(
                    {
                        "entry_id": group.entry_id,
                        "component": group.definition.component,
                        "section": group.definition.section,
                        "source": group.definition.source,
                        "source_tag": group.definition.source_tag,
                        "origins": [
                            occurrence.origin_dict()
                            for occurrence in group.occurrences
                        ],
                        "previous_source": previous_definition.source
                        if previous_definition is not None
                        else None,
                        "similarity": (
                            round(identity_match.similarity, 6)
                            if identity_match.similarity is not None
                            else None
                        ),
                        "match_level": "L4",
                        "classification": "source-changed",
                        "automatic": False,
                        "hint_only": True,
                    }
                )
                continue
            previous = previous_definition
            previous_translation = (
                current_runtime.get(previous.runtime_key)
                if previous is not None
                else None
            )
            if previous is None:
                continue
            if previous_translation is None:
                # L1 identity match without a current translation: nothing to
                # carry; record the direct binding for the report only.
                continue
            suggestion = {
                "entry_id": group.entry_id,
                "component": group.definition.component,
                "section": group.definition.section,
                "source": group.definition.source,
                "source_tag": group.definition.source_tag,
                "origins": [
                    occurrence.origin_dict() for occurrence in group.occurrences
                ],
                "previous_source": previous.source,
                "previous_source_tag": previous.source_tag,
                "previous_target": previous_translation.get("target"),
                "previous_args_order": previous_translation.get("args_order"),
                "previous_special": previous_translation.get("special"),
                "similarity": (
                    round(identity_match.similarity, 6)
                    if identity_match.similarity is not None
                    else 1.0
                ),
                "match_level": identity_match.level,
                "tu_uid": identity_match.tu_uid,
                "event": (
                    identity_match.event.to_dict()
                    if identity_match.event is not None
                    else None
                ),
                "classification": "source-changed",
                "automatic": False,
            }
            suggestions.append(suggestion)
            by_new_entry_id[group.entry_id] = suggestion
            continue
        candidates = buckets.get(
            (group.definition.section, group.definition.source_tag), []
        )
        best: DefinitionGroup | None = None
        best_score = 0.0
        for candidate in candidates:
            score = SequenceMatcher(
                None,
                candidate.definition.source,
                group.definition.source,
                autojunk=False,
            ).ratio()
            if score > best_score:
                best = candidate
                best_score = score
        if best is None or best_score < threshold:
            continue
        old_translation = current_runtime[best.runtime_key]
        suggestion = {
            "entry_id": group.entry_id,
            "component": group.definition.component,
            "section": group.definition.section,
            "source": group.definition.source,
            "source_tag": group.definition.source_tag,
            "origins": [
                occurrence.origin_dict() for occurrence in group.occurrences
            ],
            "previous_source": best.definition.source,
            "previous_source_tag": best.definition.source_tag,
            "previous_target": old_translation.get("target"),
            "previous_args_order": old_translation.get("args_order"),
            "previous_special": old_translation.get("special"),
            "similarity": round(best_score, 6),
            "classification": "source-changed",
            "automatic": False,
        }
        suggestions.append(suggestion)
        by_new_entry_id[group.entry_id] = suggestion
    return suggestions, by_new_entry_id, {
        "identity_matches": {
            entry_id: match.to_dict()
            for entry_id, match in sorted(identity_matches.items())
        },
        "identity_events": identity_events,
    }


def classify_merge(
    *,
    component: str,
    current: LocaleDocument,
    base_snapshot: Snapshot,
    new_snapshot: Snapshot,
    base_index: Any | None = None,
    new_index: Any | None = None,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if base_snapshot.component != component or new_snapshot.component != component:
        raise ValidationError("merge snapshots do not match the selected component")
    if any(record.get("kind") == "casefold" for record in current.records):
        raise ValidationError("merge does not yet support tc() records")

    current_editorial, current_runtime = _current_indexes(current)
    candidate_entries: list[dict[str, Any]] = []
    untranslated_groups: list[DefinitionGroup] = []
    exact = 0
    moved = 0
    for group in new_snapshot.groups:
        translation = current_editorial.get(group.editorial_key)
        if translation is not None:
            exact += 1
            candidate_entries.append(_candidate_entry(group, translation))
            continue
        translation = current_runtime.get(group.runtime_key)
        if translation is not None:
            moved += 1
            candidate_entries.append(_candidate_entry(group, translation))
            continue
        untranslated_groups.append(group)

    suggestions, suggestion_index, identity_report = _source_change_suggestions(
        untranslated_groups=untranslated_groups,
        base_snapshot=base_snapshot,
        new_snapshot=new_snapshot,
        current_runtime=current_runtime,
        base_index=base_index,
        new_index=new_index,
    )
    untranslated: list[dict[str, Any]] = []
    for group in untranslated_groups:
        if group.entry_id in suggestion_index:
            untranslated.append(suggestion_index[group.entry_id])
        else:
            classification = (
                "added"
                if group.runtime_key not in base_snapshot.runtime_keys
                else "untranslated-existing"
            )
            untranslated.append(
                _group_detail(group, classification=classification)
            )

    obsolete: list[dict[str, Any]] = []
    for runtime_key, entry in current_runtime.items():
        if runtime_key in new_snapshot.runtime_keys:
            continue
        section, source, source_tag = _editorial_key(entry)
        obsolete.append(
            {
                "entry_id": hashlib.sha256(
                    "\0".join(
                        (
                            component,
                            section,
                            source,
                            "<nil>"
                            if source_tag is None
                            else f"<string>{source_tag}",
                        )
                    ).encode("utf-8")
                ).hexdigest(),
                "component": component,
                "section": section,
                "source": source,
                "source_tag": source_tag,
                "target": entry.get("target"),
                "args_order": entry.get("args_order"),
                "special": entry.get("special"),
                "line": entry.get("line"),
                "classification": "obsolete-or-unextracted",
            }
        )

    base_runtime = base_snapshot.runtime_keys
    new_runtime = new_snapshot.runtime_keys
    report = {
        "component": component,
        "counts": {
            "base_occurrences": len(base_snapshot.definitions),
            "base_unique_editorial": len(base_snapshot.groups),
            "new_occurrences": len(new_snapshot.definitions),
            "new_unique_editorial": len(new_snapshot.groups),
            "canonical_translations": len(current.translations),
            "candidate_translations": len(candidate_entries),
            "exact_editorial": exact,
            "moved_section": moved,
            "untranslated": len(untranslated),
            "source_changed_suggestions": len(suggestions),
            "obsolete_or_unextracted": len(obsolete),
            "source_runtime_added": len(new_runtime - base_runtime),
            "source_runtime_deleted": len(base_runtime - new_runtime),
        },
        "untranslated": untranslated,
        "source_changed_suggestions": suggestions,
        "obsolete": obsolete,
    }
    if base_index is not None or new_index is not None:
        report["identity"] = identity_report
    return candidate_entries, report


def run_merge(
    manifest: Manifest,
    loader: LocaleLoader,
    component: ComponentSpec,
    *,
    new_snapshot_path: Path,
    base_snapshot_path: Path | None,
    base_index: Any | None = None,
    new_index: Any | None = None,
) -> dict[str, Any]:
    new_snapshot = read_snapshot(
        new_snapshot_path, expected_component=component.id
    )
    base_snapshot = (
        read_snapshot(base_snapshot_path, expected_component=component.id)
        if base_snapshot_path is not None
        else new_snapshot
    )
    current = loader.load_path(
        manifest.root / component.translation,
        logical_path=component.translation,
    )
    policy = load_policy(manifest)
    current_issues, current_metrics = lint_documents(
        [(component.id, current)], policy
    )
    current_errors = [issue for issue in current_issues if issue.severity == "error"]
    if current_errors:
        raise ValidationError(
            f"canonical translation has {len(current_errors)} blocking lint errors"
        )

    candidate_entries, classification = classify_merge(
        component=component.id,
        current=current,
        base_snapshot=base_snapshot,
        new_snapshot=new_snapshot,
        base_index=base_index,
        new_index=new_index,
    )
    candidate_bytes = _render_candidate(
        component.id, new_snapshot.sha256, candidate_entries
    )
    candidate = loader.load_bytes(
        candidate_bytes,
        logical_path=f"generated:merge/{component.translation}",
    )
    candidate_issues, candidate_metrics = lint_documents(
        [(component.id, candidate)], policy
    )
    candidate_errors = [
        issue for issue in candidate_issues if issue.severity == "error"
    ]
    if candidate_errors:
        raise ValidationError(
            f"merge candidate has {len(candidate_errors)} blocking lint errors"
        )

    merge_id = hashlib.sha256(
        "\0".join(
            (
                component.id,
                base_snapshot.sha256,
                new_snapshot.sha256,
                current.sha256,
            )
        ).encode("ascii")
    ).hexdigest()
    run_directory = create_run_directory(manifest.root, "merge")
    candidate_path = run_directory / component.id / "candidate.lua"
    atomic_write_bytes(candidate_path, candidate_bytes)
    report: dict[str, Any] = {
        "schema_version": 1,
        "ok": True,
        "safe_to_apply": (
            classification["counts"]["untranslated"] == 0
            and classification["counts"]["obsolete_or_unextracted"] == 0
        ),
        "version": manifest.version,
        "component": component.id,
        "merge_id": merge_id,
        "mode": "three-way" if base_snapshot_path is not None else "bootstrap",
        "base_snapshot": str(base_snapshot.path),
        "base_snapshot_sha256": base_snapshot.sha256,
        "new_snapshot": str(new_snapshot.path),
        "new_snapshot_sha256": new_snapshot.sha256,
        "canonical_translation": component.translation,
        "canonical_sha256": current.sha256,
        "candidate": str(candidate_path),
        "candidate_sha256": hashlib.sha256(candidate_bytes).hexdigest(),
        "current_lint": current_metrics,
        "candidate_lint": candidate_metrics,
        "candidate_warnings": [
            issue.to_dict()
            for issue in candidate_issues
            if issue.severity == "warning"
        ],
        **classification,
        "run_directory": str(run_directory),
    }
    report_path = run_directory / component.id / "merge.json"
    report["report"] = str(report_path)
    write_json(report_path, report)
    write_json(run_directory / "summary.json", {
        "schema_version": 1,
        "version": manifest.version,
        "component": component.id,
        "merge_id": merge_id,
        "safe_to_apply": report["safe_to_apply"],
        "counts": report["counts"],
        "candidate": str(candidate_path),
        "report": str(report_path),
    })
    return report
