#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readCanonical,jsonBytes,sha256,shaFile,writeExclusive} from './lib.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
export const CELL_ORDER=['baseline-p0-s0-a','schema-p0-s2-a','prompt-p1-s0-a','combined-p1-s2-a','context-p0-s0-c'];
const FROZEN=['frozen/CONTEXTS.json','frozen/REQUEST-MANIFEST.json',...CELL_ORDER.map(x=>`model-facing/requests/${x}.txt`)];
const clarification='Field rules:\n- `target_span`: copy a contiguous substring of this item\'s `target`, character for character.\n- `evidence`: copy a contiguous substring of this item\'s `source`, `target`, or `source_context` when present, character for character; it is a quotation, never explanation, translation, summary, or reasoning.\n- `correction`: authored replacement text for `target_span`; it is the only one of these fields not copied.\n\nWorked example (not an experiment item): for source "The cup is red." and target "杯子是蓝色的。", a candidate may use `target_span` "蓝色", `evidence` "red", and `correction` "红色".';
const leak=/(?:\/(?:home|Users|root|tmp|opt|var|mnt)\/|sealed.?reference|adjudicat|defect.?id|model.?provenance|api.?key|access.?token|client.?secret|credential)/iu;
export function renderContexts(items,source){const prose=source.passages.join('\n\n');return{schema_version:'evidence-contract-contexts-v1',license:'CC0-1.0',items:items.map(x=>({item_id:x.item_id,source_context:`${x.source}\n\n${prose}`}))}}
function promptFor(root,cell,def){let p=fs.readFileSync(path.join(root,def.prompt),'utf8').trim();if(cell==='combined-p1-s2-a')p=p.replaceAll('`evidence`','`evidence_quote`');return p}
export function renderRequest(prompt,input,schema){return Buffer.from(`${prompt}\n\nINPUT JSON:\n${JSON.stringify(input,null,2)}\n\nOUTPUT SCHEMA:\n${JSON.stringify(schema,null,2)}\n`)}
export function splitRequest(bytes){const text=Buffer.from(bytes).toString('utf8'),a=text.indexOf('\n\nINPUT JSON:\n'),b=text.indexOf('\n\nOUTPUT SCHEMA:\n');if(a<0||b<a)throw Error('REQUEST_FORMAT');return{prompt:text.slice(0,a),input:JSON.parse(text.slice(a+14,b)),schema:JSON.parse(text.slice(b+17))}}
export function normalizeSchema(s){const x=structuredClone(s),c=x.properties.items.items.properties.candidates.items;c.required=c.required.map(k=>k==='evidence_quote'?'evidence':k);const p=c.properties;if(p.evidence_quote){p.evidence=p.evidence_quote;delete p.evidence_quote}for(const k of ['target_span','correction','evidence'])delete p[k].description;return x}
export function normalizePrompt(p){return p.replaceAll('`evidence_quote`','`evidence`').replace(`\n\n${clarification}\n\n`,' ').replace('no free text or reasoning outside these JSON fields','no free text or reasoning')}
export function normalizedFactorBytes(bytes){const q=splitRequest(bytes);return Buffer.from(JSON.stringify({prompt:normalizePrompt(q.prompt),input:{items:q.input.items.map(({source_context,...x})=>x)},schema:normalizeSchema(q.schema)}))}
export function build(root=here){const design=readCanonical(path.join(root,'DESIGN-CONTRACT.json')),doc=readCanonical(path.join(root,'ITEMS.json')),ctxSource=readCanonical(path.join(root,'CONTEXT-SOURCE.json'));if(JSON.stringify(design.registered_order)!==JSON.stringify(CELL_ORDER))throw Error('CELL_ORDER');if(doc.items.length!==16||doc.items.some((x,i)=>x.item_id!==`EC-I${String(i+1).padStart(3,'0')}`))throw Error('ITEMS');const contexts=renderContexts(doc.items,ctxSource),ctx=new Map(contexts.items.map(x=>[x.item_id,x.source_context])),requests=[];for(const cell of CELL_ORDER){const def=design.cells[cell],schema=readCanonical(path.join(root,def.schema)),prompt=promptFor(root,cell,def),input={items:doc.items.map(x=>({...x,...(def.context?{source_context:ctx.get(x.item_id)}:{})}))},bytes=renderRequest(prompt,input,schema),n=bytes.length;if(leak.test(bytes.toString('utf8')))throw Error(`REQUEST_LEAK:${cell}`);const [min,max]=def.context?[design.request_utf8_bounds.c_min,design.request_utf8_bounds.c_max]:[design.request_utf8_bounds.a_min,design.request_utf8_bounds.a_max];if(n<min||n>max)throw Error(`REQUEST_SIZE:${cell}:${n}`);requests.push({cell,path:`model-facing/requests/${cell}.txt`,sha256:sha256(bytes),utf8_bytes:n,prompt:def.prompt,schema:def.schema,context:def.context,item_ids:doc.items.map(x=>x.item_id),bytes})}const base=splitRequest(requests[0].bytes);for(const r of requests){const q=splitRequest(r.bytes);if(JSON.stringify(q.input.items.map(({source_context,...x})=>x))!==JSON.stringify(base.input.items))throw Error(`ITEM_FACTOR_DRIFT:${r.cell}`);if(!r.context&&q.input.items.some(x=>'source_context'in x))throw Error(`A_CONTEXT:${r.cell}`);if(r.context&&q.input.items.some(x=>!x.source_context?.includes(x.source)))throw Error('CONTEXT_SOURCE');if(JSON.stringify(normalizeSchema(q.schema))!==JSON.stringify(normalizeSchema(base.schema)))throw Error(`SCHEMA_FACTOR_DRIFT:${r.cell}`);if(normalizePrompt(q.prompt)!==normalizePrompt(base.prompt))throw Error(`PROMPT_FACTOR_DRIFT:${r.cell}`);if(!normalizedFactorBytes(r.bytes).equals(normalizedFactorBytes(requests[0].bytes)))throw Error(`NORMALIZED_BYTE_DRIFT:${r.cell}`)}return{contexts,requests,manifest:{schema_version:'evidence-contract-request-manifest-v1',fixed_order:CELL_ORDER,items_sha256:shaFile(path.join(root,'ITEMS.json')),context_source_sha256:shaFile(path.join(root,'CONTEXT-SOURCE.json')),route_contract_sha256:shaFile(path.join(root,'ROUTE-CONTRACT.json')),metrics_contract_sha256:shaFile(path.join(root,'METRICS-CONTRACT.json')),requests:requests.map(({bytes,...x})=>x)}}}
export function checkFreeze(root=here){const errors=[];let built;try{built=build(root)}catch(e){return{errors:[e.message],built:null}}const expected=new Map([['frozen/CONTEXTS.json',jsonBytes(built.contexts)],['frozen/REQUEST-MANIFEST.json',jsonBytes(built.manifest)],...built.requests.map(x=>[x.path,x.bytes])]);for(const [rel,b]of expected){const p=path.join(root,rel);if(!fs.existsSync(p))errors.push(`MISSING:${rel}`);else if(!fs.readFileSync(p).equals(b))errors.push(`DRIFT:${rel}`)}return{errors,built}}
export function freeze(root=here){const b=build(root);for(const [rel,bytes]of [['frozen/CONTEXTS.json',jsonBytes(b.contexts)],...b.requests.map(x=>[x.path,x.bytes]),['frozen/REQUEST-MANIFEST.json',jsonBytes(b.manifest)]]){const p=path.join(root,rel);if(fs.existsSync(p)){if(!fs.readFileSync(p).equals(bytes))throw Error(`FROZEN_DRIFT:${rel}`)}else writeExclusive(p,bytes)}return{items:16,requests:5,request_bytes:Object.fromEntries(b.requests.map(x=>[x.cell,x.utf8_bytes]))}}
if(import.meta.url===`file://${process.argv[1]}`){try{if(process.argv[2]==='--check'){const x=checkFreeze();console.log(JSON.stringify({mode:'CHECK',request_bytes:x.built?Object.fromEntries(x.built.requests.map(r=>[r.cell,r.utf8_bytes])):{},errors:x.errors},null,2));process.exitCode=x.errors.length?3:0}else if(process.argv.length===2)console.log(JSON.stringify(freeze(),null,2));else{console.error('usage: node freezer.mjs [--check]');process.exitCode=2}}catch(e){console.error(e.message);process.exitCode=3}}
