import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
export const sha256=x=>crypto.createHash('sha256').update(x).digest('hex');
export const jsonBytes=x=>Buffer.from(`${JSON.stringify(x,null,2)}\n`);
export const shaFile=p=>sha256(fs.readFileSync(p));
export const byteSort=(a,b)=>Buffer.compare(Buffer.from(a),Buffer.from(b));
export const exactKeys=(x,keys)=>!!x&&typeof x==='object'&&!Array.isArray(x)&&JSON.stringify(Object.keys(x).sort(byteSort))===JSON.stringify([...keys].sort(byteSort));
export function parseNoDuplicate(text,label='JSON'){let i=0;const ws=()=>{while(/\s/u.test(text[i]??''))i++};const str=()=>{if(text[i++]!=='"')throw Error(`${label}:STRING`);let raw='"';for(;;){if(i>=text.length)throw Error(`${label}:STRING_EOF`);const c=text[i++];raw+=c;if(c==='"')break;if(c==='\\'){if(i>=text.length)throw Error(`${label}:ESCAPE_EOF`);raw+=text[i++]}else if(c<' ')throw Error(`${label}:CONTROL`)}return JSON.parse(raw)};const val=()=>{ws();if(text[i]==='"'){str();return}if(text[i]==='{'){obj();return}if(text[i]==='['){arr();return}const m=text.slice(i).match(/^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/u);if(!m)throw Error(`${label}:VALUE@${i}`);i+=m[0].length};const obj=()=>{i++;ws();const keys=new Set();if(text[i]==='}'){i++;return}for(;;){ws();const k=str();if(keys.has(k))throw Error(`${label}:DUPLICATE_KEY:${k}`);keys.add(k);ws();if(text[i++]!==':')throw Error(`${label}:COLON`);val();ws();const c=text[i++];if(c==='}')return;if(c!==',')throw Error(`${label}:OBJECT_SEPARATOR`)}};const arr=()=>{i++;ws();if(text[i]===']'){i++;return}for(;;){val();ws();const c=text[i++];if(c===']')return;if(c!==',')throw Error(`${label}:ARRAY_SEPARATOR`)}};val();ws();if(i!==text.length)throw Error(`${label}:TRAILING`);return JSON.parse(text)}
export function readCanonical(p){const b=fs.readFileSync(p),v=parseNoDuplicate(b.toString('utf8'),p);if(!b.equals(jsonBytes(v)))throw Error(`NONCANONICAL:${p}`);return v}
export function walk(dir,base='',out=[]){if(!fs.existsSync(dir))return out;for(const e of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>byteSort(a.name,b.name))){const rel=path.posix.join(base,e.name),p=path.join(dir,e.name),s=fs.lstatSync(p);if(s.isSymbolicLink())throw Error(`SYMLINK:${rel}`);if(e.isDirectory())walk(p,rel,out);else if(e.isFile())out.push(rel);else throw Error(`NONREGULAR:${rel}`)}return out}
export function treeBinding(repoRoot,rel){const dir=path.join(repoRoot,rel),files=walk(dir).map(p=>({path:p,sha256:shaFile(path.join(dir,p))})).sort((a,b)=>byteSort(a.path,b.path));return{root:rel,file_count:files.length,tree_sha256:sha256(Buffer.concat(files.map(x=>Buffer.from(`${x.path}\0${x.sha256}\n`))))}}
export function writeExclusive(p,bytes){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,Buffer.isBuffer(bytes)?bytes:jsonBytes(bytes),{flag:'wx'})}
