import fs from'node:fs';import path from'node:path';import{spawnSync}from'node:child_process';import{readCanonical,shaFile,sha256,jsonBytes,writeExclusive}from'./lib.mjs';import{CELL_ORDER,splitRequest}from'./freezer.mjs';import{checkManifest}from'./build-manifest.mjs';import{validateGates}from'./gates.mjs';import{derive,start,finish,append,capturePaths}from'./ledger.mjs';import{parseCapture}from'./parser.mjs';import{metrics}from'./metrics.mjs';
const EXPECTED='/home/yun/.local/lib/agy-pinned/f3575050ae826d1944913f595b32f827a4674ec42e59ff0476450e2bac5fa39e/agy',HASH='f3575050ae826d1944913f595b32f827a4674ec42e59ff0476450e2bac5fa39e';
export function verifyRoute(root,plan=null){const r=readCanonical(path.join(root,'ROUTE-CONTRACT.json')),c=r.cli_contract;if(c.executable!==EXPECTED||c.executable_sha256!==HASH||c.model!=='gemini-3.7-flash-high')throw Error('STOP_ROUTE_CONFIG');const s=fs.statSync(c.executable);if(!s.isFile()||shaFile(c.executable)!==HASH)throw Error('STOP_ROUTE_EXECUTABLE');if(plan){const i=plan.argv.indexOf('--model');if(i<0||plan.argv[i+1]!==c.model)throw Error('STOP_ROUTE_ARGV_MODEL')}return r}
export function makePlan(root,cell){const m=readCanonical(path.join(root,'frozen/REQUEST-MANIFEST.json')),e=m.requests.find(x=>x.cell===cell);if(!e)throw Error('UNKNOWN_CELL');const request=fs.readFileSync(path.join(root,e.path),'utf8');if(sha256(request)!==e.sha256)throw Error('REQUEST_DRIFT');const r=readCanonical(path.join(root,'ROUTE-CONTRACT.json')),schema=fs.readFileSync(path.join(root,e.schema),'utf8'),argv=r.cli_contract.argv_template.map(x=>x==='[REQUEST_BYTES]'?request:x==='[BUNDLE_SCHEMA]'?schema:x),env=Object.fromEntries(r.environment_allowlist.filter(k=>process.env[k]!==undefined).map(k=>[k,process.env[k]]));return{entry:e,request,command:r.cli_contract.executable,argv,env,timeout_ms:r.cli_contract.timeout_ms}}
const invoke=p=>{const r=spawnSync(p.command,p.argv,{env:p.env,encoding:null,timeout:p.timeout_ms,maxBuffer:16*1024*1024});return{exit_code:Number.isInteger(r.status)?r.status:-1,stdout:Buffer.from(r.stdout??''),stderr:Buffer.from(r.stderr??''),timed_out:r.error?.code==='ETIMEDOUT'}};
const errorBuffer=(e,key)=>Buffer.from(Buffer.isBuffer(e?.[key])?e[key]:typeof e?.[key]==='string'?e[key]:'');
export function runCell(root,repoRoot,cell,systemInvoke=invoke){const me=checkManifest(root);if(me.length)throw Error(`MANIFEST:${me}`);const gates=validateGates(root,repoRoot);if(!gates.valid)throw Error(`GATES:${gates.errors}`);const state=derive(root);if(state.errors.length)throw Error(`LEDGER:${state.errors}`);const index=CELL_ORDER.indexOf(cell);if(index<0)throw Error('CELL_NOT_REGISTERED');if(state.agy_processes_spawned>=5)throw Error('STOP_BUDGET');if(state.cells[cell])throw Error('ATTEMPT_EXHAUSTED');if(index!==state.agy_processes_spawned)throw Error('REGISTERED_ORDER_REQUIRED');if(index>0){const prev=state.cells[CELL_ORDER[index-1]]?.finish;if(!prev?.process_success||!prev?.envelope_schema_valid)throw Error('PRIOR_CELL_STOP')}const plan=makePlan(root,cell);verifyRoute(root,plan);const s=start(cell);append(root,s);
  let result={exit_code:-1,stdout:Buffer.alloc(0),stderr:Buffer.alloc(0),timed_out:false},parsed={valid:false,errors:['POST_SPAWN_EXCEPTION'],normalized:null},raw_path=null,cell_metrics=null,postSpawnError=null;
  try{
    try{const x=systemInvoke(plan);result={exit_code:Number.isInteger(x?.exit_code)?x.exit_code:-1,stdout:Buffer.from(x?.stdout??''),stderr:Buffer.from(x?.stderr??''),timed_out:!!x?.timed_out}}catch(e){postSpawnError=e;result.stdout=errorBuffer(e,'stdout');result.stderr=errorBuffer(e,'stderr')}
    const paths=capturePaths(cell);for(const [kind,bytes]of[['stdout',result.stdout],['stderr',result.stderr]])try{writeExclusive(path.join(root,paths[kind]),bytes)}catch(e){postSpawnError??=e}
    const process_success=!postSpawnError&&result.exit_code===0&&!result.timed_out;
    if(process_success){try{const req=splitRequest(plan.request),schemaName=plan.entry.schema.endsWith('/S2.json')?'S2':'S0';parsed=parseCapture(result.stdout,req.input,schemaName);if(parsed.valid){const raw={schema_version:'evidence-contract-raw-v1',cell,request_sha256:plan.entry.sha256,normalized_output:parsed.normalized};writeExclusive(path.join(root,paths.raw),jsonBytes(raw));raw_path=paths.raw;cell_metrics=metrics(parsed.normalized,req.input)}}catch(e){postSpawnError??=e;parsed={valid:false,errors:[`POST_SPAWN:${e.message}`],normalized:null};raw_path=null;cell_metrics=null}}
    else parsed={valid:false,errors:[postSpawnError?`POST_SPAWN:${postSpawnError.message}`:'PROCESS_FAILED'],normalized:null};
  }finally{
    const process_success=!postSpawnError&&result.exit_code===0&&!result.timed_out;
    append(root,finish(s,{exit_code:result.exit_code,stdout_sha256:sha256(result.stdout),stderr_sha256:sha256(result.stderr),process_success,envelope_schema_valid:process_success&&parsed.valid,raw_path}));
  }
  return{cell,attempt:1,process_success:!postSpawnError&&result.exit_code===0&&!result.timed_out,envelope_schema_valid:!postSpawnError&&parsed.valid,errors:parsed.errors,metrics:cell_metrics,continue_authorized:!postSpawnError&&result.exit_code===0&&!result.timed_out&&parsed.valid};
}
