#!/usr/bin/env node
import assert from'node:assert/strict';
import fs from'node:fs';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';
import{build,checkFreeze,CELL_ORDER,splitRequest,normalizePrompt,normalizeSchema,normalizedFactorBytes}from'../freezer.mjs';
import{checkManifest}from'../build-manifest.mjs';import{parseOutput}from'../parser.mjs';import{metrics}from'../metrics.mjs';import{runCell}from'../runner.mjs';import{preflight}from'../preflight.mjs';import{postRun,interpret,INTERPRETATION_CAVEAT}from'../post-run.mjs';import{jsonBytes,shaFile,treeBinding,sha256}from'../lib.mjs';import{GATE_PATHS}from'../gates.mjs';import{derive,capturePaths}from'../ledger.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const runScope=`evidence-contract-v1-${process.pid}-${Date.now()}-`,owned=[];
function makeTemp(){const p=fs.mkdtempSync(path.join(os.tmpdir(),runScope));owned.push(p);return p}
function cleanOwned(){for(const p of owned.splice(0))fs.rmSync(p,{recursive:true,force:true})}
for(const s of['SIGINT','SIGTERM'])process.once(s,()=>{cleanOwned();process.exit(128+(s==='SIGINT'?2:15))});
function output(input,key='evidence',mode='valid'){return{items:input.items.map((x,i)=>({item_id:x.item_id,candidates:i?[]:[{verdict:'FINDING',claim_type:'OTHER',target_span:mode==='membership'?'不存在':x.target.slice(0,1),correction:'修正',[key]:mode==='membership'?'This is an explanation because it differs.':x.source.slice(0,3)}]}))}}
function envelope(x){return Buffer.from(JSON.stringify({status:'SUCCESS',structured_output:x,response:null}))}
function gateRepo(pkg){const repo=path.dirname(path.dirname(path.dirname(path.dirname(pkg)))),predRel='evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v5',predDest=path.join(repo,predRel);fs.mkdirSync(path.dirname(predDest),{recursive:true});fs.cpSync(path.resolve(root,'../gemini-context-counterexample-reviewer-v5-execution-v5'),predDest,{recursive:true});const task=path.join(repo,path.dirname(GATE_PATHS.PACKAGE_REVIEW));fs.mkdirSync(task,{recursive:true});const manifest=shaFile(path.join(pkg,'MANIFEST.json')),review={schema_version:'evidence-contract-package-review-v1',task_id:'research-gemini-evaluator-evidence-contract-conformance-v1',decision:'PASS',manifest_sha256:manifest,authorized_cells:CELL_ORDER};fs.writeFileSync(path.join(repo,GATE_PATHS.PACKAGE_REVIEW),jsonBytes(review));fs.writeFileSync(path.join(repo,GATE_PATHS.EXECUTION_AUTHORIZATION),jsonBytes({schema_version:'evidence-contract-execution-authorization-v1',task_id:'research-gemini-evaluator-evidence-contract-conformance-v1',decision:'AUTHORIZED',manifest_sha256:manifest,package_review_sha256:shaFile(path.join(repo,GATE_PATHS.PACKAGE_REVIEW)),authorized_cells:CELL_ORDER,agy_process_budget:5,inference_call_budget:5,max_attempts:1,retries:0}));return repo}
function copyPackage(){const tmp=makeTemp(),pkg=path.join(tmp,'evidence/quality/model-probes/gemini-evaluator-evidence-contract-conformance-v1');fs.mkdirSync(path.dirname(pkg),{recursive:true});fs.cpSync(root,pkg,{recursive:true});return{tmp,pkg,repo:gateRepo(pkg)}}
function cellMetrics(cell,rate,count=1,stRate=rate){return{cell,metrics:{candidate_count:count,evidence_membership_rate:rate,source_target_only_evidence_membership_rate:stRate}}}
let checks=0;const check=(condition,message)=>{checks++;assert(condition,message)};
try{
  check(checkManifest(root).length===0,'manifest');check(checkFreeze(root).errors.length===0,'freeze');const a=build(root),b=build(root);check(JSON.stringify(a.requests.map(x=>x.sha256))===JSON.stringify(b.requests.map(x=>x.sha256)),'deterministic rebuild');check(a.requests.length===5,'five requests');check(JSON.stringify(a.requests.map(x=>x.cell))===JSON.stringify(CELL_ORDER),'order');
  const base=splitRequest(a.requests[0].bytes);for(const r of a.requests){const q=splitRequest(r.bytes);check(JSON.stringify(q.input.items.map(({source_context,...x})=>x))===JSON.stringify(base.input.items),`items ${r.cell}`);check(normalizePrompt(q.prompt)===normalizePrompt(base.prompt),`prompt factor ${r.cell}`);check(JSON.stringify(normalizeSchema(q.schema))===JSON.stringify(normalizeSchema(base.schema)),`schema factor ${r.cell}`);check(normalizedFactorBytes(r.bytes).equals(normalizedFactorBytes(a.requests[0].bytes)),`exact factor ${r.cell}`);check(r.context?q.input.items.every(x=>x.source_context.includes(x.source)):q.input.items.every(x=>!('source_context'in x)),`context shape ${r.cell}`)}
  check(a.requests.filter(x=>!x.context).length===4,'four A cells');check(a.requests.slice(0,4).every(x=>x.utf8_bytes>=4096&&x.utf8_bytes<=12288),'A bounds');check(a.requests[4].utf8_bytes>=25600&&a.requests[4].utf8_bytes<=40960,'C bounds');
  const contextSource=fs.readFileSync(path.join(root,'CONTEXT-SOURCE.json'),'utf8');check(!/(?:categor|taxonom|independent|item|task|mismatch|candidate|translation|review|instruction)/iu.test(contextSource),'context cue absence');check(JSON.parse(fs.readFileSync(path.join(root,'frozen/CONTEXTS.json'),'utf8')).items.every(x=>!/EC-I\d|catalog card/iu.test(x.source_context)),'context identity cue absence');
  const generic=fs.readFileSync(path.join(root,'model-facing/prompts/P0-GENERIC.md'),'utf8'),prior=fs.readFileSync(path.resolve(root,'../gemini-context-counterexample-reviewer-v5-execution-v5/model-facing/prompts/GENERIC.md'),'utf8');check(generic===prior,'generic predecessor identity');const s0=base.schema,s2=splitRequest(a.requests[1].bytes).schema;check(JSON.stringify(normalizeSchema(s2))===JSON.stringify(s0),'S2 exact factor');const p1=splitRequest(a.requests[2].bytes).prompt,p12=splitRequest(a.requests[3].bytes).prompt;check(p12===p1.replaceAll('`evidence`','`evidence_quote`'),'combined substitution');check(p1.includes('`source_context` when present, character for character'),'P1 when present');check(JSON.stringify(s2).includes('source_context when present'),'S2 when present');
  const valid=parseOutput(output(base.input),base.input,'S0');check(valid.valid,'S0 registered alias');const cross=parseOutput(output(base.input,'evidence_quote'),base.input,'S0');check(cross.valid,'S0 alternate alias');const crossMetrics=metrics(cross.normalized,base.input);check(crossMetrics.registered_field_name_rate===0,'alternate alias recorded');const registeredMetrics=metrics(valid.normalized,base.input);check(registeredMetrics.registered_field_name_rate===1,'registered alias recorded');const both=output(base.input);both.items[0].candidates[0].evidence_quote='At';check(!parseOutput(both,base.input,'S0').valid,'both aliases rejected');const neither=output(base.input);delete neither.items[0].candidates[0].evidence;check(!parseOutput(neither,base.input,'S0').valid,'neither alias rejected');
  const bad=metrics(parseOutput(output(base.input,'evidence','membership'),base.input,'S0').normalized,base.input);check(bad.evidence_membership_rate===0&&bad.target_span_membership_rate===0,'strict membership continues');check(bad.explanatory_prose_proxy_membership_invalid_count===1&&bad.explanatory_prose_proxy_membership_valid_count===0,'invalid proxy split');const punct=output(base.input);punct.items[0].candidates[0].evidence=base.input.items[0].source;const punctMetrics=metrics(parseOutput(punct,base.input,'S0').normalized,base.input);check(punctMetrics.explanatory_prose_proxy_membership_valid_count===1,'valid punctuation proxy split');
  const contextInput=splitRequest(a.requests[4].bytes).input,contextOnly=output(contextInput);contextOnly.items[0].candidates[0].evidence='Rain had stopped';const restricted=metrics(parseOutput(contextOnly,contextInput,'S0').normalized,contextInput);check(restricted.evidence_membership_rate===1&&restricted.source_target_only_evidence_membership_rate===0,'restricted context metric');const zero=metrics({items:base.input.items.map(x=>({item_id:x.item_id,candidates:[]}))},base.input);check(zero.status==='UNINFORMATIVE_ZERO_CANDIDATES'&&zero.evidence_membership_rate===null&&zero.registered_field_name_rate===null,'zero null rates');
  const nullInteraction=interpret([cellMetrics(CELL_ORDER[0],0),cellMetrics(CELL_ORDER[1],null,0,null),cellMetrics(CELL_ORDER[2],1),cellMetrics(CELL_ORDER[3],1),cellMetrics(CELL_ORDER[4],1)]);check(!nullInteraction.some(x=>x.interpretation.includes('interaction matters')),'null cannot trigger interaction');check(nullInteraction.every(x=>x.caveat===INTERPRETATION_CAVEAT&&x.supporting_cells),'interpretation support and caveat');const contextInterpretation=interpret([cellMetrics(CELL_ORDER[0],1,1,1),cellMetrics(CELL_ORDER[1],1),cellMetrics(CELL_ORDER[2],1),cellMetrics(CELL_ORDER[3],1),cellMetrics(CELL_ORDER[4],1,1,0)]);check(contextInterpretation.some(x=>x.interpretation.includes('source/target-only')),'restricted context interpretation');
  const foreign=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-contract-v1-foreign-'));const own=makeTemp();cleanOwned();check(fs.existsSync(foreign)&&!fs.existsSync(own),'concurrent process-scoped cleanup');fs.rmSync(foreign,{recursive:true,force:true});
  const pre=preflight(root,path.resolve(root,'../../../..'));check(pre.decision==='NO_GO_REQUIRED_GATES'&&pre.execution_state==='NO_RUN'&&pre.agy_processes_spawned===0&&pre.inference_calls_made===0,'NO_RUN preflight');
  const {pkg,repo}=copyPackage();check(preflight(pkg,repo).decision==='GO','gated mock copy');let calls=0;for(const cell of CELL_ORDER){const entry=build(pkg).requests.find(x=>x.cell===cell),req=splitRequest(entry.bytes),registered=entry.schema.endsWith('S2.json')?'evidence_quote':'evidence',key=cell==='schema-p0-s2-a'?'evidence':registered,mode=cell==='baseline-p0-s0-a'?'membership':'valid',r=runCell(pkg,repo,cell,()=>{calls++;return{exit_code:0,stdout:envelope(cell==='context-p0-s0-c'?{items:req.input.items.map(x=>({item_id:x.item_id,candidates:[]}))}:output(req.input,key,mode)),stderr:Buffer.alloc(0),timed_out:false}});check(r.continue_authorized,`mock continue ${cell}`)}check(calls===5,'exact 5/5');check(derive(pkg).agy_processes_spawned===5,'ledger five starts');const result=postRun(pkg);check(result.decision==='DESCRIPTIVE_PILOT_COMPLETE'&&result.cells[1].metrics.registered_field_name_rate===0,'post-run alias metric');check(result.cells[4].metrics.status==='UNINFORMATIVE_ZERO_CANDIDATES','zero continues');
  const ex=copyPackage(),reqEx=splitRequest(build(ex.pkg).requests[0].bytes),thrown=Object.assign(Error('capture failed'),{stdout:envelope(output(reqEx.input)),stderr:Buffer.from('diagnostic')});const stopped=runCell(ex.pkg,ex.repo,CELL_ORDER[0],()=>{throw thrown});const exState=derive(ex.pkg),exFinish=exState.cells[CELL_ORDER[0]].finish;check(!stopped.continue_authorized&&!!exFinish,'post-spawn exception FINISH');check(exFinish.stdout_sha256===sha256(thrown.stdout)&&exFinish.stderr_sha256===sha256(thrown.stderr),'exception capture hashes');check(fs.readFileSync(path.join(ex.pkg,capturePaths(CELL_ORDER[0]).stderr)).equals(thrown.stderr),'exception stderr preserved');check(()=>{try{runCell(ex.pkg,ex.repo,CELL_ORDER[0],()=>{throw Error('retry')});return false}catch(e){return /ATTEMPT_EXHAUSTED/.test(e.message)}} ,'never retry');
  const malformed=copyPackage(),ledgerPath=path.join(malformed.pkg,'execution/LEDGER.jsonl');fs.mkdirSync(path.dirname(ledgerPath),{recursive:true});fs.writeFileSync(ledgerPath,`${JSON.stringify({event:'START',cell:CELL_ORDER[0],attempt:1,started_at:'x',extra:true})}\n`);check(derive(malformed.pkg).errors.some(x=>x.startsWith('START_KEYS:')),'START keys rejected');fs.writeFileSync(ledgerPath,`${JSON.stringify({event:'START',cell:CELL_ORDER[0],attempt:1,started_at:'x'})}\n${JSON.stringify({event:'FINISH',cell:CELL_ORDER[0],attempt:1,started_at:'x',finished_at:'y',exit_code:0,stdout_sha256:'x',stderr_sha256:'y',process_success:true,envelope_schema_valid:true,raw_path:null,extra:true})}\n`);check(derive(malformed.pkg).errors.some(x=>x.startsWith('FINISH_KEYS:')),'FINISH keys rejected');
  const predecessor=treeBinding(path.resolve(root,'../../../..'),'evidence/quality/model-probes/gemini-context-counterexample-reviewer-v5-execution-v5');check(predecessor.tree_sha256==='55dfb7bda36d2e06083c349bbb79e6b1de35e2019c1055c989633d6ef523877a','predecessor immutable');check(!fs.existsSync(path.join(root,'execution')),'package temp clean');console.log(JSON.stringify({ok:true,checks,requests:5,items:16,mock_spawns:calls,temp_scope:runScope},null,2));
}finally{cleanOwned()}
