#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';import{jsonBytes,readCanonical,sha256,writeExclusive}from'./lib.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
export const CELL_ORDER=['h1-baseline-r1','h2-hardened-r1','h2-baseline-r1','h1-hardened-r1','h2-baseline-r2','h1-baseline-r2','h1-hardened-r2','h2-hardened-r2','h1-hardened-r3','h2-baseline-r3','h2-hardened-r3','h1-baseline-r3'];
export const factors=cell=>{const m=/^(h[12])-(baseline|hardened)-r([123])$/u.exec(cell);if(!m)throw Error(`CELL:${cell}`);return{dataset:m[1].toUpperCase(),condition:m[2],repetition:Number(m[3]),prompt:m[2]==='baseline'?'P0':'P1',schema:m[2]==='baseline'?'S0':'S2'};};
const markerI='\nINPUT JSON:\n',markerS='\n\nOUTPUT SCHEMA:\n';
const forbidden=/(?:\/(?:home|Users|root|tmp|opt|var|mnt)\/|sealed.?reference|adjudicat|defect.?id|provenance|api.?key|access.?token|client.?secret|credential|origin_revision|fixed_source_identity|translation_baseline_commit)/iu;
export function splitRequest(bytes){const t=Buffer.from(bytes).toString('utf8'),a=t.indexOf(markerI),b=t.indexOf(markerS);if(a<0||b<a)throw Error('REQUEST_FORMAT');return{prompt:t.slice(0,a),inputText:t.slice(a+markerI.length,b),input:JSON.parse(t.slice(a+markerI.length,b)),schemaText:t.slice(b+markerS.length),schema:JSON.parse(t.slice(b+markerS.length))};}
const compact=o=>JSON.stringify(o);
function effectivePrompt(root,f){const b=fs.readFileSync(path.join(root,`model-facing/prompts/${f.prompt==='P0'?'P0-GENERIC.md':'P1-FIELD-RULES.md'}`));if(f.condition==='baseline')return b;const t=b.toString('utf8'),n=t.match(/`evidence`/gu)||[];if(n.length!==2)throw Error('P1_TOKEN_COUNT');return Buffer.from(t.replaceAll('`evidence`','`evidence_quote`'));}
function render(prompt,input,schema){return Buffer.concat([prompt,Buffer.from('INPUT JSON:\n'),Buffer.from(compact(input)),Buffer.from(markerS),Buffer.from(compact(schema))]);}
export function build(root=here){
 const design=readCanonical(path.join(root,'DESIGN-CONTRACT.json'));if(JSON.stringify(design.registered_order)!==JSON.stringify(CELL_ORDER))throw Error('ORDER');
 const prompts={P0:fs.readFileSync(path.join(root,'model-facing/prompts/P0-GENERIC.md')),P1:fs.readFileSync(path.join(root,'model-facing/prompts/P1-FIELD-RULES.md'))};
 const schemas={S0:readCanonical(path.join(root,'model-facing/schemas/S0.json')),S2:readCanonical(path.join(root,'model-facing/schemas/S2.json'))};
 const data={H1:readCanonical(path.join(root,'model-facing/datasets/H1.json')),H2:readCanonical(path.join(root,'model-facing/datasets/H2.json'))};
 for(const d of Object.keys(data)){const ids=data[d].items.map(x=>x.item_id);if(ids.length!==24||ids.some((x,i)=>x!==`${d}-I${String(i+1).padStart(3,'0')}`)||!data[d].items.every(x=>JSON.stringify(Object.keys(x).sort())===JSON.stringify(['item_id','source','target'])))throw Error(`DATASET:${d}`);if(d==='H1'&&new Set(data[d].items.map(x=>x.source)).size!==24)throw Error('H1_DUPLICATE_SOURCE');}
 const requests=[];for(const cell of CELL_ORDER){const f=factors(cell),prompt=effectivePrompt(root,f),schema=schemas[f.schema],bytes=render(prompt,data[f.dataset],schema),text=bytes.toString('utf8');if(forbidden.test(text))throw Error(`MODEL_LEAK:${cell}`);const q=splitRequest(bytes);if(JSON.stringify(q.input)!==JSON.stringify(data[f.dataset])||JSON.stringify(q.schema)!==JSON.stringify(schema)||q.prompt!==prompt.toString('utf8').trimEnd())throw Error(`RENDER:${cell}`);requests.push({cell,...f,path:`model-facing/requests/${cell}.txt`,sha256:sha256(bytes),utf8_bytes:bytes.length,prompt_sha256:sha256(prompt),base_prompt_sha256:sha256(prompts[f.prompt]),schema_sha256:sha256(fs.readFileSync(path.join(root,`model-facing/schemas/${f.schema}.json`))),dataset_sha256:sha256(fs.readFileSync(path.join(root,`model-facing/datasets/${f.dataset}.json`))),item_ids:q.input.items.map(x=>x.item_id),bytes});}
 return{requests,manifest:{schema_version:'gemini-evaluator-contract-effectiveness-request-manifest-v2',fixed_order:CELL_ORDER,uniform_rendering_contract:{input_json:'compact JSON.stringify with no insignificant whitespace',schema_json:'compact JSON.stringify with no insignificant whitespace',request_trailing_newline:false,registered_deviation:'Unlike the predecessor pretty-printed request/schema with a trailing LF, every baseline and hardened cell uses the same compact serialization and omits the trailing LF; this removes formatting as a between-condition confound.'},factors:{P0:{sha256:sha256(prompts.P0)},P1:{sha256:sha256(prompts.P1),hardened_effective_sha256:requests.find(x=>x.condition==='hardened').prompt_sha256,transform:'replace both exact `evidence` tokens with `evidence_quote`'},S0:{sha256:sha256(fs.readFileSync(path.join(root,'model-facing/schemas/S0.json'))),field:'evidence'},S2:{sha256:sha256(fs.readFileSync(path.join(root,'model-facing/schemas/S2.json'))),field:'evidence_quote'}},datasets:Object.fromEntries(Object.keys(data).map(d=>[d,{path:`model-facing/datasets/${d}.json`,sha256:sha256(fs.readFileSync(path.join(root,`model-facing/datasets/${d}.json`)),)}])),requests:requests.map(({bytes,...x})=>x)}};
}
export function freeze(root=here){const b=build(root);for(const r of b.requests){const p=path.join(root,r.path);if(fs.existsSync(p)){if(!fs.readFileSync(p).equals(r.bytes))throw Error(`DRIFT:${r.path}`);}else writeExclusive(p,r.bytes);}const p=path.join(root,'frozen/REQUEST-MANIFEST.json'),bytes=jsonBytes(b.manifest);if(fs.existsSync(p)){if(!fs.readFileSync(p).equals(bytes))throw Error('DRIFT:REQUEST-MANIFEST');}else writeExclusive(p,bytes);return{requests:12};}
export function checkFreeze(root=here){try{const b=build(root),errors=[];for(const r of b.requests){const p=path.join(root,r.path);if(!fs.existsSync(p)||!fs.readFileSync(p).equals(r.bytes))errors.push(`DRIFT:${r.path}`);}if(!fs.existsSync(path.join(root,'frozen/REQUEST-MANIFEST.json'))||!fs.readFileSync(path.join(root,'frozen/REQUEST-MANIFEST.json')).equals(jsonBytes(b.manifest)))errors.push('DRIFT:REQUEST-MANIFEST');return{errors,built:b};}catch(e){return{errors:[e.message],built:null};}}
if(import.meta.url===`file://${process.argv[1]}`){try{if(process.argv.includes('--check')){const x=checkFreeze();console.log(JSON.stringify({mode:'CHECK',errors:x.errors,requests:x.built?.requests.length??0},null,2));process.exitCode=x.errors.length?3:0;}else console.log(JSON.stringify(freeze(),null,2));}catch(e){console.error(e.message);process.exitCode=3;}}
