import fs from'node:fs';import path from'node:path';import{CELL_ORDER}from'./freezer.mjs';import{exactKeys,jsonBytes,parseNoDuplicate,readCanonical,writeExclusive}from'./lib.mjs';
export const MAX_ATTEMPTS=1,PROCESS_BUDGET=12,CALL_BUDGET=12;
const startKeys=['schema_version','event','cell','attempt','sequence','agy_processes_spawned','inference_calls_made'];const finishKeys=['schema_version','event','cell','attempt','sequence','exit_code','stdout_sha256','stderr_sha256','process_success','payload_strict_valid','raw_path'];const terminalKeys=['schema_version','status','cell','reason','agy_processes_spawned','inference_calls_made'];
export const pathsFor=cell=>({stdout:`execution/captures/${cell}.stdout.bin`,stderr:`execution/captures/${cell}.stderr.bin`,raw:`execution/RAW/${cell}.json`});
export function derive(root){const file=path.join(root,'execution/LEDGER.jsonl'),terminal=path.join(root,'execution/TERMINAL.json'),state={errors:[],cells:{},agy_processes_spawned:0,inference_calls_made:0,unfinished:null,terminal_failure:false,no_run:!fs.existsSync(file)&&!fs.existsSync(terminal)};if(fs.existsSync(file)){const text=fs.readFileSync(file,'utf8');if(text&&!text.endsWith('\n'))state.errors.push('LEDGER_FINAL_LF');const lines=text.split('\n').filter(Boolean);let open=null;for(let i=0;i<lines.length;i++){let e;try{e=parseNoDuplicate(lines[i],`LEDGER:${i+1}`);}catch(x){state.errors.push(x.message);continue;}if(e.event==='START'){if(!exactKeys(e,startKeys)||e.schema_version!=='holdout-ledger-event-v2'||open||e.sequence!==i+1||e.attempt!==1||e.cell!==CELL_ORDER[state.agy_processes_spawned]||state.cells[e.cell]||e.agy_processes_spawned!==state.agy_processes_spawned+1||e.inference_calls_made!==state.inference_calls_made+1||state.terminal_failure){state.errors.push(`START:${i+1}`);continue;}state.agy_processes_spawned++;state.inference_calls_made++;open=e;state.cells[e.cell]={start:e};}else if(e.event==='FINISH'){if(!exactKeys(e,finishKeys)||e.schema_version!=='holdout-ledger-event-v2'||!open||e.sequence!==i+1||e.cell!==open.cell||e.attempt!==1){state.errors.push(`FINISH:${i+1}`);continue;}state.cells[e.cell].finish=e;open=null;if(!e.process_success||!e.payload_strict_valid)state.terminal_failure=true;}else state.errors.push(`EVENT:${i+1}`);}state.unfinished=open;}
 if(fs.existsSync(terminal)){try{const t=readCanonical(terminal),countsMatch=t.agy_processes_spawned===state.agy_processes_spawned&&t.inference_calls_made===state.inference_calls_made,nextCell=CELL_ORDER[state.agy_processes_spawned]??null;if(!exactKeys(t,terminalKeys)||t.schema_version!=='holdout-prestart-terminal-v2'||t.status!=='TERMINAL_STOP'||typeof t.reason!=='string'||t.cell!==nextCell||!countsMatch||state.unfinished||state.terminal_failure)state.errors.push('TERMINAL_INVALID');}catch{state.errors.push('TERMINAL_INVALID');}state.terminal_failure=true;}return state;}
export function start(cell,state){return{schema_version:'holdout-ledger-event-v2',event:'START',cell,attempt:1,sequence:Object.keys(state.cells).length*2+1,agy_processes_spawned:state.agy_processes_spawned+1,inference_calls_made:state.inference_calls_made+1};}
export function finish(s,x){return{schema_version:'holdout-ledger-event-v2',event:'FINISH',cell:s.cell,attempt:1,sequence:s.sequence+1,...x};}
export function append(root,e){const p=path.join(root,'execution/LEDGER.jsonl');fs.mkdirSync(path.dirname(p),{recursive:true});fs.appendFileSync(p,JSON.stringify(e)+'\n',{encoding:'utf8',flag:'a'});}
export function prestartTerminal(root,cell,reason,state=derive(root)){if(state.errors.length||state.unfinished||state.terminal_failure||cell!==CELL_ORDER[state.agy_processes_spawned])throw Error('PRESTART_TERMINAL_STATE');writeExclusive(path.join(root,'execution/TERMINAL.json'),jsonBytes({schema_version:'holdout-prestart-terminal-v2',status:'TERMINAL_STOP',cell,reason,agy_processes_spawned:state.agy_processes_spawned,inference_calls_made:state.inference_calls_made}));}
export function rawValue(cell,entry,normalized,metadata){return{schema_version:'gemini-evaluator-contract-effectiveness-raw-v2',cell,condition:entry.condition,dataset:entry.dataset,repetition:entry.repetition,request_sha256:entry.sha256,schema_sha256:entry.schema_sha256,authoritative_channel:'structured_output',response_provenance:metadata,normalized_output:normalized};}
