#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{CELL_ORDER,factors,splitRequest}from'./freezer.mjs';import{derive,pathsFor}from'./ledger.mjs';import{parseCapture}from'./parser.mjs';import{mechanicalMetrics,variance}from'./metrics.mjs';import{loadReference,scoreDataset,deriveAcrossRuns}from'./scorer.mjs';import{jsonBytes,readCanonical,shaFile,writeExclusive}from'./lib.mjs';import{staticChecks}from'./preflight.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../../..');
const caveats={sample_size:'n=3 per dataset/condition; descriptive only; no significance claim.',decoding:'Decoding is unpinned.',caching:'Provider caching, shared infrastructure, or hidden state may make repetitions non-independent.',order:'Frozen interleaving reduces but cannot remove time-order confounding.',route:'Local executable/argv attestation only; no provider-side served-model proof.'};
function base(root,state,errors){return{schema_version:'gemini-evaluator-contract-effectiveness-result-v2',manifest_sha256:fs.existsSync(path.join(root,'MANIFEST.json'))?shaFile(path.join(root,'MANIFEST.json')):null,caveats,agy_processes_spawned:state.agy_processes_spawned,inference_calls_made:state.inference_calls_made,errors};}
export function evaluateAdoption(datasets,runs){const mechanicalExceptions=[];for(const d of ['H1','H2'])for(const r of datasets[d].hardened.measured)if(r.mechanical.candidate_count>0&&r.mechanical.quote_and_span_valid_rate!==1)mechanicalExceptions.push(`${d}:r${r.repetition}`);const evals={};for(const d of ['H1','H2']){const pairs=[];for(let repetition=1;repetition<=3;repetition++){const b=datasets[d].baseline.measured.find(x=>x.repetition===repetition).effectiveness,h=datasets[d].hardened.measured.find(x=>x.repetition===repetition).effectiveness;const additionalMisses=(h.reference_defect_count-h.matched_reference_defect_count)-(b.reference_defect_count-b.matched_reference_defect_count),additionalCleanFP=h.clean_item_false_positive_count-b.clean_item_false_positive_count;pairs.push({repetition,additional_missed_reference_defects:additionalMisses,additional_clean_item_false_positives:additionalCleanFP,passes:additionalMisses<=1&&additionalCleanFP<=1});}evals[d]={paired_repetitions:pairs,passing_repetitions:pairs.filter(x=>x.passes).length,passes:pairs.filter(x=>x.passes).length>=2};}const pass=!mechanicalExceptions.length&&evals.H1.passes&&evals.H2.passes,zeroRuns=runs.filter(x=>x.mechanical.zero_candidate_run).map(x=>x.cell);return{status:pass?'PASS':'NO_GO_PRODUCTION_INTEGRATION',mechanical_quote_span_gate:{passes:!mechanicalExceptions.length,exceptions:mechanicalExceptions},effectiveness_noninferiority_gate:evals,zero_candidate_runs:zeroRuns};}
export function postRun(root=here,repoRoot=repo,{write=false}={}){const state=derive(root),errors=[...state.errors,...staticChecks(root,repoRoot)],manifest=readCanonical(path.join(root,'frozen/REQUEST-MANIFEST.json'));if(state.no_run){const out={...base(root,state,errors),decision:errors.length?'INVALID_ARTIFACTS':'NO_RUN',matrix_complete:false,effectiveness_revealed:false,runs:[],datasets:{},adoption_gate:{status:'NOT_EVALUATED'}};if(write)writeResult(root,out);return out;}
 const runs=[],artifacts={};if(fs.existsSync(path.join(root,'execution/LEDGER.jsonl')))artifacts.ledger={path:'execution/LEDGER.jsonl',sha256:shaFile(path.join(root,'execution/LEDGER.jsonl'))};if(fs.existsSync(path.join(root,'execution/TERMINAL.json')))artifacts.prestart_terminal={path:'execution/TERMINAL.json',sha256:shaFile(path.join(root,'execution/TERMINAL.json'))};for(const cell of CELL_ORDER){const c=state.cells[cell],fin=c?.finish,f=factors(cell),entry=manifest.requests.find(x=>x.cell===cell);let normalized=null,mechanical=null;if(fin?.process_success&&fin.payload_strict_valid&&fin.raw_path)try{const input=splitRequest(fs.readFileSync(path.join(root,entry.path))).input,parsed=parseCapture(fs.readFileSync(path.join(root,pathsFor(cell).stdout)),input,f.condition),raw=readCanonical(path.join(root,fin.raw_path));if(!parsed.valid||JSON.stringify(parsed.normalized)!==JSON.stringify(raw.normalized_output)||JSON.stringify(parsed.envelope_metadata)!==JSON.stringify(raw.response_provenance))throw Error('CAPTURE_RAW_REPLAY_MISMATCH');normalized=parsed.normalized;mechanical=mechanicalMetrics(normalized,input);}catch(e){errors.push(`${cell}:${e.message}`);}runs.push({cell,...f,attempted:!!c,process_success:fin?.process_success??false,payload_strict_valid:fin?.payload_strict_valid??false,mechanical,normalized});for(const[k,p]of Object.entries(pathsFor(cell)))if(fs.existsSync(path.join(root,p)))artifacts[`${cell}:${k}`]={path:p,sha256:shaFile(path.join(root,p))};}
 const complete=state.agy_processes_spawned===12&&state.inference_calls_made===12&&!state.unfinished&&!state.terminal_failure&&runs.length===12&&runs.every(x=>x.process_success&&x.payload_strict_valid&&x.normalized)&&!errors.length;if(!complete){const out={...base(root,state,errors),decision:'MATRIX_STOPPED_OR_INCOMPLETE',matrix_complete:false,effectiveness_revealed:false,runs:runs.map(({normalized,...x})=>x),datasets:{},adoption_gate:{status:'NOT_EVALUATED'},artifacts};if(write)writeResult(root,out);return out;}
 // The sealed reference is first parsed only after all twelve strict successful executions.
 const reference=loadReference(root),datasets={};for(const dataset of ['H1','H2']){const input=readCanonical(path.join(root,`model-facing/datasets/${dataset}.json`)),byCondition={};for(const condition of ['baseline','hardened']){const rs=runs.filter(x=>x.dataset===dataset&&x.condition===condition).sort((a,b)=>a.repetition-b.repetition),measured=rs.map(x=>({repetition:x.repetition,kind:'MEASURED_SINGLE_RUN',mechanical:x.mechanical,effectiveness:scoreDataset(x.normalized,input,reference.datasets[dataset])})),derived=deriveAcrossRuns(rs,input,reference.datasets[dataset]);byCondition[condition]={measured,descriptive_derived:derived,variance:{candidate_count:variance(measured.map(x=>x.mechanical.candidate_count)),defect_level_recall:variance(measured.map(x=>x.effectiveness.defect_level_recall)),clean_item_specificity:variance(measured.map(x=>x.effectiveness.clean_item_specificity)),precision:variance(measured.map(x=>x.effectiveness.precision).filter(x=>x!==null)),balanced_accuracy:variance(measured.map(x=>x.effectiveness.balanced_accuracy))}};}datasets[dataset]=byCondition;}
 const adoption=evaluateAdoption(datasets,runs),pass=adoption.status==='PASS';const out={...base(root,state,errors),decision:pass?'DESCRIPTIVE_COMPLETE_ADOPTION_GATE_PASS':'DESCRIPTIVE_COMPLETE_NO_GO',matrix_complete:true,effectiveness_revealed:true,headline_rule:'H1 and H2 remain separate; no pooled headline.',runs:runs.map(({normalized,...x})=>x),datasets,adoption_gate:adoption,artifacts};if(write)writeResult(root,out);return out;}
function writeResult(root,out){const p=path.join(root,'RESULT.json');if(fs.existsSync(p))throw Error('RESULT_COLLISION');writeExclusive(p,jsonBytes(out));}
if(import.meta.url===`file://${process.argv[1]}`){const x=postRun(here,repo,{write:process.argv.includes('--write')});console.log(JSON.stringify(x,null,2));process.exitCode=['NO_RUN','DESCRIPTIVE_COMPLETE_ADOPTION_GATE_PASS','DESCRIPTIVE_COMPLETE_NO_GO'].includes(x.decision)?0:3;}
