#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import{execFileSync}from'node:child_process';import{fileURLToPath}from'node:url';import{checkManifest}from'./build-manifest.mjs';import{checkFreeze,CELL_ORDER}from'./freezer.mjs';import{readCanonical,sha256,shaFile,trackedCleanErrors,walk}from'./lib.mjs';import{derive}from'./ledger.mjs';import{validateGates}from'./gate-reader.mjs';import{validateHostValues}from'./host-validation.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../../..'),host='/home/yun/projects/t-engine4/game';
export function staticChecks(root=here,repoRoot=repo,{requireZero=false}={}){const errors=[...checkManifest(root).map(x=>`manifest:${x}`)],fr=checkFreeze(root);errors.push(...fr.errors.map(x=>`freeze:${x}`));
 try{const p=readCanonical(path.join(root,'PREDECESSOR-BINDING.json')),q=p.predecessor,hashes=['terminal_tree_sha256','terminal_correction_sha256','generated_result_sha256','ledger_sha256'];if(p.schema_version!=='gemini-evaluator-contract-effectiveness-predecessor-binding-v2'||!q||q.task_id!=='research-gemini-evaluator-contract-effectiveness-holdout-v1'||hashes.some(k=>!/^[0-9a-f]{64}$/u.test(q[k]))||p.dynamic_imports_allowed!==false)errors.push('PREDECESSOR_BINDING_INVALID');}catch(e){errors.push(`PREDECESSOR:${e.message}`);}
 try{const b=readCanonical(path.join(root,'SOURCE-BINDINGS.json'));for(const x of b.tracked_evidence_files)if(!fs.existsSync(path.join(repoRoot,x.path))||shaFile(path.join(repoRoot,x.path))!==x.sha256)errors.push(`SOURCE_DRIFT:${x.path}`);errors.push(...trackedCleanErrors(repoRoot,b.tracked_evidence_files.map(x=>x.path)));for(const x of b.task_handoff_inputs)if(!fs.existsSync(path.join(repoRoot,x.path))||shaFile(path.join(repoRoot,x.path))!==x.sha256)errors.push(`TASK_INPUT_DRIFT:${x.path}`);for(const x of b.historical_git_inputs){try{const bytes=execFileSync('git',['-C',repoRoot,'show',`${x.commit}:${x.path}`],{maxBuffer:64*1024*1024}),oid=execFileSync('git',['-C',repoRoot,'rev-parse',`${x.commit}:${x.path}`],{encoding:'utf8',maxBuffer:1024*1024}).trim();if(sha256(bytes)!==x.sha256||oid!==x.git_blob_oid)errors.push(`HISTORICAL_DRIFT:${x.path}`);}catch{errors.push(`HISTORICAL_UNREADABLE:${x.path}`);}}for(const x of b.fixed_source_files)if(!fs.existsSync(path.join(host,x.source_path))||shaFile(path.join(host,x.source_path))!==x.source_file_sha256)errors.push(`FIXED_SOURCE_DRIFT:${x.source_path}`);if(shaFile(path.join(root,b.reference_inputs.sealed_reference_path))!==b.reference_inputs.sealed_reference_sha256)errors.push('SEALED_REFERENCE_HASH_DRIFT');for(const d of ['H1','H2'])if(shaFile(path.join(root,`model-facing/datasets/${d}.json`))!==b.reference_inputs[`${d}_model_input_sha256`])errors.push(`DATA_HASH_DRIFT:${d}`);}catch(e){errors.push(`SOURCE_BINDINGS:${e.message}`);}
 try{const h=validateHostValues(root,repoRoot,{hostRoot:host});errors.push(...h.errors.map(x=>`HOST_VALUES:${x}`));}catch(e){errors.push(`HOST_VALUES:${e.message}`);}
 try{const route=readCanonical(path.join(root,'ROUTE-CONTRACT.json')).cli_contract,s=fs.lstatSync(route.executable);if(route.executable!=='/home/yun/.local/lib/agy-pinned/c05ce64fa27211121aff092e307e3281cdd9de2021d735a56ea556b8c7927fe8/agy'||route.executable_sha256!=='c05ce64fa27211121aff092e307e3281cdd9de2021d735a56ea556b8c7927fe8'||route.executable_mode!=='0555'||!s.isFile()||s.isSymbolicLink()||(s.mode&0o777)!==0o555||shaFile(route.executable)!==route.executable_sha256||route.model!=='gemini-3.7-flash-high'||route.effort!=='high'||route.mode!=='plan')errors.push('ROUTE_NOT_ELIGIBLE');}catch(e){errors.push(`ROUTE:${e.message}`);}
 const pred=path.join(repoRoot,'evidence/quality/model-probes/gemini-evaluator-original-items-prompt-schema-matrix-v4-network-retry');for(const p of ['P0-GENERIC.md','P1-FIELD-RULES.md'])if(!fs.readFileSync(path.join(root,'model-facing/prompts',p)).equals(fs.readFileSync(path.join(pred,'model-facing/prompts',p))))errors.push(`PROMPT_SEMANTICS:${p}`);for(const n of ['S0','S2']){const s=JSON.parse(fs.readFileSync(path.join(pred,`model-facing/schemas/${n}.json`))),a=s.properties.items;a.minItems=a.maxItems=24;a.items.properties.item_id.pattern='^H[12]-I[0-9]{3}$';if(JSON.stringify(s)!==JSON.stringify(readCanonical(path.join(root,`model-facing/schemas/${n}.json`))))errors.push(`SCHEMA_SEMANTICS:${n}`);}
 const leak=/(?:\/(?:home|Users|root|tmp|opt|var|mnt)\/|sealed.?reference|adjudicat|defect.?id|provenance|origin_revision|fixed_source_identity|translation_baseline_commit|api.?key|access.?token|credential)/iu;for(const p of walk(path.join(root,'model-facing')))if(leak.test(fs.readFileSync(path.join(root,'model-facing',p),'utf8')))errors.push(`MODEL_FACING_LEAK:${p}`);
 const temps=walk(root).filter(p=>/(?:^|\/)(?:tmp|temp)(?:\/|$)|\.tmp$/iu.test(p));if(temps.length)errors.push(...temps.map(x=>`TEMP_ARTIFACT:${x}`));if(requireZero&&(fs.existsSync(path.join(root,'execution'))))errors.push('NONZERO_EXECUTION_ARTIFACT');if(fr.built&&JSON.stringify(fr.built.requests.map(x=>x.cell))!==JSON.stringify(CELL_ORDER))errors.push('REQUEST_ORDER');return errors;}
export function preflight(root=here,repoRoot=repo){const state=derive(root),errors=staticChecks(root,repoRoot,{requireZero:state.no_run});errors.push(...state.errors.map(x=>`ledger:${x}`));const gates=validateGates(root,repoRoot);return{schema_version:'gemini-evaluator-contract-effectiveness-preflight-v2',decision:errors.length?'NO_GO_STATIC_INTEGRITY':gates.valid?'GO':'NO_GO_REQUIRED_GATES',execution_state:state.no_run?'NO_RUN':state.terminal_failure?'TERMINAL_STOP':'PARTIAL_OR_COMPLETE',static_integrity:errors.length?'FAIL':'PASS',manifest_sha256:fs.existsSync(path.join(root,'MANIFEST.json'))?shaFile(path.join(root,'MANIFEST.json')):null,registered_cells:CELL_ORDER,blocked_gates:gates.errors,agy_processes_spawned:state.agy_processes_spawned,inference_calls_made:state.inference_calls_made,errors};}
if(import.meta.url===`file://${process.argv[1]}`){const x=preflight();console.log(JSON.stringify(x,null,2));process.exitCode=x.decision==='GO'?0:3;}
