import fs from'node:fs';import path from'node:path';import{readCanonical}from'./lib.mjs';
const rate=(n,d)=>d?n/d:null;
export const occurrences=(text,sub)=>{const out=[];if(!sub)return out;for(let at=0;(at=text.indexOf(sub,at))>=0;){out.push([at,at+sub.length]);at+=[...text.slice(at)][0].length;}return out;};
const overlaps=(a,b)=>a[0]<b[1]&&b[0]<a[1];
function eligible(candidate,item,ref){if(candidate.verdict!=='FINDING'||!candidate.target_span_member||!ref.accepted_claim_types.includes(candidate.claim_type))return false;const spans=occurrences(item.target,candidate.target_span);return ref.localization_anchors.some(a=>occurrences(item.target,a).some(g=>spans.some(s=>overlaps(s,g))));}
function patchAccept(candidate,item,ref){if(!candidate.target_span_member)return false;for(const [a,b] of occurrences(item.target,candidate.target_span)){const patched=item.target.slice(0,a)+candidate.correction+item.target.slice(b);if(ref.acceptable_full_targets.includes(patched))return true;}return false;}
function bestMatching(candidates,item,refs){
 let best=[];const edges=candidates.map((c,ci)=>refs.flatMap((r,ri)=>eligible(c,item,r)?[[ci,ri]]:[]));
 const rec=(ci,used,pairs)=>{if(ci===candidates.length){const key=pairs.map(([a,b])=>`${String(a).padStart(2,'0')}:${refs[b].reference_id}`).join('|'),bk=best.map(([a,b])=>`${String(a).padStart(2,'0')}:${refs[b].reference_id}`).join('|');if(pairs.length>best.length||(pairs.length===best.length&&key<bk))best=[...pairs];return;}rec(ci+1,used,pairs);for(const [a,b] of edges[ci])if(!used.has(b)){used.add(b);pairs.push([a,b]);rec(ci+1,used,pairs);pairs.pop();used.delete(b);}};rec(0,new Set(),[]);return best;
}
export function loadReference(root){return readCanonical(path.join(root,'sealed/REFERENCE.json'));}
export function scoreDataset(normalized,input,datasetReference){
 const publicBy=new Map(input.items.map(x=>[x.item_id,x])),outBy=new Map(normalized.items.map(x=>[x.item_id,x])),matches=[],classes=new Map(),detected=new Set();let totalRefs=0,matchedRefs=0,findings=0,matchedCandidates=0,clean=0,cleanNoFp=0,cleanFp=0,defective=0,defectiveDetected=0,defectiveFindings=0,localized=0,correctionOK=0;
 for(const priv of datasetReference.items){const item=publicBy.get(priv.item_id),row=outBy.get(priv.item_id),cs=row.candidates.map(c=>({...c,target_span_member:item.target.includes(c.target_span)})),pos=cs.filter(c=>c.verdict==='FINDING');findings+=pos.length;
  if(priv.truth==='clean'){clean++;if(pos.length){cleanFp++;}else cleanNoFp++;continue;}
  defective++;defectiveFindings+=pos.length;totalRefs+=priv.references.length;for(const r of priv.references){const x=classes.get(r.defect_class)||{reference_count:0,matched_count:0};x.reference_count++;classes.set(r.defect_class,x);}
  const pairs=bestMatching(cs,item,priv.references);matchedRefs+=pairs.length;matchedCandidates+=pairs.length;if(pairs.length){defectiveDetected++;detected.add(priv.item_id);}localized+=pos.filter(c=>priv.references.some(r=>eligible(c,item,r))).length;
  for(const[ci,ri]of pairs){const c=cs[ci],r=priv.references[ri],ok=patchAccept(c,item,r);if(ok)correctionOK++;classes.get(r.defect_class).matched_count++;matches.push({item_id:priv.item_id,candidate_index:ci,reference_id:r.reference_id,defect_class:r.defect_class,correction_acceptable:ok});}
 }
 const sensitivity=rate(defectiveDetected,defective),specificity=rate(cleanNoFp,clean),precision=rate(matchedCandidates,findings),balanced=sensitivity===null||specificity===null?null:(sensitivity+specificity)/2;
 const result={reference_defect_count:totalRefs,matched_reference_defect_count:matchedRefs,defect_level_recall:rate(matchedRefs,totalRefs),defective_item_count:defective,defective_item_detected_count:defectiveDetected,defective_item_sensitivity:sensitivity,clean_item_count:clean,clean_item_false_positive_count:cleanFp,clean_item_specificity:specificity,finding_candidate_count:findings,matched_finding_candidate_count:matchedCandidates,precision,balanced_accuracy:balanced,localization_denominator:'FINDING_CANDIDATES_ON_DEFECTIVE_ITEMS',localization_defective_finding_count:defectiveFindings,localization_acceptable_defective_finding_count:localized,localization_acceptability:rate(localized,defectiveFindings),correction_acceptable_match_count:correctionOK,correction_acceptability:rate(correctionOK,matchedCandidates),defect_class_recall:Object.fromEntries([...classes].sort().map(([k,v])=>[k,{...v,recall:rate(v.matched_count,v.reference_count)}])),matches};
 if(datasetReference.controlled_mutation_count)result.H1_controlled_mutation_sensitivity={controlled_mutation_count:defective,detected_mutation_count:defectiveDetected,sensitivity:rate(defectiveDetected,defective)};
 return result;
}
const tuple=c=>JSON.stringify([c.verdict,c.claim_type,c.target_span,c.correction,c.evidence]);
export function deriveAcrossRuns(runs,input,ref){const byId=new Map(input.items.map(x=>[x.item_id,[]]));for(const run of runs)for(const row of run.normalized.items)for(const c of row.candidates)byId.get(row.item_id).push({run:run.repetition,c});const make=threshold=>({items:input.items.map(item=>{const groups=new Map();for(const x of byId.get(item.item_id)){const k=tuple(x.c),g=groups.get(k)||{c:x.c,reps:new Set()};g.reps.add(x.run);groups.set(k,g);}return{item_id:item.item_id,candidates:[...groups.entries()].filter(([,g])=>g.reps.size>=threshold).sort(([a],[b])=>a.localeCompare(b)).map(([,g])=>g.c)};})});return{union:{kind:'DESCRIPTIVE_DERIVED_UNION',...scoreDataset(make(1),input,ref)},consensus:{kind:'DESCRIPTIVE_DERIVED_CONSENSUS_2_OF_3',...scoreDataset(make(2),input,ref)}};}
