import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";

export const ROUTES = {
  codex: {key:"codex",slug:"codex-gpt-5.6-sol-high",kind:"codex",command:"codex",version:"codex-cli 0.150.1",model:"gpt-5.6-sol",effort:"high",evidence_tier:"REQUESTED_ROUTE_ONLY_UNVERIFIED"},
  opus: {key:"opus",slug:"claude-opus-5-medium-no-advisor",kind:"claude",command:"claude",version:"2.1.251 (Claude Code)",model:"claude-opus-5",effort:"medium",evidence_tier:"STRICT_STREAM_IDENTITY_REQUIRED"},
  glm: {key:"glm",slug:"pi-zai-cn-glm-5.3-flash-high",kind:"pi",command:"pi",version:"0.84.3",provider:"zai-standard-cn",model:"glm-5.3-flash",effort:"high",evidence_tier:"PROVIDER_AND_MODEL_REQUIRED"},
  gemini: {key:"gemini",slug:"agy-gemini-3.7-flash-high",kind:"agy",command:"agy",version:"1.1.22",model:"gemini-3.7-flash-high",effort:"high",evidence_tier:"REQUESTED_ROUTE_ONLY_UNVERIFIED"}
};
export const WAVES = ["A1","B1","B2","A2"];
export const sha = bytes => crypto.createHash("sha256").update(bytes).digest("hex");
export const shaFile = file => sha(fs.readFileSync(file));
export const readJson = file => JSON.parse(fs.readFileSync(file,"utf8"));
export const assert = (x,m) => {if(!x) throw new Error(m);};
export function writeNew(file,bytes){const fd=fs.openSync(file,"wx",0o600);try{fs.writeFileSync(fd,bytes);}finally{fs.closeSync(fd);}}

export function requestFile(here,wave,shard){return path.join(here,`REQUEST-${wave[0]}-SHARD-${String(shard).padStart(2,"0")}.txt`);}
export function attemptDir(here,wave,route,shard,attempt){return path.join(here,"attempts",wave,route.slug,`SHARD-${String(shard).padStart(2,"0")}`,`attempt-${String(attempt).padStart(3,"0")}`);}
export function reserveAttempt(here,wave,route,shard,attempt){const root=path.dirname(attemptDir(here,wave,route,shard,attempt));fs.mkdirSync(root,{recursive:true});const dir=attemptDir(here,wave,route,shard,attempt);fs.mkdirSync(dir,{recursive:false,mode:0o700});return dir;}

const copySecret=(source,dest)=>{const stat=fs.lstatSync(source);assert(stat.isFile()&&!stat.isSymbolicLink(),"unsafe/missing route auth");fs.mkdirSync(path.dirname(dest),{recursive:true,mode:0o700});fs.copyFileSync(source,dest,fs.constants.COPYFILE_EXCL);fs.chmodSync(dest,0o600);};
export function makeRuntime(route){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"scc-runtime-"));fs.chmodSync(root,0o700);const home=path.join(root,"home");fs.mkdirSync(home,{mode:0o700});fs.mkdirSync(path.join(root,"tmp"),{mode:0o700});fs.mkdirSync(path.join(root,"bin"),{mode:0o700});const host=os.homedir();
  if(route.kind==="codex") copySecret(path.join(host,".codex","auth.json"),path.join(home,".codex","auth.json"));
  if(route.kind==="claude") copySecret(path.join(host,".claude",".credentials.json"),path.join(home,".claude",".credentials.json"));
  if(route.kind==="agy") copySecret(path.join(host,".gemini","antigravity-cli","antigravity-oauth-token"),path.join(home,".gemini","antigravity-cli","antigravity-oauth-token"));
  if(route.kind==="pi"){
    const auth=readJson(path.join(host,".pi","agent","auth.json"));const models=readJson(path.join(host,".pi","agent","models.json"));assert(auth[route.provider]?.type==="api_key","Pi auth unavailable");const provider=structuredClone(models.providers?.[route.provider]);assert(provider,"Pi provider unavailable");delete provider.apiKey;provider.models=provider.models.filter(x=>x.id===route.model);assert(provider.models.length===1,"Pi model unavailable");fs.mkdirSync(path.join(home,".pi","agent"),{recursive:true,mode:0o700});writeNew(path.join(home,".pi","agent","auth.json"),`${JSON.stringify({[route.provider]:auth[route.provider]})}\n`);writeNew(path.join(home,".pi","agent","models.json"),`${JSON.stringify({providers:{[route.provider]:provider}})}\n`);
  }
  if(["claude","agy"].includes(route.kind)) writeNew(path.join(root,"bin",route.command),"");
  return root;
}
export function removeTemp(dir,prefix){assert(path.dirname(dir)===os.tmpdir()&&path.basename(dir).startsWith(prefix),"unsafe temp cleanup");fs.rmSync(dir,{recursive:true,force:false});}
export function makeBundle(here,wave,shard){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"scc-bundle-")),id=String(shard).padStart(2,"0");for(const name of [`REQUEST-${wave[0]}-SHARD-${id}.txt`,`OUTBOUND-${wave[0]}-SHARD-${id}.json`,`REVIEWER-SCHEMA.json`])fs.copyFileSync(path.join(here,name),path.join(dir,name),fs.constants.COPYFILE_EXCL);return dir;}
export function envFor(route){const keep=["PATH","LANG","LC_ALL","LC_CTYPE","TZ","TERM","SSL_CERT_FILE","SSL_CERT_DIR","HTTPS_PROXY","HTTP_PROXY","ALL_PROXY","NO_PROXY"];const env={};for(const n of keep)if(typeof process.env[n]==="string")env[n]=process.env[n];env.PATH=`/tmp/route-runtime/bin:${env.PATH??"/usr/local/bin:/usr/bin:/bin"}`;env.HOME="/tmp/route-runtime/home";env.TMPDIR="/tmp/route-runtime/tmp";env.XDG_CONFIG_HOME="/tmp/route-runtime/home/.config";env.XDG_CACHE_HOME="/tmp/route-runtime/home/.cache";env.XDG_STATE_HOME="/tmp/route-runtime/home/.local/state";env.NO_COLOR="1";if(route.kind==="pi"){env.PI_SKIP_VERSION_CHECK="1";env.PI_TELEMETRY="0";}if(route.kind==="claude"){env.CLAUDE_CODE_DISABLE_ADVISOR_TOOL="1";env.CLAUDE_CODE_NO_MODEL_FALLBACK="1";env.CLAUDE_CODE_DISABLE_REFUSAL_FALLBACK="1";env.CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK="1";env.CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1";env.CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION="0";}return env;}
function resolveExe(name){for(const d of (process.env.PATH??"").split(path.delimiter)){const f=path.join(d,name);try{if(fs.statSync(f).isFile()||fs.lstatSync(f).isSymbolicLink())return fs.realpathSync(f);}catch{}}throw new Error(`${name} missing`);}
export function plan(route,wave,request,bundle,runtime){
  const schemaText=fs.readFileSync(path.join(bundle,"REVIEWER-SCHEMA.json"),"utf8");const schema=JSON.parse(schemaText);delete schema.$schema;const schemaArg=JSON.stringify(schema);let args;
  if(route.kind==="codex"){const disabled=["shell_tool","unified_exec","apps","browser_use","browser_use_external","browser_use_full_cdp_access","computer_use","multi_agent","multi_agent_v2","plugins","plugin_sharing","remote_plugin","skill_search","view_image","image_generation","hooks","goals","tool_suggest","tool_call_mcp_elicitation","workspace_dependencies"].flatMap(x=>["--disable",x]);args=[...disabled,"-a","never","exec","-m",route.model,"-c",`model_reasoning_effort=\"${route.effort}\"`,"--ephemeral","--ignore-user-config","--ignore-rules","--skip-git-repo-check","-C","/mnt","-s","read-only","--output-schema","/mnt/REVIEWER-SCHEMA.json","--json","-o","/tmp/route-runtime/last-message.json",request.toString("utf8")];}
  else if(route.kind==="claude")args=["--print","--model",route.model,"--effort",route.effort,"--output-format","stream-json","--verbose","--no-session-persistence","--safe-mode","--restricted","--strict-mcp-config","--mcp-config","{\"mcpServers\":{}}","--disable-slash-commands","--prompt-suggestions","false","--permission-mode","plan","--tools","","--json-schema",schemaArg,"--",request.toString("utf8")];
  else if(route.kind==="pi")args=["--provider",route.provider,"--model",route.model,"--thinking",route.effort,"--no-tools","--no-session","--no-extensions","--no-skills","--no-prompt-templates","--no-themes","--no-context-files","--no-approve","--mode","json","--print","--",request.toString("utf8")];
  else args=["-p",request.toString("utf8"),"--model",route.model,"--effort",route.effort,"--disable-slash-commands","--output-format","json","--print-timeout","25m","--mode","plan","--sandbox","--json-schema","/mnt/REVIEWER-SCHEMA.json"];
  const privateExe=["claude","agy"].includes(route.kind)?["--ro-bind",resolveExe(route.command),`/tmp/route-runtime/bin/${route.command}`]:[];
  const wrapped=["--die-with-parent","--new-session","--cap-drop","ALL","--ro-bind","/","/","--dev","/dev","--proc","/proc","--tmpfs",os.homedir(),"--ro-bind",bundle,"/mnt","--tmpfs","/tmp","--dir","/tmp/route-runtime","--bind",runtime,"/tmp/route-runtime",...privateExe,"--chdir","/mnt","--",route.command,...args];
  return {command:"bwrap",args:wrapped,display_args:args.map(x=>x===request.toString("utf8")?"[REQUEST_BYTES]":x===schemaArg?"[NATIVE_SCHEMA_BYTES]":x)};
}
const unwrap=text=>{const t=text.trim(),m=t.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/iu);return JSON.parse(m?m[1]:t);};
const lines=raw=>raw.split(/\r?\n/u).filter(x=>x.trim()).map(JSON.parse);
const toolSignal=v=>{if(!v||typeof v!=="object")return false;if(typeof v.type==="string"&&/(?:command|web|browser|mcp|subagent)/iu.test(v.type))return true;return Object.values(v).some(x=>Array.isArray(x)?x.some(toolSignal):toolSignal(x));};
export function parseRaw(route,raw,lastMessage){const errors=[];let response=null,identity={};try{
  if(route.kind==="codex"){const ev=lines(raw),msgs=ev.filter(e=>e.type==="item.completed"&&e.item?.type==="agent_message"),done=ev.filter(e=>e.type==="turn.completed");if(msgs.length!==1)errors.push(`Codex agent message count ${msgs.length}`);if(done.length!==1)errors.push(`Codex terminal count ${done.length}`);if(ev.some(e=>e.item&&!['reasoning','agent_message'].includes(e.item.type)))errors.push("Codex tool/non-message item");response=lastMessage?JSON.parse(lastMessage):unwrap(msgs[0]?.item?.text??"");identity={requested_model:route.model,runtime_identity_verified:false,reported_models:[...new Set(ev.flatMap(e=>[e.model,e.item?.model]).filter(Boolean))],usage:done[0]?.usage??null};}
  else if(route.kind==="claude"){const ev=lines(raw),init=ev.filter(e=>e.type==="system"&&e.subtype==="init"),asst=ev.filter(e=>e.type==="assistant"&&e.message),res=ev.filter(e=>e.type==="result"),blocks=asst.flatMap(e=>e.message.content??[]),tools=blocks.filter(b=>b.type==="tool_use"),models=[...new Set(asst.map(e=>e.message.model).filter(Boolean))],used=Object.keys(res[0]?.modelUsage??res[0]?.model_usage??{});if(init.length!==1||res.length!==1)errors.push("Claude init/result cardinality");if(init[0]?.model!==route.model||JSON.stringify(models)!==JSON.stringify([route.model]))errors.push("Claude runtime model mismatch");if(tools.length!==1||tools[0]?.name!=="StructuredOutput")errors.push("Claude non-unique structured output");if(used.some(x=>x!==route.model))errors.push(`Claude ancillary model usage ${used.join(',')}`);if(ev.some(e=>/fallback|advisor/iu.test(`${e.type??''} ${e.subtype??''}`))||ev.some(e=>e.parent_tool_use_id!=null))errors.push("Claude fallback/advisor/subagent signal");if(Object.values(res[0]?.usage?.server_tool_use??{}).some(x=>typeof x==='number'&&x!==0))errors.push("Claude server tool use");response=res[0]?.structured_output??tools[0]?.input??unwrap(res[0]?.result??"");identity={initialized_model:init[0]?.model??null,assistant_models:models,model_usage:used,usage:res[0]?.usage??null};}
  else if(route.kind==="pi"){const ev=lines(raw),ends=ev.filter(e=>e.type==="message_end"&&e.message?.role==="assistant"),m=ends[0]?.message;if(ends.length!==1)errors.push(`Pi assistant count ${ends.length}`);if(ev.some(toolSignal))errors.push("Pi tool signal");if(m?.provider!==route.provider||m?.model!==route.model)errors.push("Pi runtime identity mismatch");response=unwrap((m?.content??[]).filter(b=>b.type==="text").map(b=>b.text).join(""));identity={actual_provider:m?.provider??null,actual_model:m?.model??null,usage:m?.usage??null};}
  else {const env=JSON.parse(raw);if(env.status!=="SUCCESS")errors.push(`agy status ${env.status}`);if(env.model!=null&&env.model!==route.model)errors.push("agy model mismatch");if(env.structured_output==null)errors.push("agy structured_output missing");if(Array.isArray(env.tool_calls)&&env.tool_calls.length)errors.push("agy tool signal");response=env.structured_output;identity={reported_model:env.model??null,runtime_identity_verified:env.model===route.model,usage:env.usage??null};}
}catch(e){errors.push(`parse failure: ${e.message}`);}return {response,identity,errors};}
export function validateResponse(response,input){const errors=[];if(!response||typeof response!=="object"||Array.isArray(response))return ["response not object"];if(JSON.stringify(Object.keys(response).sort())!==JSON.stringify(["items"]))errors.push("top-level keys");if(!Array.isArray(response.items)||response.items.length!==input.items.length)return [...errors,"items length"];
  for(let i=0;i<input.items.length;i++){const r=response.items[i],v=input.items[i];if(!r||typeof r!=="object"||Array.isArray(r)){errors.push(`item ${i} object`);continue;}if(JSON.stringify(Object.keys(r).sort())!==JSON.stringify(["candidates","neutral_id","observation"]))errors.push(`item ${i} keys`);if(r.neutral_id!==v.neutral_id)errors.push(`item ${i} id/order`);if(typeof r.observation!=="string"||!r.observation)errors.push(`item ${i} observation`);if(!Array.isArray(r.candidates)||r.candidates.length>4){errors.push(`item ${i} candidates`);continue;}for(const [j,c] of r.candidates.entries()){if(!c||JSON.stringify(Object.keys(c).sort())!==JSON.stringify(["claim_type","correction","evidence","target_span","verdict"]))errors.push(`item ${i} candidate ${j} keys`);if(!["FINDING","UNCERTAIN"].includes(c?.verdict))errors.push(`item ${i} candidate ${j} verdict`);if(!["VALUE","DIRECTION","CONDITION","SUBJECT","REFERENT","TIMING","SCOPE","ACTION","STATE","ORDER","OMISSION","ADDITION","OTHER"].includes(c?.claim_type))errors.push(`item ${i} candidate ${j} type`);if(typeof c?.target_span!=="string"||!v.target.includes(c.target_span))errors.push(`item ${i} candidate ${j} target span`);if(typeof c?.correction!=="string"||!c.correction)errors.push(`item ${i} candidate ${j} correction`);if(typeof c?.evidence!=="string"||![v.source,v.source_context].filter(x=>typeof x==='string').some(x=>x.includes(c.evidence)))errors.push(`item ${i} candidate ${j} evidence`);}}
  return errors;
}
export function versionCheck(route){const x=spawnSync(route.command,["--version"],{cwd:"/tmp",encoding:"utf8"});return {ok:x.status===0&&x.stdout.trim()===route.version,observed:x.stdout.trim(),status:x.status};}
